### ISSUE TITLE
Table size might be too large

### ISSUE THREAD

**Issue by Ufaowl** [cavaliercoder/libzbxpgsql#10]
Hi again.
I have stumbled upon such a problem. When i tried to get table size of a table which size is 8Gb i get an error from Postgres saying that integer value is out of range. I found out that table size is obtained by this string in pg_table.c:
#define PGSQL_GET_TABLE_SIZE        "SELECT (relpages * 8192) FROM pg_class WHERE relkind='r' AND relname = '%s'"
So relpages*8192 = 8496332800 and it's out of int range which is from	-2147483648 to +2147483647. So i force data type to bigint
#define PGSQL_GET_TABLE_SIZE        "SELECT (relpages::bigint * 8192) FROM pg_class WHERE relkind='r' AND relname = '%s'"
and for other get_table_size items. 

Maybe it's not an issue. But sometimes tables take so much space))

**Comment by cavaliercoder** [comment]
Yes this is definitely an issue in v0.1.3. Fortunately it's already fixed in merge request #1 (although I need to fix it for table size SUMs). I'll be releasing the fix soon in v0.2.0.
