### ISSUE TITLE
Confusion with documentation

### ISSUE THREAD

**Issue by ksemaev** [cavaliercoder/libzbxpgsql#100]
First of all thank you for you wonderful job with this module!

I am trying to implement it, but I absolutely do not understand the principle of it's functionality. I've read this part: https://www.zabbix.com/documentation/3.2/manual/config/items/loadablemodules
I've read documentation http://cavaliercoder.com/libzbxpgsql/documentation/

But I still don't understand how to "Configure Zabbix to use the monitoring role by specifying the user keyword in the first parameter of your item keys. E.g. pg.connect[user=monitoring,postgres]"
(http://cavaliercoder.com/libzbxpgsql/documentation/local-monitoring-agent/)

Where am I supposed to do it? The only string in /etc/zabbix/zabbix_agentd.d/libzbxpgsql.conf
is "LoadModule=libzbxpgsql.so".  So nothing there, what I could do simular to UserParametrs (https://www.zabbix.com/documentation/3.2/manual/config/items/userparameters)

I do understand that it is lack of my zabbix Loadable modules knowlege, but please provide some explanations)

**Comment by cavaliercoder** [comment]
Thank you for your feedback and for taking the time to understand the documentation.
The 'first parameter of your item keys' refers the the item keys in the Template which accompanies the loadable module.

Install the template according to http://cavaliercoder.com/libzbxpgsql/documentation/template-installation/.

Once installed, you'll see from the template (Configuration ->  Templates -> Template App PostgreSQL Server, in Zabbix web console) that the first parameter of all keys actually uses the PG_CONN macro. You can set your connection string in this macro on the macros tab. Ref: http://cavaliercoder.com/libzbxpgsql/documentation/template-configuration/

**Comment by ksemaev** [comment]
Ah, so it was about macros!) Thank you very much for quick response!

**Comment by ksemaev** [comment]
Still confused( (
This page tell me to use to macroses for {$PG_CONN} and {$PG_DB} (why do I need this second macro if I have Database discovery rule).
And this page tell me  to use string pg.connect[user=monitoring,postgres]. This string is two previous macroses combined? Why do I need to see this "parameters of my item keys" if I use macros?

So just to be clear, in simple config with zabbix agent on every monitored node I need to specify one macro for it: {$PG_CONN} => user=monitoring and this would be enough?

And please tell how can I debug this solution? There's nothing in any logs about working libzbxpgsql module.

**Comment by cavaliercoder** [comment]
If you enable debug-level logging for the Zabbix agent, it will include lots of debug log messages for the PostgreSQL module.

PG_CONN should be your connection string _excluding_ the name of the database you wish to connect to. This should be supplied only as the second parameter, PG_DB. As per the documentation:

> Please note that you must not include the dbname= directive in your connection string. This is instead defined in the next macro, to enable discovery of PostgreSQL resources across multiple databases.

This is a limitation of PostgreSQL. It only allows you to monitor a single database for any given connection. To monitor multiple databases, you need multiple connections. The second parameter allows Zabbix to pass a discovered database to item prototypes so they can monitor all discovered databases. However, you still need the PG_DB macro for the initial connection, which is used to perform discovery.

**Comment by ksemaev** [comment]
Thank you!
