### ISSUE TITLE
zabbix_get working but no data in UI

### ISSUE THREAD

**Issue by madchap** [cavaliercoder/libzbxpgsql#101]
Hi,

Using the latest libzbxpgsql rpm on CentOS 7, SELinux in permissive mode. I am running zabbix 3.2.4.

I have configured everything per the doc, using the "local monitoring agent" variant.

If I run a zabbix_get from the zabbix server, such as:
```
$ zabbix_get -s p-db-psql-001 -k pg.version
PostgreSQL 9.5.4 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4), 64-bit

 $ zabbix_get -s p-db-psql-001 -k pg.connect
1

$ zabbix_get -s p-db-psql-001 -k pg.connect
```
Same if I run the command as root.

On the postgres server, where the zabbix-agent is runing as user 'zabbix', I get valid results if running `zabbix_agentd -p |grep '^pg'`. However, if running as user 'root', I get `[m|ZBX_NOTSUPPORTED] [FATAL:  role "root" does not exist
zabbix_agentd [9374]: Error: PostgreSQL: FATAL:  role "root" does not exist`

I have no data coming back up in the UI whatsoever. Yet, all items are in "enabled" mode (and not in "unsupported" or other modes that would indicate an issue).

My pg_ident.conf reads:
```
# MAPNAME       SYSTEM-USERNAME         PG-USERNAME
monitoring      zabbix                  monitoring
```
and I have added the corresponding PG role.

My pg_hba.conf reads:
```
local   all             monitoring                              ident map=monitoring
```

I have no logs to take me any further, unfortunately.

I would appreciate any pointers to make it work.

Thanks!
fred

**Comment by madchap** [comment]
As usual, found the culprit... active checks not configured on the agent (I blame it on puppet ;))

Thanks,
fred

**Comment by cavaliercoder** [comment]
Thanks for posting the outcome. Regards
