### ISSUE TITLE
Cannot get zabbix information from postgresql

### ISSUE THREAD

**Issue by N1k3** [cavaliercoder/libzbxpgsql#108]
Hello!
I have problem with libzbxpgsql on RHEL 7.2
In log zabbix-agent:

> 16593:20171010:104927.512 Got signal [signal:15(SIGTERM),sender_pid:16645,sender_uid:0,reason:0]. Exiting ...
 16593:20171010:104927.516 Zabbix Agent stopped. Zabbix 3.2.7 (revision 70298).
 16681:20171010:104959.941 Starting Zabbix Agent [srv-saumi-khabarovsk-db]. Zabbix 3.2.7 (revision 70298).
 16681:20171010:104959.941 **** Enabled features ****
 16681:20171010:104959.941 IPv6 support:          YES
 16681:20171010:104959.941 TLS support:           YES
 16681:20171010:104959.941 **************************
 16681:20171010:104959.941 using configuration file: /etc/zabbix/zabbix_agentd.conf
 16681:20171010:104959.943 starting agent module libzbxpgsql 1.1.0
 16681:20171010:104959.943 using module configuration file: /etc/zabbix/libzbxpgsql.conf
 16681:20171010:104959.943 loaded modules: libzbxpgsql.so
 16681:20171010:104959.943 agent #0 started [main process]
 16682:20171010:104959.944 agent #1 started [collector]
 16683:20171010:104959.944 agent #2 started [listener #1]
 16684:20171010:104959.944 agent #3 started [listener #2]
 16685:20171010:104959.945 agent #4 started [listener #3]
 16686:20171010:104959.945 agent #5 started [active checks #1]
 16686:20171010:104959.950 PostgreSQL: could not connect to server: Permission denied
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5432?

>  16686:20171010:104959.950 active check "pg.backends.count[host=127.0.0.1 port=5432 user=postgres password=postgres connect_timeout=10,postgres]" is not supported: could not connect to server: Permission denied
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5432?

>  16686:20171010:104959.950 PostgreSQL: could not connect to server: Permission denied
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5432?

>  16686:20171010:104959.950 active check "pg.backends.free[host=127.0.0.1 port=5432 user=postgres password=postgres connect_timeout=10,postgres]" is not supported: could not connect to server: Permission denied
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5432?

I'm use {$PG_CONN} = host=127.0.0.1 port=5432 user=postgres password=postgres connect_timeout=10
{$PG_DB} = postgres

**Comment by cavaliercoder** [comment]
It looks like PostgreSQL is rejecting the credentials you are providing. Please test your connection using another PostgreSQL client and see the support channels for PostgreSQL for further help. I do offer some hints at server configuration in the [libzbxpgsql documentation](http://cavaliercoder.com/libzbxpgsql/documentation/connecting-to-postgresql/).

**Comment by cavaliercoder** [comment]
What do the PostgreSQL logs say when you attempt to authenticate via Zabbix? It could be a HBA issue? I also recommend using a `.pgpass` file instead of storing credentials in your connection string.

**Comment by N1k3** [comment]
I am using .pgpass. I think the maim problem what libzbxpgsql dont see server and they says 
> Is the server running on host "127.0.0.1" and accepting
TCP/IP connections on port 5432?

**Comment by N1k3** [comment]
[sas@srv ~]$ sudo su - zabbix -c "zabbix_get -s 127.0.0.1 -k pg.version"
ZBX_NOTSUPPORTED: could not connect to server: Permission denied
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
