### ISSUE TITLE
connection problem database "postgres dbname="

### ISSUE THREAD

**Issue by ikzelf** [cavaliercoder/libzbxpgsql#111]
zabbix_agent 3.0.12
libzbxpgsql 1.1.0

>zabbix_get -s 127.0.0.1 -k "pg.connect[postgresql://zbxmonitoring@dbhostname/postgres]"
0

zabbix_agentd.log:
27320:20171019:202202.500 using configuration file: /etc/zabbix/zabbix_agentd.conf
 27320:20171019:202202.503 starting agent module libzbxpgsql 1.1.0
 27320:20171019:202202.503 using module configuration file: /etc/zabbix/libzbxpgsql.conf
 27320:20171019:202202.503 loaded modules: libzbxpgsql.so
 27320:20171019:202202.504 agent #0 started [main process]
 27322:20171019:202202.505 agent #1 started [collector]
 27323:20171019:202202.506 agent #2 started [listener #1]
 27324:20171019:202202.507 agent #3 started [listener #2]
 27325:20171019:202202.509 agent #4 started [listener #3]
 27326:20171019:202202.509 agent #5 started [active checks #1]
<snip>
 27325:20171019:210912.880 PostgreSQL: FATAL:  no pg_hba.conf entry for host "db.host.ip.addr", user "zbxmonitoring", database "postgres dbname=", SSL off

I have a little trouble getting postgres monitoring to work ...
If I fall back to keyword/value pairs like:
>zabbix_get -s 127.0.0.1 -k "pg.connect[user=zbxmonitoring host=dbhostname dbname=postgres]"
the log gets:
 27325:20171019:211558.885 PostgreSQL: FATAL:  no pg_hba.conf entry for host "db.host.ip.addr", user "zbxmonitoring", database "zbxmonitoring", SSL off

How can/should I fix this?

**Comment by ikzelf** [comment]
Oops, db.host.ip.address is ofcourse the agents.host.ip.address. Why does iT try to connect to the database with the dame name as the username, when I try to have iT connect to the postgres db?

**Comment by cavaliercoder** [comment]
Please see: http://cavaliercoder.com/libzbxpgsql/documentation/connecting-to-postgresql/

You'll need to use the key/val style of connection string, and omit the `dbname` component. The name of the database should be provided instead as the second zabbix parameter.

By default, PostgreSQL will always connect to a database with the same name as the username, unless explicitly requested otherwise. This is what the second parameter is for in this module.

**Comment by cavaliercoder** [comment]
Please see: http://cavaliercoder.com/libzbxpgsql/documentation/connecting-to-postgresql/

Please use the key/val style of connection string and specify `dbname` in the second item key parameter instead of the connection string.

**Comment by ikzelf** [comment]
Thanks.
