### ISSUE TITLE
Module libzbxpgsql is not loaded

### ISSUE THREAD

**Issue by lpossamai** [cavaliercoder/libzbxpgsql#121]
Hi,

I've got Zabbix Server 3.4 and PostgreSQL 10. When downloading the RPM package for my CentOS 6.9 and then restarting the zabbix agent on my PG DB Server, I get the following:

 ```
30569:20180613:074608.958 unsupported module "libzbxpgsql.so" version: 2
 30569:20180613:074608.958 loading modules failed, exiting...
```

How can I fix the problem? Cheers!

**Comment by cavaliercoder** [comment]
It looks like you downloaded the package for v2. Make sure to download the package for Zabbix 3.2+ here: http://cavaliercoder.com/libzbxpgsql/download/

**Comment by lpossamai** [comment]
Nope.. I have downloaded the correct one:

`wget http://cdn.cavaliercoder.com/libzbxpgsql/yum/zabbix32/rhel/6/x86_64/libzbxpgsql-1.1.0-1.el6.x86_64.rpm`

**Comment by cavaliercoder** [comment]
That's confusing. What happens if you compile the module yourself? http://cavaliercoder.com/libzbxpgsql/documentation/module-installation/#install-from-source

**Comment by lpossamai** [comment]
```
[root@uatdb ~]# wget http://cdn.cavaliercoder.com/libzbxpgsql/yum/zabbix32/rhel/6/x86_64/libzbxpgsql-1.1.0-1.el6.x86_64.rpm
--2018-06-13 09:02:31--  http://cdn.cavaliercoder.com/libzbxpgsql/yum/zabbix32/rhel/6/x86_64/libzbxpgsql-1.1.0-1.el6.x86_64.rpm
Resolving cdn.cavaliercoder.com... 52.85.40.128, 52.85.40.191, 52.85.40.156, ...
Connecting to cdn.cavaliercoder.com|52.85.40.128|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 24160 (24K) [binary/octet-stream]
Saving to: “libzbxpgsql-1.1.0-1.el6.x86_64.rpm”

100%[===============================================================>] 24,160      --.-K/s   in 0.02s   

2018-06-13 09:02:31 (1.29 MB/s) - “libzbxpgsql-1.1.0-1.el6.x86_64.rpm” saved [24160/24160]

[root@uatdb ~]# rpm -i libzbxpgsql-1.1.0-1.el6.x86_64.rpm
[root@uatdb ~]# 
[root@uatdb ~]# service zabbix-agent restart
Shutting down Zabbix agent:                                [  OK  ]
Starting Zabbix agent:                                           [  OK  ]

tail -n 50 /var/log/zabbix/zabbix_agentd.log
 32195:20180613:090258.609 unsupported module "libzbxpgsql.so" version: 2
 32195:20180613:090258.610 loading modules failed, exiting...
```

Manually compiling the module:
Same error as https://github.com/cavaliercoder/libzbxpgsql/issues/68: "configure: error: /etc/zabbix/module.h does not exist"

Why is that?

**Comment by cavaliercoder** [comment]
That error message is unrelated to #68 as best I can tell.

Did you tell the compiler where the Zabbix sources are with `./configure --with-zabbix=/usr/src/zabbix`?

**Comment by lpossamai** [comment]
Yup I know that.. but this error: `configure: error: /usr/lib64/zabbix/module.h does not exist` ... that module.h doesn't exist on my server.

Do I need to install an add-on for Zabbix or something?
I installed Zabbix from the Yum repository BTW.

**Comment by cavaliercoder** [comment]
That file is in the source tarball you download in step 2.

**Comment by lpossamai** [comment]
Can you please elaborate?

```
tar -xzf libzbxpgsql-*.tar.gz
cd libzbxpgsql-*/
./configure --with-zabbix=/usr/lib64/zabbix

configure: error: /usr/lib64/zabbix/module.h does not exist
```

At what moment am I (supposed) copying a `module.h` file?

**Comment by cavaliercoder** [comment]
Sure. Please accept my apologies. It's difficult to write the documentation with the right granularity. It does assume a fair bit of prior linux/postgresql/zabbix knowledge that might not fit everybody fairly.

Step 2. is to "download and extract" the Zabbix sources. Grab the tarball from https://www.zabbix.com/download_sources and then extract it anywhere on the machine you will compile from. Typically, `$ tar -xzf <tarball>.tar.gz`. I typically put these sources under `/usr/src` but it is entirely unimportant.

The configure step requires you to tell the module compiler where the sources are with `$ ./configure --with-zabbix=<the-extracted-sources-path>`.

You'll need the sources for libpq and libconfig too, but these are available simply by installing `postgresql-devel` and `libconfig-devel`. Unfortunately, Zabbix do not publish a 'sources' package so the above process is required.

On second thought, asking you to compile was an experiment to see if the issue was in code or my packaging. If it proves difficult (there are steps to making it work once compiled), I'll try find some time to do this for you.

**Comment by lpossamai** [comment]
When you asked me to compile it from the source file, you did not mention you were referring to Zabbix. Perhaps you should improve your communication skills.

**Comment by cavaliercoder** [comment]
I wasn't referring to Zabbix. I asked you to compile _this_ module. Compiling this module requires an extracted copy of the Zabbix sources, as per the documentation referenced above.

Judging by your hostile response I'm guessing you interpreted my offer as mockery or an affront to your abilities. This was not my intention. I'm literally offering to take time out of my day to setup an environment and try to replicate your issue.

If I re-read my comments with a harsh tone, I can see how you might be offended. Try read them again in a helpful tone, noting that I was replying from my phone on the train home from work. Assuming the best in people makes the Internet a better place.

**Comment by lpossamai** [comment]
FYI @cavaliercoder ,

this link works: http://cdn.cavaliercoder.com/libzbxpgsql/yum/zabbix30/rhel/6/x86_64/libzbxpgsql-1.1.0-1.el6.x86_64.rpm

this link does not work: http://cdn.cavaliercoder.com/libzbxpgsql/yum/zabbix32/rhel/6/x86_64/libzbxpgsql-1.1.0-1.el6.x86_64.rpm

Error: 

> 30569:20180613:074608.958 unsupported module "libzbxpgsql.so" version: 2
> 30569:20180613:074608.958 loading modules failed, exiting...

**Comment by Fizard** [comment]
> FYI @cavaliercoder ,
> 
> this link works: http://cdn.cavaliercoder.com/libzbxpgsql/yum/zabbix30/rhel/6/x86_64/libzbxpgsql-1.1.0-1.el6.x86_64.rpm
> 
> this link does not work: http://cdn.cavaliercoder.com/libzbxpgsql/yum/zabbix32/rhel/6/x86_64/libzbxpgsql-1.1.0-1.el6.x86_64.rpm
> 
> Error:
> 
> > 30569:20180613:074608.958 unsupported module "libzbxpgsql.so" version: 2
> > 30569:20180613:074608.958 loading modules failed, exiting...

That's true, just tried on a CentOS 6.8 and had to download from this link http://cdn.cavaliercoder.com/libzbxpgsql/yum/zabbix30/rhel/6/x86_64/libzbxpgsql-1.1.0-1.el6.x86_64.rpm instead the zabbix 3.2+.

**Comment by mohammadasim** [comment]
The instructions in this page helped me configure libzbxsystemd loadable module.  I couldn't understand from the readme file that I needed the zabbix sources to compile the module.  
Thanks,
