### ISSUE TITLE
Zabbix 3.4 seem not workin

### ISSUE THREAD

**Issue by metabsd** [cavaliercoder/libzbxpgsql#129]
It's supported ?

```
zabbix_agentd -t pg.modver
pg.modver                                     [m|ZBX_NOTSUPPORTED] [Unsupported item key.]
```

**Comment by i-ky** [comment]
You have to provide `-C path/to/zabbix_agentd.conf` option if you want keys from loadable modules to work with `-t`.

**Comment by metabsd** [comment]
I just want to confirm the installation is ok with 3.4

```
zabbix_agentd -c /etc/zabbix/zabbix_agentd.conf -t pg.modver
pg.modver                                     [m|ZBX_NOTSUPPORTED] [Unsupported item key.]
```

**Comment by metabsd** [comment]
The template 3.0 will be compatible ?

https://github.com/cavaliercoder/libzbxpgsql/tree/v1.1.0/templates

**Comment by cavaliercoder** [comment]
You should see a log line when the module loads. If not, Zabbix is not even trying to load the module. Please check through the installation and configuration docs.

**Comment by i-ky** [comment]
> The template 3.0 will be compatible ?

Even 1.8 would be. :) Zabbix does automatic XML conversion on the fly as you import it (similar to DB upgrade).

**Comment by metabsd** [comment]
I try to find the way to filter the discovery.

The error :
![image](https://user-images.githubusercontent.com/7953470/46541192-4f38d700-c889-11e8-9796-44b5b531bf1e.png)

The config:
![image](https://user-images.githubusercontent.com/7953470/46541225-637cd400-c889-11e8-9106-8b16a5dc0347.png)

My host macro:
![image](https://user-images.githubusercontent.com/7953470/46541274-932bdc00-c889-11e8-93da-c86e25823ef1.png)

**Comment by metabsd** [comment]
It's working now. Thx!
