### ISSUE TITLE
Zabbix agent 4.0.7 and 4.2.1 breaks support for libzbxpgsql.so

### ISSUE THREAD

**Issue by Trikke76** [cavaliercoder/libzbxpgsql#139]
https://support.zabbix.com/browse/ZBX-16028
 
14538:20190419:094458.679 Starting Zabbix Agent [staging]. Zabbix 4.0.7 (revision 92831).
14538:20190419:094458.679 **** Enabled features ****
14538:20190419:094458.679 IPv6 support: YES
14538:20190419:094458.679 TLS support: YES
14538:20190419:094458.679 **************************
14538:20190419:094458.679 using configuration file: /etc/zabbix/zabbix_agentd.conf
14538:20190419:094458.681 cannot load module "libzbxpgsql.so": /usr/lib64/zabbix/modules/libzbxpgsql.so: undefined symbol: __zbx_zbx_snprintf

it seems the module is broken since  zabbix 4.0.7 not sure they will revert changes they made. if not it would be nice if you could create a new package

**Comment by i-ky** [comment]
You can try `objcopy --redefine-sym __zbx_zbx_snprintf=zbx_snprintf libzbxpgsql.so`.

**Comment by Trikke76** [comment]
Thx @i-ky 
tried it but it doesn't seem to work.
Zabbix is also unwilling to fix it on there side so it would be great if a new module was made to support latest changes

https://support.zabbix.com/browse/ZBX-16028

**Comment by i-ky** [comment]
Seems I have found a dirty workaround:
1. Open `libzbxpgsql.so` in hex editor;
1. Find `__zbx_zbx_snprintf`;
1. Remove 6 bytes corresponding to `__zbx_` prefix;
1. Add 6 (for every character of `__zbx_`) zero bytes (`00`) **after** `zbx_snprintf`;
1. Save your work.

After that module can be loaded without "undefined symbol" error.

**Comment by Cobra1978** [comment]
Hi.

It's possible to have a packaged version with the workaround.

We have many postgres server, and modifyng the library on every f them will be a very long work

**Comment by OrangeDog** [comment]
@i-ky unfortunately `objcopy` doesn't work on dynamic symbols.

**Comment by i-ky** [comment]
@OrangeDog, it is a dynamic symbol, but not one provided by `libzbxpgsql.so`. Seems that `objcopy` does not work for undefined symbols.

**Comment by OrangeDog** [comment]
@Cobra1978 you can easily make your own package with the patched binary.
Use `rpmrebuild ` or `dpkg-deb` as appropriate. I recommend adding e.g. `+ZBX-16028` to the version.
