### ISSUE TITLE
Troubleshooting?

### ISSUE THREAD

**Issue by SubZr0** [cavaliercoder/libzbxpgsql#14]
Hi,

I configured everything correct ( i think ) i see the module being loaded. The test works, but my zabbix server gets no data, and i don't see anything in the logs... ( i don't see anything in the lagent logs on debug level either )

i am using zabbix 2.4.6 and the latest libzbxpgsql rpm on centos6

**Comment by cavaliercoder** [comment]
If you're using the included template, all items are configured as 'Active items' which means the agent won't be aware of the new items until it next refreshes its configuration from the Zabbix server (i.e. when the configured `RefreshActiveChecks` interval expires). There is also a ~2 min delay from when you make a template change in the web interface and when the Zabbix server synchronises configuration from the database.

Have you tried waiting until `RefreshActiveChecks` expires (typically one hour) or restarting the agent once or twice? The agent will reload config shortly after each start.

**Comment by SubZr0** [comment]
i have waited 24 hours now :)

i see them in my queue.. i reloaded the server ,and the agent.. 
so now the delay is only 2 minutes..

**Comment by cavaliercoder** [comment]
Something is definitely amiss. Can you please provide further clarification of your issue?
Are you seeing unsupported items in the Zabbix web console or simply no data on the graphs or Latest Data screens?

Can you please double check you have completed each step in the documentation? Please advise if it requires any refinement. http://cavaliercoder.com/libzbxpgsql/template/

Which queue do you see the items in?

Please also take a look in the debug logs when the agent performs a configuration sync with the server. You should see a JSON packet returned from the server with all of the configured items for that agent. Are the libzbxpgsql template items in this list?

Do the logs on the zabbix server (not agent) show any unsupported items or errors?

Can you query the libzbxpgsql items on your agent using `zabbix_get`?

My initial feeling is that you do have a configuration problem, but I'm keen to help and update the documentation to make it more efficacious and easier to follow.

**Comment by SubZr0** [comment]
> On 15 sep. 2015, at 18:30, Ryan Armstrong <notifications@github.com> wrote:
> 
> Something is definitely amiss. Can you please provide further clarification of your issue?
> Are you seeing unsupported items in the Zabbix web console or simply no data on the graphs or Latest Data screens?
> 
> most items are enabled, just no data. i enabled the discoveries.
> Can you please double check you have completed each step in the documentation? Please advise if it requires any refinement. http://cavaliercoder.com/libzbxpgsql/template/ <http://cavaliercoder.com/libzbxpgsql/template/>I did, i did all the steps.
> Which queue do you see the items in?
> 
> 

> Please also take a look in the debug logs when the agent performs a configuration sync with the server. You should see a JSON packet returned from the server with all of the configured items for that agent. Are the libzbxpgsql template items in this list?
> 
> none :(
> Do the logs on the zabbix server (not agent) show any unsupported items or errors?
> 
> 
> no 
[root@Zabbix ~]# grep unsupported  /var/log/zabbix/zabbix_server.log
[root@Zabbix ~]#

> no not at all.. Do i need the java gateway? 
> Can you query the libzbxpgsql items on your agent using zabbix_get?
> 
> 
[root@Zabbix ~]# zabbix_get -s x.x.x.x -p 10050 -I x.x.x.x -k pg.queries.longest[{$PG_CONN},{$PG_DB}]
ZBX_NOTSUPPORTED: Item is not supported.
[root@Zabbix ~]# zabbix_get -s x.x.x.x -p 10050 -I x.x.x.x -k 'pg.queries.longest[{$PG_CONN},{$PG_DB}]'
ZBX_NOTSUPPORTED: Item is not supported.
[root@Zabbix ~]# zabbix_get -s x.x.x.x -p 10050 -I x.x.x.x -k pg.buffers_alloc[{$PG_CONN},{$PG_DB}]
ZBX_NOTSUPPORTED: Item is not supported.

**Comment by cavaliercoder** [comment]
Did you replace the `{$PG_*}` macros when calling `zabbix_get`?
Try `zabbix_get -s x.x.x.x pg.modver`

**Comment by SubZr0** [comment]
> On 16 sep. 2015, at 04:08, Ryan Armstrong <notifications@github.com> wrote:
> 
> Did you replace the {$PG_*} macros when calling zabbix_get?
> 
Tried that too :)

[root@Zabbix ~]# zabbix_get -s x.x.x.x -p 10050 -I x.x.x.x -k pg.buffers_alloc[{host=localhost user=monitoring,postgres]
ZBX_NOTSUPPORTED: Invalid item key format.
[root@Zabbix ~]# zabbix_get -s x.x.x.x -p 10050 -I x.x.x.x -k pg.buffers_alloc[{host=localhost user=monitoring, postgres]
ZBX_NOTSUPPORTED: Invalid item key format.
[root@Zabbix ~]# zabbix_get -s x.x.x.x -p 10050 -I x.x.x.x -k pg.buffers_alloc[host=localhost user=monitoring, postgres]
ZBX_NOTSUPPORTED: Invalid item key format.
[root@Zabbix ~]# zabbix_get -s x.x.x.x -p 10050 -I x.x.x.x -k pg.buffers_alloc[host=localhost user=monitoring port=5432, postgres]
ZBX_NOTSUPPORTED: Invalid item key format.

> Try zabbix_get -s x.x.x.x pg.modver
> 
> 
[root@Zabbix ~]# zabbix_get -s 91.213.13.236 -k pg.modver
libzbxpgsql 0.2.0
[root@Zabbix ~]#
so that seems to do something.. 


this is pg_hba.conf :
# TYPE  DATABASE        USER            ADDRESS                 METHOD



pand pg_ident.conf
# MAPNAME       SYSTEM-USERNAME         PG-USERNAME
monitoring	root			monitoringlocal	all		monitoring				ident map=monitor

**Comment by cavaliercoder** [comment]
I'm going to close this issue as this isn't really the right forum for troubleshooting Zabbix configuration. There doesn't appear to be any bugs in libzbxpgsql contributing to your issues.

The `Invalid item key format` error is because you have left a stray `{` in the first key parameter and aren't escaping your ` ` spaces on the command line.

It also appears that your `pg_hba.conf` is empty?? This is not correct!

As your issues are quite generalised to Zabbix, maybe jump on the #zabbix freenode IRC channel and have a chat to the team.

All the best!

**Comment by SubZr0** [comment]
Just to let you know: i got it to work.. Lesson 101 if using active checks: make sure you configure your hostname correct on your agent config.

Thanks for your help.

**Comment by cavaliercoder** [comment]
Great news!
