### ISSUE TITLE
Database capacity on some DBs

### ISSUE THREAD

**Issue by shayani** [cavaliercoder/libzbxpgsql#144]
I'm getting the info from Database Capacity only from some DBs (all on same host), but not from all the DBs. Maybe it's a priviledge error. 
![Captura de Tela 2019-05-16 às 17 36 37](https://user-images.githubusercontent.com/1488409/57885363-2aceb100-7801-11e9-95fa-b5d9247a44c9.png)

**Comment by shayani** [comment]
I got it working! Thanks

**Comment by cavaliercoder** [comment]
Can you please share your solution for others?

**Comment by shayani** [comment]
I forgot to give the appropriate permission to the "monitoring" PostgreSQL user (http://cavaliercoder.com/libzbxpgsql/documentation/connecting-to-postgresql/).
