### ISSUE TITLE
Redirect or disable log

### ISSUE THREAD

**Issue by shayani** [cavaliercoder/libzbxpgsql#145]
How to change the log level for libzbxpgsql, or redirect them to another file? My zabbix_server.log is too chatty and I cannot read others important log warnings. 

Thanks

**Comment by shayani** [comment]
Really sorry. Wrong forum. I was looking to solve Apache logs on Zabbix.

**Comment by shayani** [comment]
I'm reopening this. Also libzbxpgsql log files generated on zabbix_agentd.log are too extensive. Is there a way to redirect this to another file?

**Comment by i-ky** [comment]
Sounds related to #139 and #141.

**Comment by shayani** [comment]
I read those threads but no solution is there :(

**Comment by i-ky** [comment]
Please provide some context. Which Zabbix version do you use? Did you compile module yourself or installed from packages?

**Comment by shayani** [comment]
I'm using Zabbix 4.2.3 from packages from repo.zabbix.com. I'm using Ubuntu 18.04.
libzbxpgsql I compiled myself from source codes.

Everything runs fine. Just the zabbix log file is huge. Follows example of text in log file:

    ...
    618:20190625:070319.551 In pg_get_result(pg.starttime)
    618:20190625:070319.551 In pg_scalar
    618:20190625:070319.551 In pg_connect()
    618:20190625:070319.551 Connecting to PostgreSQL with: dbname=postgres
    618:20190625:070319.554 End of pg_connect()
    618:20190625:070319.554 Executing query with 0 parameters: SELECT pg_postmaster_start_time();
    618:20190625:070319.555 End of pg_scalar
    618:20190625:070319.555 End of pg_get_result(pg.starttime)
    618:20190625:070319.555 End of PG_STARTTIME()
    618:20190625:070320.555 In PG_STAT_BGWRITER()
    618:20190625:070320.555 In pg_get_result(pg.stats_reset)
    618:20190625:070320.555 In pg_scalar
    618:20190625:070320.555 In pg_connect()
    618:20190625:070320.555 Connecting to PostgreSQL with: dbname=postgres
    618:20190625:070320.560 End of pg_connect()
    618:20190625:070320.560 Executing query with 0 parameters: SELECT stats_reset FROM pg_stat_bgwriter;
    618:20190625:070320.572 End of pg_scalar
    618:20190625:070320.572 End of pg_get_result(pg.stats_reset)
    618:20190625:070320.572 End of PG_STAT_BGWRITER()
    618:20190625:070320.572 In PG_UPTIME()
    618:20190625:070320.572 In pg_get_result(pg.uptime)
    618:20190625:070320.572 In pg_scalar
    618:20190625:070320.572 In pg_connect()
    618:20190625:070320.572 Connecting to PostgreSQL with: dbname=postgres
    618:20190625:070320.577 End of pg_connect()
    618:20190625:070320.577 Executing query with 0 parameters: SELECT EXTRACT(EPOCH FROM NOW()) - EXTRACT(EPOCH FROM pg_postmaster_start_time());
    618:20190625:070320.578 End of pg_scalar
    618:20190625:070320.578 End of pg_get_result(pg.uptime)
    618:20190625:070320.578 End of PG_UPTIME()
    ...

and much more

**Comment by i-ky** [comment]
> libzbxpgsql I compiled myself from source codes.

Which version of Zabbix did you use to compile the module? I think it may help if you take Zabbix 4.2.3 sources and recompile it.

**Comment by shayani** [comment]
> Which version of Zabbix did you use to compile the module? I think it may help if you take Zabbix 4.2.3 sources and recompile it.

I did that. I compiled the module using the source code of Zabbix 4.2.3.

**Comment by i-ky** [comment]
Hm, have you restarted Zabbix agents after that?

**Comment by shayani** [comment]
> Hm, have you restarted Zabbix agents after that?

Yes. Still no good

**Comment by i-ky** [comment]
If you have nothing to loose, you can try out #142.

**Comment by cavaliercoder** [comment]
The log messages you posted should only be visible in `DEBUG` level logging right? I agree these are too noisy as they follow the old Zabbix standard of logging stack calls which can simply be observed with a debugger. I will remove this in a future version.

**Comment by i-ky** [comment]
@cavaliercoder, as I understand, @shayani is seeing these messages *without* raising log level to `DEBUG`. I suppose it is the same problem as reported [here](https://support.zabbix.com/browse/ZBX-16028?focusedCommentId=337846&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-337846) and reportedly [fixed](https://support.zabbix.com/browse/ZBX-16028?focusedCommentId=337934&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-337934) by just recompiling the module.

**Comment by shayani** [comment]
The Zabbix loglevel is on WARN and even after recompiling the module, I'm still seeing the extensive DEBUG-like info.

**Comment by i-ky** [comment]
I can't believe this. Please double-check everything. When Zabbix agent starts it prints its version in the log. Module also prints its version and the version of Zabbix it was compiled for. You can also get the latter from the binary:
```bash
$ strings ~/libzbxpgsql.so | grep '^[[:digit:]].[[:digit:]].[[:digit:]]$'
```
Make sure Zabbix loads the correct binary of the module.

**Comment by shayani** [comment]
When I start zabbix_agentd, it shows the versions:

    12995:20190628:081826.185 Starting Zabbix Agent. Zabbix 4.2.3 (revision 3685611ba5).
    12995:20190628:081826.185 **** Enabled features ****
    12995:20190628:081826.185 IPv6 support:          YES
    12995:20190628:081826.185 TLS support:           YES
    12995:20190628:081826.185 **************************
    12995:20190628:081826.185 using configuration file: /etc/zabbix/zabbix_agentd.conf
    12995:20190628:081826.191 starting agent module libzbxpgsql 1.1.0
    12995:20190628:081826.191 using module configuration file: /etc/zabbix/libzbxpgsql.conf
    12995:20190628:081826.192 loaded modules: libzbxpgsql.so

 
When I run the strings commands: 

    $ /var/lib/zabbix/modules/libzbxpgsql.so | grep '^[[:digit:]].[[:digit:]].[[:digit:]]$'
    4.2.3

The file `/etc/zabbix/libzbxpgsql.conf` is empty.

**Comment by i-ky** [comment]
What will `pg.modver` return?

**Comment by shayani** [comment]
`libzbxpgsql 1.1.0, compiled for Zabbix 4.2.3`

**Comment by i-ky** [comment]
I might have an idea what's going on...

Can you try to recompile module with `CFLAGS='-DHAVE___VA_ARGS__=1'`? Alternatively, you can add
```c
#define HAVE___VA_ARGS__ 1
```
at the top of src/libzbxpgsql.h file.

**Comment by i-ky** [comment]
Could you please check this?
```bash
$ grep HAVE___VA_ARGS__ /path/to/zabbix_source_dir/include/config.h
```

**Comment by shayani** [comment]
$ grep HAVE___VA_ARGS__ /root/zabbix-4.2.3/include/config.h.in
    #undef HAVE___VA_ARGS__

**Comment by i-ky** [comment]
config.h, not config.h.in

**Comment by shayani** [comment]
ls: cannot access 'config.h': No such file or directory

**Comment by i-ky** [comment]
Wait, this file is required to compile the module...

**Comment by i-ky** [comment]
Oh, I see. This module uses Autotools too and has its own config.h which is probably included into Zabbix sources when they need it.

Try to run ./configure in Zabbix source directory, recompile the module and restart the agent. I think you will be fine after that.

**Comment by shayani** [comment]
I ran `./configure` in zabbix-4.2.3 directory.
After that, I stoped the agent, deleted the libzbxpgsql.so file that the agent uses and recompiled the module with

    ./configure --with-zabbix=/root/zabbix-4.2.3
    make
    make install

Finally, restarted the agent. The moduled loaded fine, but still looks lots of info on the log file.

**Comment by i-ky** [comment]
Hm... Can you check this again?
```bash
$ grep HAVE___VA_ARGS__ /root/zabbix-4.2.3/include/config.h
```

**Comment by shayani** [comment]
$ grep HAVE___VA_ARGS__ /root/zabbix-4.2.3/include/config.h                                                                                                                   
    #define HAVE___VA_ARGS__ 1

**Comment by i-ky** [comment]
OK, this is good. This is how it should be, I guess. But I can't understand why module recompilation did not pick up this change. Have you just removed .so file? Have you done `make clean`?

As a last resort, you can put
```c
#define HAVE___VA_ARGS__ 1
```
on top of src/libzbxpgsql.h file.

**Comment by shayani** [comment]
Oh, I did not execute `make clean`. 

I did it now and recompiled the module. 

Now it's working fine! Thanks!
