### ISSUE TITLE
dont close the connection

### ISSUE THREAD

**Issue by colttt** [cavaliercoder/libzbxpgsql#16]
Hello,

i'am not an expert, but it seems to be that libzbxpgsql dont close the connection correctly, it open a new connection again and again.. 
that ends up with a full connection (look at the screenshot), after that i become a "Zabbix Database is down" message
![pg_connects](https://cloud.githubusercontent.com/assets/10084871/9987009/3de4b002-6043-11e5-92b2-52b64828dcd1.png)

**Comment by cavaliercoder** [comment]
I identified a leak in libzbxpgsql v0.2.0 which was fixed in v0.2.1. Which version are you using?

**Comment by colttt** [comment]
i running v0.2.0.. i will try 0.2.1

**Comment by cavaliercoder** [comment]
Apologies for any impact this issue caused for you. Please let me know if this resolves the problem for you once you've had it running a while.

**Comment by cavaliercoder** [comment]
Are your backend connections still leaking?
