### ISSUE TITLE
ZBX_NOTSUPPORTED items in host after template was added

### ISSUE THREAD

**Issue by lpallard1** [cavaliercoder/libzbxpgsql#19]
Hello,  I'd rather say it first, I'm a total noob with Zabbix and PGSQL but I appreciate the development you've done for the PGSQL integration with Zabbix!

I have followed the instructions of your website, and while everything went fine on the remote server (where postgresql runs), I cannot make it work on the zabbox server.  I imported the template, checked the macros (they were fine), attached the template to the host and restarted the agent on the remote server.

Under Hosts > Items, I see about 15 entries pertaining to your template, they all have status "not supported" (ZBX_NOTSUPPORTED).  

I wonder why?  On the remote server, the zabbix agent log has this in it:
 29292:20151010:163607.248 Zabbix Agent stopped. Zabbix 2.2.2 (revision 42525).
   696:20151010:163626.720 Starting Zabbix Agent [musicbrainz-mirror.tuxdomain]. Zabbix 2.2.2 (revision 42525).
   696:20151010:163626.720 using configuration file: /etc/zabbix/zabbix_agentd.conf
   697:20151010:163626.722 agent #0 started [collector]
   698:20151010:163626.722 agent #1 started [listener #1]
   701:20151010:163626.722 agent #4 started [active checks #1]
   699:20151010:163626.723 agent #2 started [listener #2]
   700:20151010:163626.723 agent #3 started [listener #3]
   701:20151010:163626.734 active check "pg.index.discovery[host=127.0.0.1 port=5432,postgres]" is not supported
   701:20151010:163626.734 active check "pg.table.discovery[host=127.0.0.1 port=5432,postgres]" is not supported
   701:20151010:164026.780 active check "pg.backends.count[host=127.0.0.1 port=5432,postgres]" is not supported
   701:20151010:164026.781 active check "pg.buffers_alloc[host=127.0.0.1 port=5432,postgres]" is not supported
   701:20151010:164026.781 active check "pg.buffers_backend[host=127.0.0.1 port=5432,postgres]" is not supported
   701:20151010:164026.782 active check "pg.buffers_backend_fsync[host=127.0.0.1 port=5432,postgres]" is not supported
   701:20151010:164026.782 active check "pg.buffers_checkpoint[host=127.0.0.1 port=5432,postgres]" is not supported
   701:20151010:164026.782 active check "pg.buffers_clean[host=127.0.0.1 port=5432,postgres]" is not supported
   701:20151010:164026.782 active check "pg.checkpoints_req[host=127.0.0.1 port=5432,postgres]" is not supported
   701:20151010:164026.782 active check "pg.checkpoints_timed[host=127.0.0.1 port=5432,postgres]" is not supported
   701:20151010:164026.782 active check "pg.checkpoint_sync_time[host=127.0.0.1 port=5432,postgres]" is not supported
   701:20151010:164026.782 active check "pg.checkpoint_write_time[host=127.0.0.1 port=5432,postgres]" is not supported
   701:20151010:164026.782 active check "pg.connect[host=127.0.0.1 port=5432,postgres]" is not supported
   701:20151010:164026.782 active check "pg.db.discovery[host=127.0.0.1 port=5432,postgres]" is not supported
   701:20151010:164026.782 active check "pg.maxwritten_clean[host=127.0.0.1 port=5432,postgres]" is not supported
   701:20151010:164026.782 active check "pg.queries.longest[host=127.0.0.1 port=5432,postgres]" is not supported
   701:20151010:164026.782 active check "pg.setting.discovery[host=127.0.0.1 port=5432,postgres]" is not supported
   701:20151010:164026.782 active check "pg.stats_reset[host=127.0.0.1 port=5432,postgres]" is not supported
   701:20151010:164026.783 active check "pg.tablespace.discovery[host=127.0.0.1 port=5432,postgres]" is not supported
   701:20151010:164026.783 active check "pg.version[host=127.0.0.1 port=5432,postgres]" is not supported

If you can shed some light on this, I'd appreciate a lot!
Thank you and best regards

**Comment by cavaliercoder** [comment]
It looks like the libzbxpgsql module is not being loaded by your remote agent. When installed correctly, you should see a line in the agent log file when it starts similar to:

    Loaded modules: libzbxpgsql.so
    Starting agent module libzbxpgsql vX.X

Please check that `lizbxbpgsql.so` is installed into the correct directory configured in the `LoadModulePath` directive. Also check that a `LoadModule=libzbxpgsql.so` directive is added to the agent config file or in its own file in the agent's `conf.d` directory.

**Comment by cavaliercoder** [comment]
There are two parts to the installation; the agent module install (on the PostgreSQL server) and the template install. It looks like the template is working for you, but please double check through the instructions here: http://cavaliercoder.com/libzbxpgsql/installation/

If anything is unclear or not working as expected, please let me know and I'll adjust the documentation.
