### ISSUE TITLE
permission denied for relation pg_authid

### ISSUE THREAD

**Issue by colttt** [cavaliercoder/libzbxpgsql#2]
Hello,

when i look to my database-log and i see a lot of errors like:

`2015-04-14 06:34:51 CEST STATEMENT:  SELECT t.oid, t.spcname, a.rolname from pg_tablespace t JOIN pg_authid a ON a.oid = t.spcowner
2015-04-14 06:40:51 CEST ERROR:  permission denied for relation pg_authid

why you need access to pg_authid?

**Comment by cavaliercoder** [comment]
The next version will use `pg_roles` instead of the legacy `pg_authid` but this is used to get the name of the owner of a relation. Most relations store the ID of the owner, but not the owner's friendly name.

I'll close this in lieu of issue #4 which will fix this issue.
