### ISSUE TITLE
FATAL: role "root" does not exist

### ISSUE THREAD

**Issue by mkash28** [cavaliercoder/libzbxpgsql#21]
I have following:

zabbix-agent 2.4.6-1
zabbix-server 2.4.6-1
database server pgsql 9.3 (zabbix agent)
libzbxpgsql  0.2.1-1
postgresql-libs-8.4.20-3

getting following error after installing libzbxpgsql on a database server.

pg.db.stats_reset[,,postgres,,,]              [m|ZBX_NOTSUPPORTED] [Item is not supported.]
zabbix_agentd [4233]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  role "root" does not exist

pg.table.seq_scan                             [m|ZBX_NOTSUPPORTED] [Item is not supported.]
zabbix_agentd [4233]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  role "root" does not exist

pg.table.seq_tup_read                         [m|ZBX_NOTSUPPORTED] [Item is not supported.]
zabbix_agentd [4233]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  role "root" does not exist

pg.table.idx_scan                             [m|ZBX_NOTSUPPORTED] [Item is not supported.]
zabbix_agentd [4233]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  role "root" does not exist

pg.table.idx_tup_fetch                        [m|ZBX_NOTSUPPORTED] [Item is not supported.]
zabbix_agentd [4233]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  role "root" does not exist

pg.table.n_tup_ins                            [m|ZBX_NOTSUPPORTED] [Item is not supported.]
zabbix_agentd [4233]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  role "root" does not exist

pg.table.n_tup_upd                            [m|ZBX_NOTSUPPORTED] [Item is not supported.]
zabbix_agentd [4233]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  role "root" does not exist

pg.table.n_tup_del                            [m|ZBX_NOTSUPPORTED] [Item is not supported.]
zabbix_agentd [4233]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  role "root" does not exist

pg.table.n_tup_hot_upd                        [m|ZBX_NOTSUPPORTED] [Item is not supported.]
zabbix_agentd [4233]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  role "root" does not exist

pg.table.n_live_tup                           [m|ZBX_NOTSUPPORTED] [Item is not supported.]
zabbix_agentd [4233]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  role "root" does not exist

pg.table.n_dead_tup                           [m|ZBX_NOTSUPPORTED] [Item is not supported.]
zabbix_agentd [4233]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  role "root" does not exist

pg.table.last_vacuum[,,pg_database]           [m|ZBX_NOTSUPPORTED] [Item is not supported.]
zabbix_agentd [4233]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  role "root" does not exist

pg.table.last_autovacuum[,,pg_database]       [m|ZBX_NOTSUPPORTED] [Item is not supported.]
zabbix_agentd [4233]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  role "root" does not exist

pg.table.last_analyze[,,pg_database]          [m|ZBX_NOTSUPPORTED] [Item is not supported.]
zabbix_agentd [4233]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  role "root" does not exist

pg.table.last_autoanalyze[,,pg_database]      [m|ZBX_NOTSUPPORTED] [Item is not supported.]
zabbix_agentd [4233]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  role "root" does not exist

pg.table.vacuum_count                         [m|ZBX_NOTSUPPORTED] [Item is not supported.]
zabbix_agentd [4233]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  role "root" does not exist

pg.table.autovacuum_count                     [m|ZBX_NOTSUPPORTED] [Item is not supported.]
zabbix_agentd [4233]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  role "root" does not exist

pg.table.analyze_count                        [m|ZBX_NOTSUPPORTED] [Item is not supported.]
zabbix_agentd [4233]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  role "root" does not exist

pg.table.autoanalyze_count                    [m|ZBX_NOTSUPPORTED] [Item is not supported.]
zabbix_agentd [4233]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  role "root" does not exist

pg.table.heap_blks_read                       [m|ZBX_NOTSUPPORTED] [Item is not supported.]
zabbix_agentd [4233]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  role "root" does not exist

pg.table.heap_blks_hit                        [m|ZBX_NOTSUPPORTED] [Item is not supported.]
zabbix_agentd [4233]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  role "root" does not exist

pg.table.idx_blks_read                        [m|ZBX_NOTSUPPORTED] [Item is not supported.]
zabbix_agentd [4233]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  role "root" does not exist

pg.table.idx_blks_hit                         [m|ZBX_NOTSUPPORTED] [Item is not supported.]
zabbix_agentd [4233]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  role "root" does not exist

pg.table.toast_blks_read                      [m|ZBX_NOTSUPPORTED] [Item is not supported.]
zabbix_agentd [4233]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  role "root" does not exist

pg.table.toast_blks_hit                       [m|ZBX_NOTSUPPORTED] [Item is not supported.]
zabbix_agentd [4233]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  role "root" does not exist

pg.table.tidx_blks_read                       [m|ZBX_NOTSUPPORTED] [Item is not supported.]
zabbix_agentd [4233]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  role "root" does not exist

pg.table.tidx_blks_hit                        [m|ZBX_NOTSUPPORTED] [Item is not supported.]
zabbix_agentd [4233]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  role "root" does not exist

pg.index.idx_scan                             [m|ZBX_NOTSUPPORTED] [Item is not supported.]
zabbix_agentd [4233]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  role "root" does not exist

pg.index.idx_tup_read                         [m|ZBX_NOTSUPPORTED] [Item is not supported.]
zabbix_agentd [4233]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  role "root" does not exist

pg.index.idx_tup_fetch                        [m|ZBX_NOTSUPPORTED] [Item is not supported.]
zabbix_agentd [4233]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  role "root" does not exist

pg.index.idx_blks_read                        [m|ZBX_NOTSUPPORTED] [Item is not supported.]
zabbix_agentd [4233]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  role "root" does not exist

pg.index.idx_blks_hit                         [m|ZBX_NOTSUPPORTED] [Item is not supported.]

**Comment by cavaliercoder** [comment]
This indicates that the Zabbix agent is running as 'root' and using peer or ident authentication to connect to PostgreSQL as root.

Please configure a monitoring role in PostgreSQL and your Zabbix template to authenticate correctly as per the documentation: http://cavaliercoder.com/libzbxpgsql/agent-keys/#connecting-to-postgresql

**Comment by mkash28** [comment]
Thanks for very helpful information!
Not sure why it shows that 'zabbix-agent' is running as 'root' since all zabbix process are running under zabbix (standard) user account.

 └─zabbix_agentd,5323,zabbix -c /etc/zabbix/zabbix_agentd.conf
      ├─zabbix_agentd,5325          
      ├─zabbix_agentd,5326
      ├─zabbix_agentd,5327
      └─zabbix_agentd,5328
zabbix    5323     1  0 Oct19 ?        00:00:00 zabbix_agentd -c /etc/zabbix/zabbix_agentd.conf
zabbix    5325  5323  0 Oct19 ?        00:00:32 zabbix_agentd: collector [idle 1 sec]          
zabbix    5326  5323  0 Oct19 ?        00:00:17 zabbix_agentd: listener #1 [waiting for connection]
zabbix    5327  5323  0 Oct19 ?        00:00:17 zabbix_agentd: listener #2 [waiting for connection]
zabbix    5328  5323  0 Oct19 ?        00:00:17 zabbix_agentd: listener #3 [waiting for connection]

**Comment by mkash28** [comment]
wondering whether i need to map 'monitoring' with 'zabbix' or with 'root'?
thanks for your help, truly appreciate it.

**Comment by cavaliercoder** [comment]
If you intend to use `peer` or `ident` authentication, and your monitoring PostgreSQL role uses a different name to the user account the zabbix agent runs as, you must map your postgresql role to the agent service account name in `pg_ident.conf`.

So in your case, the agent runs as `zabbix` and I assume the PostgreSQL role is `monitoring` so `pg_ident.conf` should include this:
```
# MAPNAME       SYSTEM-USERNAME         PG-USERNAME
monitoring      zabbix                  monitoring
```

**Comment by mkash28** [comment]
thanks, will give it a try soon.
