### ISSUE TITLE
Alternate method of calculating table size

### ISSUE THREAD

**Issue by ZippySLC** [cavaliercoder/libzbxpgsql#22]
Hi -

So first of, my apologizes if this isn't the proper venue for raising this kind of request since it's not really a bug.

I've been asked to monitor table size in Postgress using pg_table_size rather than the method used natively by this plugin. i.e.: (SELECT (CAST(relpages AS bigint) * 8192)FROM pg_class WHERE relkind='r' AND relname = '%s’

I can easily do a custom SQL check and do something like SELECT pg_table_size('schema.table'); and get the information that I need. However I don't want to have to create a bunch of custom SQL queries by hand. There's multiple schemas involved here as well.

Is there a relatively easy way to accomplish this with libzbxpgsql? 

Thanks!

**Comment by cavaliercoder** [comment]
This is the perfect place for such questions :)

I deliberately did not use `pg_table_size()` as it's not compatible with PG 8.4 though I agree it may be a better way forward given that it is a native C function in later functions.

The only way to use this function with libzbxpgsql at present would be via the [pg.query.integer](http://cavaliercoder.com/libzbxpgsql/agent-keys/queries/#pg-query-integer) key using hand written queries.

To avoid rewriting the item for each table, you could create a discovery rule using the `pg.table.discovery` key and then an item prototype e.g. `pg.query.integer[<connection_details>,SELECT pg_table_size('{#SCHEMA}.{#TABLE}')]`.

In all of my testing, both `pg_table_size` and my query return the same figures. I'd be interested in your findings.

**Comment by ZippySLC** [comment]
Ok, so this is sort-of working. Here's my situation: I only have a few specific tables I care about. When I set up a discovery filter I use something like this:

{#DATABASE} - whatever
{#SCHEMA} - ^schema1$|^schema2$
{#TABLE} - ^table_without_schema_prefix$|table2_without_schema_prefix

This is the item prototype: pg.query.integer[{$PG_CONN},{$PG_DB},"SELECT pg_table_size('{#SCHEMA}.{#TABLE}')",]

So when it runs discovery it seems to find all of the tables in {#SCHEMA} but then doesn't filter them further by showing just what I want in {#TABLE} But I end up wth something like 600 items which is a bit unwieldily and I'd like to be able to cut it down to just the ones we care about.

(I don't know if it's possible to do that or not. I'm still kind of new to Zabbix.)

As for why we need to use pg_table_size as opposed to the other method -- apparently we do a bad job of vacuuming our tables.

**Comment by cavaliercoder** [comment]
Hurm... I don;t see anything wrong with your configuration there. The Regexp filters, if applied to your discovery rule, should return only the desired tables.

Maybe trying adding parentheses? I've experience wierdness with the `|` pipes in the past.

E.g. `^(schema1)|(schema2)$`

**Comment by ZippySLC** [comment]
It seems that the parentheses solved it. However now I’ve run into another issue! 

The regex that I ended up with for my tables is too big for the form on the filter page in Zabbix. I decided to try making a global macro but that seems to not work now. Do you see a reason why it wouldn’t work with libzbxpgsql?

And, by the way, thank you so much for all of your help so far!

**Comment by cavaliercoder** [comment]
You're welcome. How are you telling the discovery item to use the global regex? From memory you must use the `@` symbol to name a global regex.

**Comment by ZippySLC** [comment]
Yes. So if I’ve named the regex “Foo” I’d use @Foo.
