### ISSUE TITLE
Missing "=" after "monitoring" in connection info string

### ISSUE THREAD

**Issue by TheWorms** [cavaliercoder/libzbxpgsql#23]
19233:20151115:015630.149 Zabbix Agent stopped. Zabbix 2.4.6 (revision 54796).
 20276:20151115:015630.176 Starting Zabbix Agent [BlueMind]. Zabbix 2.4.6 (revision 54796).
 20276:20151115:015630.176 using configuration file: /etc/zabbix/zabbix_agentd.conf
 20276:20151115:015630.177 Starting agent module libzbxpgsql 0.2.1
 20276:20151115:015630.178 agent #0 started [main process]
 20277:20151115:015630.178 agent #1 started [collector]
 20278:20151115:015630.178 agent #2 started [listener #1]
 20279:20151115:015630.178 agent #3 started [listener #2]
 20280:20151115:015630.178 agent #4 started [listener #3]
 20281:20151115:015630.179 agent #5 started [active checks #1]
 20282:20151115:015630.179 agent #6 started [active checks #2]
 20281:20151115:015630.182 Failed to connect to PostgreSQL in pg_connect():
missing "=" after "monitoring" in connection info string

 20282:20151115:015631.023 Failed to connect to PostgreSQL in pg_connect():
missing "=" after "monitoring" in connection info string

**Comment by cavaliercoder** [comment]
Please show your connection string (with private data obfuscated). It looks like a syntax error.

**Comment by TheWorms** [comment]
sorry for my english ;)

i create this file in home zabbix config /etc/zabbix/.pgpass

# hostname:port:database:username:password
localhost:5432:bj:Admin:Password123

**Comment by cavaliercoder** [comment]
That file holds your password information, not connection information. Connection information is the first parameter that you pass in each of your Zabbix items that use libzbxpgsql. By default this is set in the `{$PG_CONN}` user macro.

What connection string are you using there? It appears to have a syntax error.

Also, as a side note, your `.pgpass` file should be stored in the Zabbix user account home directory (typically `/home/zabbix` or `/var/lib/zabbix`). Are you sure `/etc/zabbix` is correct? Double check the location listed for the Zabbix user in `/etc/passwd`/.

**Comment by TheWorms** [comment]
I'm use template.xml and macro with {$PG_CONN}

```/etc/zabbix``` is correct for zabbix-agent 2.2.7

I'm same error : https://www.zabbix.com/forum/showthread.php?p=174530#post174530

**Comment by cavaliercoder** [comment]
I'm closing this issue assuming it was a syntax error in the connection string.
If you are now seeing `FATAL: role "root" does not exist` instead, please see #27 or my response on the Zabbix forum link above.
