### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by tridlk** [cavaliercoder/libzbxpgsql#25]
http://cavaliercoder.com/libzbxpgsql/agent-keys/
Local monitoring agent

Where it has:-
pg.connect[host=localhost user=monitoring,postgres]

localhost is wrong, it should the dir of your pid file, ie /tmp/
So:-
pg.connect[host=/tmp/ user=monitoring,postgres]

**Comment by cavaliercoder** [comment]
Thanks for raising this. I've removed the `host` declaration all together so it will use the default socket directory.
