### ISSUE TITLE
Bad multiplier for pg.db.blk_read_time and pg.db.blk_write_time

### ISSUE THREAD

**Issue by fabriziomello** [cavaliercoder/libzbxpgsql#26]
Shouldn't the pg.db.blk_read_time and pg.db.blk_write_time multiplies by 0.001 instead of 1000?

I complain about that because the system stats pg_stat_database.{blk_write_time|blk_read_time} store values in miliseconds, so if you want to calculate it in seconds you should divide by 1000 or multiply by 0.001.

Am I missing something?

**Comment by cavaliercoder** [comment]
Yes I believe you are right. I'll update this in the next version. Still doing a bit of research into what exactly this key means.

**Comment by cavaliercoder** [comment]
Fixed in 8f37aad
