### ISSUE TITLE
FATAL:  database "root" does not exist

### ISSUE THREAD

**Issue by aaryabhatt** [cavaliercoder/libzbxpgsql#29]
Hello,

I am trying this to monitor postgresql bdr database node or postgresql database. My OS is debian jessie 64 bit and I tried to install is with deb package but it did not work, it installed but it did not return anything with  zabbix_agentd -p | grep '^pg\.' So I installed it with source package and include modules and it start showing module loaded "loaded modules: libzbxpgsql.so" in logs file. I created a user in root with connect to access for all database in postgresql.  

host    all             root      127.0.0.1/32                trust
host    all             root      10.11.12.7/32              trust

10.11.12 is mine zabbix server ip address. 
but when I run zabbix_agentd -p | grep '^pg\.' it give a lot below errors for different parameters.

zabbix_agentd [4594]: Starting agent module libzbxpgsql 0.2.1
pg.modver                                     [s|libzbxpgsql 0.2.1]
zabbix_agentd [4594]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  database "root" does not exist

pg.connect                                    [u|0]
zabbix_agentd [4594]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  database "root" does not exist
pg.version                                    [m|ZBX_NOTSUPPORTED]
zabbix_agentd [4594]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  database "root" does not exist

pg.starttime                                  [m|ZBX_NOTSUPPORTED]
zabbix_agentd [4594]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  database "root" does not exist

pg.uptime                                     [m|ZBX_NOTSUPPORTED]
zabbix_agentd [4594]: Error: Failed to connect to PostgreSQL in pg_connect():
FATAL:  database "root" does not exist

####################################3
template macros settings are given below.
{$PG_CONN}	⇒ host=127.0.0.1 port=5432
{$PG_DB} ⇒	postgres

postgresql errors are 
root@root FATAL:  database "root" does not exist
########################################
Zabbix server package version
root@zabbix:~# dpkg -l | grep zabbix
ii  zabbix-agent                   1:2.4.7-1+jessie          amd64        network monitoring solution - agent
ii  zabbix-frontend-php            1:2.4.7-1+jessie          all          network monitoring solution - PHP front-end
ii  zabbix-release                 2.4-1+jessie              all          Zabbix official repository configuration
ii  zabbix-server-mysql            1:2.4.7-1+jessie          amd64        network monitoring solution - server (using MySQL)
#########################################
zabbix client version
root@pg1:~# dpkg -l | grep zabbix
ii  zabbix-agent                   1:2.2.7+dfsg-2            amd64        network monitoring solution - agent

output of zabbix_get command
root@zabbix:~# zabbix_get -s pg1 -p 10050 -k pg.connect
0
root@zabbix:~# zabbix_get -s pg1 -p 10050 -k pg.index.idx_scan
ZBX_NOTSUPPORTED

May be I am missing something.

Is there any zabbix commands to check connectivity with postgresql on client side. If I use psql I am able to connect to pg server.
root@pg1:~# psql -U root postgres 
psql (9.4.5)
Type "help" for help.

I tried zabbix_get with below commands.
root@zabbix:~# zabbix_get -s pg1 -p 10050 -k pg.connect
0
root@zabbix:~# zabbix_get -s pg1 -p 10050 -k pg.index.idx_scan
ZBX_NOTSUPPORTED

--
Thanks 
Amit Bondwal

**Comment by cavaliercoder** [comment]
If you don't specify a database name in your connection string, PostgreSQL assumes the database name is the same as the user name. When you connect as root from your Zabbix connection string, it will also look for the root database... which does not exist.

When you connect with `psql -U root postgres` is works because you have told it to connect to the `postgres` database; not root.

Try `sudo -u postgres zabbix_agentd -p | grep '^pg.'` which will connect as the `postgres` user to the `postgres` database.

I'll update the documentation to note this.

**Comment by aaryabhatt** [comment]
Thanks for your reply, by running this command, I got a long list of data parameters like below. But I am not getting any data on zabbix server. I tried to change my connection string 
host=127.0.0.1 port=5432 dbname=postgres  but still not getting any data on zabbix server. 

zabbix_agentd [6530]: Starting agent module libzbxpgsql 0.2.1
pg.modver                                     [s|libzbxpgsql 0.2.1]
pg.connect                                    [u|1]
pg.version                                    [s|PostgreSQL 9.4.5 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit]
pg.starttime                                  [s|2016-01-05 07:44:48.679404+00]
pg.uptime                                     [u|7471]
pg.setting[,,data_directory]                  [s|/var/lib/postgresql/9.4/main]
pg.setting.discovery                          [s|{
pg.query.string[,,SELECT 'Lorem ipsum dolor';] [s|Lorem ipsum dolor]
pg.query.integer[,,SELECT pg_backend_pid();]  [u|6554]
pg.query.double[,,SELECT CAST(1234 AS double precision);] [d|1234.000000]
pg.query.discovery[,,SELECT * FROM pg_database;] [s|{
pg.backends.count                             [u|7]
pg.queries.longest                            [d|-0.001740]
pg.checkpoints_timed                          [u|3183]
pg.checkpoints_req                            [u|7]
pg.checkpoint_write_time                      [d|151078.000000]
pg.checkpoint_sync_time                       [d|2144.000000]
pg.buffers_checkpoint                         [u|1548]
pg.buffers_clean                              [u|0]
pg.maxwritten_clean                           [u|0]
pg.buffers_backend                            [u|984]
pg.buffers_backend_fsync                      [u|0]
pg.buffers_alloc                              [u|14238]
pg.stats_reset                                [s|2015-12-25 07:20:27.885293+00]

**Comment by cavaliercoder** [comment]
The Zabbix agent has the same issue; it is running and identifying as `root`. You need to configure a monitoring role (preferably not `root`) and use `pg_ident.conf` to map the Zabbix agent uid (`root`) to your PostgreSQL monitoring role.

Please see http://cavaliercoder.com/libzbxpgsql/agent-keys/#connecting-to-postgresql

**Comment by aaryabhatt** [comment]
I added the monitoring user , still not getting data on zabbix server. 
enty in pg_hba.conf file is 
local   all             monitoring                              ident map=monitoring
entry in pg_ident.conf file is 
monitoring      zabbix                  monitoring

my zabbix user home directory is /var/run/zabbix
.pass file entry changed it permission 600 and ownership to zabbix.
root@pg1:/var/run/zabbix# cat .pass 
*:*:*:monitoring:monitoring

able to login through psql with monitoring 
where to change below part
#####################
Configure Zabbix to use the monitoring role by specifying the user keyword in the first parameter of your item keys. E.g.

pg.connect[user=monitoring,postgres]
#############################

**Comment by cavaliercoder** [comment]
The connection string is set in the template using the `${PG_CONN}` macro. Try setting the user account there.

**Comment by sheh1000** [comment]
Run zabbix_agentd  command as a zabbix user:

sudo -u zabbix zabbix_agentd -p | grep '^pg\.'

**Comment by michaelwemoto** [comment]
I have this same problem, I've followed all of you instructions and set pg_ident.conf and an entry in pg_hba. I've tried all variations of macros without luck. 

Should this extension be fully compatible with Zabbix 3.0?

**Comment by cavaliercoder** [comment]
Regarding Zabbix v3 compatibility, please see #34.

**Comment by buzzing-bee** [comment]
> I added the monitoring user , still not getting data on zabbix server.
> enty in pg_hba.conf file is
> local all monitoring ident map=monitoring
> entry in pg_ident.conf file is
> monitoring zabbix monitoring
> 
> my zabbix user home directory is /var/run/zabbix
> .pass file entry changed it permission 600 and ownership to zabbix.
> root@pg1:/var/run/zabbix# cat .pass
> _:_:*:monitoring:monitoring
> 
> able to login through psql with monitoring
> where to change below part
> #####################
> Configure Zabbix to use the monitoring role by specifying the user keyword in the first parameter of your item keys. E.g.
> 
> pg.connect[user=monitoring,postgres]
> #############################

I have tried to follow on above step, but I can't seem to get it to work.

when I tried this command `sudo -u postgres zabbix_agentd -p | grep '^pg.'`, I got the result, but when It ried using zabbix `sudo -u zabbix zabbix_agentd -p | grep '^pg.'`, I got error as below:
####################################
zabbix_agentd [23727]: starting agent module libzbxpgsql 1.1.0
zabbix_agentd [23727]: using module configuration file: /etc/zabbix/libzbxpgsql.conf
zabbix_agentd [23727]: Warning: Executing command 'echo test'
pg.modver                                     [s|libzbxpgsql 1.1.0, compiled for Zabbix 3.2.3]
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.connect                                    [u|0]
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.version                                    [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.starttime                                  [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.uptime                                     [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.prepared_xacts_count                       [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.prepared_xacts_ratio                       [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.prepared_xacts_age                         [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.setting[,,data_directory]                  [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

zabbix_agentd [23727]: No query found for SELECT 'Lorem ipsum dolor';
pg.setting.discovery                          [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

zabbix_agentd [23727]: No query found for SELECT pg_backend_pid();
pg.query.string[,,SELECT 'Lorem ipsum dolor';] [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

zabbix_agentd [23727]: No query found for SELECT CAST(1234 AS double precision);
pg.query.integer[,,SELECT pg_backend_pid();]  [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

zabbix_agentd [23727]: No query found for SELECT * FROM pg_database;
pg.query.double[,,SELECT CAST(1234 AS double precision);] [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.query.discovery[,,SELECT * FROM pg_database;] [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.backends.count                             [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.backends.free                              [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.backends.ratio                             [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.queries.longest                            [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.checkpoints_timed                          [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.checkpoints_req                            [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.checkpoint_write_time                      [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.checkpoint_sync_time                       [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.checkpoint_avg_interval                    [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.checkpoint_time_ratio                      [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.buffers_checkpoint                         [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.buffers_clean                              [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.maxwritten_clean                           [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.buffers_backend                            [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.buffers_backend_fsync                      [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.buffers_alloc                              [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.stats_reset                                [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.stats_reset_interval                       [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.db.discovery                               [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.namespace.discovery                        [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.schema.discovery                           [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.tablespace.discovery                       [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.discovery                            [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.children.discovery[,,pg_proc]        [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.index.discovery                            [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.db.size                                    [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.size                                 [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.rows                                 [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.children[,,pg_database]              [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.children.size[,,pg_database]         [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.children.rows[,,pg_database]         [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.index.size                                 [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.index.rows                                 [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.tablespace.size[,,pg_default]              [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.namespace.size[,,pg_catalog]               [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.schema.size[,,pg_catalog]                  [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.db.numbackends                             [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.db.xact_commit                             [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.db.xact_rollback                           [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.db.blks_read                               [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.db.blks_hit                                [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.db.blks_ratio                              [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.db.tup_returned                            [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.db.tup_fetched                             [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.db.tup_inserted                            [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.db.tup_updated                             [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.db.tup_deleted                             [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.db.conflicts                               [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.db.temp_files                              [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.db.temp_bytes                              [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.db.deadlocks                               [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.db.blk_read_time                           [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.db.blk_write_time                          [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.db.stats_reset[,,postgres,,,]              [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.db.xid_age                                 [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.seq_scan                             [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.seq_tup_read                         [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.idx_scan                             [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.idx_scan_ratio                       [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.idx_tup_fetch                        [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.n_tup_ins                            [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.n_tup_upd                            [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.n_tup_del                            [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.n_tup_hot_upd                        [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.n_live_tup                           [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.n_dead_tup                           [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.n_mod_since_analyze                  [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.last_vacuum[,,pg_database]           [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.last_autovacuum[,,pg_database]       [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.last_analyze[,,pg_database]          [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.last_autoanalyze[,,pg_database]      [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.vacuum_count                         [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.autovacuum_count                     [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.analyze_count                        [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.autoanalyze_count                    [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.heap_blks_read                       [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.heap_blks_hit                        [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.heap_blks_ratio                      [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.idx_blks_read                        [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.idx_blks_hit                         [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.idx_blks_ratio                       [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.toast_blks_read                      [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.toast_blks_hit                       [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.toast_blks_ratio                     [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.tidx_blks_read                       [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.tidx_blks_hit                        [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.table.tidx_blks_ratio                      [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.index.idx_scan                             [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.index.idx_tup_read                         [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.index.idx_tup_fetch                        [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.index.idx_blks_read                        [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.index.idx_blks_hit                         [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
zabbix_agentd [23727]: Error: PostgreSQL: fe_sendauth: no password supplied

pg.index.idx_blks_ratio                       [m|ZBX_NOTSUPPORTED] [fe_sendauth: no password supplied
pgsql.get.pg.transactions                     [t|sh: 1: /pgsql_server_funcs.sh: not found]
pgsql.get.pg.bgwriter                         [t|sh: 1: /pgsql_server_funcs.sh: not found]
pgsql.get.pg.slow_query                       [t|sh: 1: /pgsql_server_funcs.sh: not found]
pgsql.get.pg.stat_database                    [t|sh: 1: /pgsql_db_funcs.sh: not found]
pgsql.get.pg.size                             [t|sh: 1: /pgsql_userdb_funcs.sh: not found]
pgsql.get.pg.stat_table                       [t|sh: 1: /pgsql_tbl_funcs.sh: not found]
pgsql.get.pg.stat_replication                 [t|sh: 1: /pgsql_sr_server_funcs.sh: not found]
pgsql.get.pg.sr.status                        [t|sh: 1: /pgsql_sr_server_funcs.sh: not found]
pgpool.running                                [t|sh: 1: /pgpool_simple.sh: not found]
pgpool.have_delegate_ip                       [t|sh: 1: /pgpool_delegate_ip.sh: not found]
pgpool.get.nodes                              [t|sh: 1: /pgpool_backend_status.sh: not found]
pgpool.get.connections                        [t|sh: 1: /pgpool_connections.sh: not found]
pgpool.get.cache                              [t|sh: 1: /pgpool_cache.sh: not found]
####################################
