### ISSUE TITLE
in postgres <9.3 different errors

### ISSUE THREAD

**Issue by colttt** [cavaliercoder/libzbxpgsql#3]
Hello,

on postgres 9.3 i dont get values from pg.setting = "ZBX_NOTSUPPORTED"

on Postgres 8.4 i don't get items like psql.db_deadlocks, psql.db_temp_bytes, psql.idle_tx_connections etc.. "Received value [] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]"

**Comment by cavaliercoder** [comment]
I've fixed a bunch of issues with < 9.2 in the latest release (v0.2.0).
Any item keys that require a specific PostgreSQL version are now noted in the documentation.

E.g. http://cavaliercoder.github.io/libzbxpgsql/agent-keys/server/#pg-queries-longest
