### ISSUE TITLE
Can only discover a single instance of postgres on DB per server?

### ISSUE THREAD

**Issue by Wicaeed** [cavaliercoder/libzbxpgsql#31]
Greetings,

Been messing around with your plugin for a few weeks, and may have come up with an edge case.

A previous DBA had a bad habit of setting up multiple instances of postgres to run on separate ports on a single server. With the macro {$PG_CONN} can you specify more than one port to attempt connection to, or can you only connect to a single port per database server?

Thanks for the excellent plugin!

**Comment by cavaliercoder** [comment]
Thanks for raising this. I think a few people will have similar scenarios so I'll have a think about creative ways to solve it.

In the meantime, you may only specify a single instance to connect to in the connection parameter.
There are a few ways to solve this problem; none of which seem elegant to me. You could:

* create multiple hosts in Zabbix for the same database server and apply the template with different connection strings to each
* duplicate the template but rename `{$PG_CONN}` on the second template to something different. Then apply both templates to your database server
* re-hire the previous DBA, get them to configure virtual interfaces instead and then fire them again

**Comment by henriavelabarbe** [comment]
Hi,
don't know if it's the good place to post, but I have a similar situation.
We have multiple clusters on some hosts listening to different ports.
I tried the method to create a template copy and assign it to the same host.
I'm having an issue with the discovery rules and applications already existing on the host.
I suppose I could modify those names in the second template, but it starts to get nasty.
Next, I wanted to try the additional host entry in Zabbix, but I don't know where to specify the second host name.
Any new elegant and creative way to solve this ?

Regards

**Comment by Wicaeed** [comment]
Hey there,

When you create the second host entry in Zabbix you can give it a name that is unique, but specify the same Agent Interface (db server) as is used by the first entry. With that done you can specify the second instances {$PG_CONN} and {$PG_DB} connection strings that point to the second DB instances port/db.

Hope this helps.

**Comment by henriavelabarbe** [comment]
Hi,
thanks for your answer.
I tried that but it seems the module here is expecting the same hostname in the zabbix agent configuration file and in the zabbix console.
So for instance, I have a machine server1.domain.com.
The machine is configured in Zabbix to use a Linux template and the postgresql template here.
If I configure in Zabbix the host as SERVER1, the metrics for the postgresql template are not uploaded, while the ones for the Linux template are.
So I have to match exactly the name in the zabbix_agentd.conf and in the Zabbix console.
When I add a second host (SERVER1_PGCLUSTER2 with only the postgresql template), that host is never populated with the postgresql metrics.

**Comment by henriavelabarbe** [comment]
And when I change Hostname=SERVER1_PGCLUSTER2 in  zabbix_agentd.conf, I can see the metrics in SERVER1_PGCLUSTER2 in Zabbix, but metrics for SERVER1 are not uploaded anymore.

**Comment by henriavelabarbe** [comment]
I found a solution using several templates.
I added the port number to all "<name>PostgreSQL" entries in the xml file, did the same for all macros and removed the pg.modver item and trigger in all but the base template.
That allowed me to configure a server with 3 templates, each on different port.
It covers 99.999% of my needs here.
Maybe it could be done by just adding the port number or a more generalist cluster alias in the macros and passing that cluster alias in all the items / triggers / names..
Templates are attached in the zip files (module v 1.1.0 zabbix 3.2)

**Comment by weekender81** [comment]
Hi ! I found a solution how to monitor multiple instances in postgres. It`s very simple: Firstly You must execute multiple instances of zabbix agents on PostgreSQL server side. The count of Zabbex agents instances = PostgreSQL instances. How to do it you can read in zabbix forums. Secondary in Zabbix create new hosts. Count of hosts = Count of Zabbix agents running on Postgres side. that`s all tricks :) If will be questions - feel free to write me.
