### ISSUE TITLE
invalid port number for value in $PG_DB

### ISSUE THREAD

**Issue by clark0r** [cavaliercoder/libzbxpgsql#36]
Zabbix server is up and running, Zabbix agent is installed and configured to work in active mode.  libzbxpgsql.x86_64 is installed on the database host, along with the postgresql93-libs.x86_64 prerequisite.

The host has the template assigned, and the following macros are set on the host in zabbix:

```
{$PG_CONN}
hostaddr = 127.0.0.1 port = 5432 user = POSTGRES

{$PG_DB}
database
```

These work on the cli:
```
[root@server lib64]# psql -U postgres -h 127.0.0.1 -p 5432 database
psql (9.3.5)
Type "help" for help.

database=# 
```

When I restart the zabbix-agent service, I get the following in /var/log/zabbix/zabbix_agentd.log :
 ```
30241:20160303:145502.900 Failed to connect to PostgreSQL server 'hostaddr = 127.0.0.1 port = 5432 user = POSTGRES' in PG_CONNECT():
invalid port number: "database"

 30241:20160303:145502.900 active check "pg.version[hostaddr = 127.0.0.1 port = 5432 user = POSTGRES,database]" is not supported
```

Any ideas?

**Comment by cavaliercoder** [comment]
Thanks for raising this. I'm having trouble reproducing this issue though for now I may be testing with different versions. Can you please confirm the exact versions you are running of the Zabbix agent, PostgreSQL libs, client and server.

Can you please also try to reproduce the error using `zabbix_get`?

E.g.
```
$ zabbix_get -s 127.0.0.1 -k "pg.connect[hostaddr = 127.0.0.1 port = 5432 user = POSTGRES,database]"
```

**Comment by clark0r** [comment]
Ran zabbix_get from the zabbix server (running locally on the database server gave me denied errors):
```
[root@zabbix ~]# zabbix_get -s server -k "pg.connect[hostaddr = 127.0.0.1 port = 5432 user = POSTGRES,database]"
0

```

Packages:
```
libzbxpgsql.x86_64               0.1.1-1.el7.centos             installed       
pgdg-redhat93.noarch             9.3-1                          @/pgdg-redhat93-9.3-1.noarch
postgresql93.x86_64              9.3.5-2PGDG.rhel7              @yum.postgresql.org
postgresql93-contrib.x86_64      9.3.5-2PGDG.rhel7              @pgdg93         
postgresql93-devel.x86_64        9.3.5-2PGDG.rhel7              @pgdg93         
postgresql93-libs.x86_64         9.3.5-2PGDG.rhel7              @yum.postgresql.org
postgresql93-plperl.x86_64       9.3.5-2PGDG.rhel7              @pgdg93         
postgresql93-server.x86_64       9.3.5-2PGDG.rhel7              @yum.postgresql.org

zabbix.x86_64                    2.2.11-1.el7                         
zabbix-agent.x86_64              2.2.11-1.el7                         
```

**Comment by cavaliercoder** [comment]
Could you please try libzbxpgsql v0.2.1 as this is the most recent.

**Comment by cavaliercoder** [comment]
Closing due after no response. Please try with v0.2.1+ and advise if the issue persists.
