### ISSUE TITLE
table and index discovery only for PG_DB

### ISSUE THREAD

**Issue by robbrucks** [cavaliercoder/libzbxpgsql#38]
Hey Ryan,

This module rocks!  It's pretty awesome!

But I did find what appears to be a minor bug.

If I enable table and index auto-discovery then it appears to only discover them in the DB defined by the PG_DB macro, not all the DBs that zabbix can connect to.

I'm using:
PG 9.4.6 running on Centos 6.7 x86_86
Zabbix 2.4.7 running on Centos 7.2.1511 x86_64

I have 2 DBs on postgres:
zabbix  (containing the zabbix tables)
pgbench  (the benchmarking tables)

I have no filters set in the discovery.

When I left the default PG_DB macro set to the "postgres" DB it failed to discover any tables because the "postgres" DB was empty.  Everything other than individual table and index metrics appeared to be collected for the "zabbix" DB.

When I switched PG_DB macro to "zabbix" it then discovered all the Zabbix tables and indexes.  Then I switched PG_DB to "pgbench" and it discovered the tables and indexes there.

Thanks!
Rob

**Comment by cavaliercoder** [comment]
Thanks for the feedback!

This is fixed in #11 which is pending release in v2.0.

In the current release does discovery is only for [tables in the currently connected database](http://cavaliercoder.com/libzbxpgsql/agent-keys/tables/#pg-table-discovery).
