### ISSUE TITLE
Fix unsupported items for unprivileged PostgreSQL roles

### ISSUE THREAD

**Issue by colttt** [cavaliercoder/libzbxpgsql#4]
Hello,

it would be nice if you add a sql-query for an example-user that has only read-permissions to all tables that you need in this module

**Comment by cavaliercoder** [comment]
I definitely agree! I'm trying to find a nice way of doing this but I anticipate being able to do so in the next release v0.1.4.

**Comment by cavaliercoder** [comment]
I've updated the documentation with instructions for creating a limited privilege role for monitoring. I've confirmed it works on PostgreSQL v8.4 - 9.4 for all items.
The only exception, is `pg.tablespace.size[,,pg_global]` which requires `superuser` access.

http://cavaliercoder.github.io/libzbxpgsql/agent-keys/#monitoring-role
