### ISSUE TITLE
Support long queries in key parameters

### ISSUE THREAD

**Issue by robbrucks** [cavaliercoder/libzbxpgsql#41]
Hey Ryan,

I'm trying to use your pg.query.integer key and I've run into a limitation on the length of the key.  Looks like Zabbix has a 255 character limit on key length, which limits the SQL query to around 200 characters (depending on other parameters).  I was hoping it was only a limitation on the UI, but even editing the XML for the template and trying to import it gives the same error.

As a workaround I'm going to try using a variable macro to form part of the query.  If all else fails I'll create a function in the DB (but I really, really want to avoid that since we'll have dozens of deployments).

I also intend to create some queries to monitor application-level tables, and these queries could also exceed the length limitation.

Can you suggest another method to pass a long query to your plugin keys?

Thanks,
Rob

**Comment by robbrucks** [comment]
It appears putting the query into a macro variable works, but it's not an ideal solution.  Some of the queries at the app level are going to be around 400 characters.  I don't want to create a bunch of macro variables for those.

Any suggestions?

Thanks,
Rob

**Comment by cavaliercoder** [comment]
Hmmm... really good challenge. We could push for the character limit to be increased but I'm not convinced that is a smart way forward.

How helpful would it be if I documented up a template for writing and compiling your own keys in the module? Just copy and paste in your own queries and `make`.

**Comment by robbrucks** [comment]
I'd prefer a method that wouldn't require recompiling every time we change something.  Would it be possible to read the sql by key from a config file in "/etc/zabbix" or "/etc/zabbix/zabbix_agentd.d" ?

**Comment by cavaliercoder** [comment]
Would you prefer to define all of your queries in an INI style file or as individual query files?

I think individual files would be better in that there is no character escaping required. The query could then be referenced in the Zabbix agent key by file name. E.g. `pg.query.interger[,,query_file]`. These could maybe be stored in `/etc/zabbix/libzbxpgsql.d/*.sql` or a path configured via environment variable. This is also fairly simple to implement in code.

A single config file could get a little unwieldy with lots of multi-line queries and character escaping, but it would more intuitive for defining other things like a pre-allocated agent key, data type, etc.

**Comment by robbrucks** [comment]
If I had to choose between them I'd go with a single file, but if you feel strongly about multiple files I could live with that. IMHO a single file is easier to maintain.  Plus if you have need to define other parameters (like maybe session options such as statement_timeout... hint hint) they could live there as well.

Escaping things isn't a big deal to me... I live for dollar quotes and backslashes... lol!

Simple variable assignment or INI or YAML or whatever standard you want to use would be fine, I can adapt. Even XML would work (sigh), though I hate XML.

BTW - Thanks for all your hard work on this, I think this plugin will rapidly become very popular!

**Comment by cavaliercoder** [comment]
I've pushed some fairly major refactoring in 4663596. I apologise as it has removed your contributions from blame view, but your implementation and commit history are still in tact.

These are few changes that are hopefully of value:
- there's a single config file now, that can be used to import additional config files, instead of using file globbing
- configuration files can be used for other future things - for now it only supports `queries = {}`
- config/named-query logic is in a discrete code file `src/pg_config.c`
- theres a lot less log noise now

**Comment by cavaliercoder** [comment]
Added in release v1.1.0
