### ISSUE TITLE
Template Multiplier Wrong

### ISSUE THREAD

**Issue by robbrucks** [cavaliercoder/libzbxpgsql#42]
Thought I'd give you something easy...

The IO stats metrics have the wrong multiplier set in the template for these two discovery item prototypes:

Time spent reading data ({#DATABASE})

Time spent writing data ({#DATABASE})

They both have a multiplier setting of 1000, but they should be 0.0001.  Those metrics come from the blk_read_time and blk_write_time columns of pg_stat_database, which are measured in milliseconds, so need to be divided by 1000.

When I turned them on for a fresh install and ran pgbench it said I'd spent days writing data and months reading data... lol.

Thanks,
Rob

**Comment by cavaliercoder** [comment]
Thanks for spotting that. I thought I had published the fix already in #26. Will do shortly.

**Comment by jamescook000** [comment]
Hi Ryan,

Just to confirm the multiplier should be 0.001 not 0.0001 for milliseconds to seconds conversion.

Cheers

**Comment by robbrucks** [comment]
You are correct, I just got zero happy.

**Comment by cavaliercoder** [comment]
Duplicate fixed in #26
