### ISSUE TITLE
Longest running query

### ISSUE THREAD

**Issue by robbrucks** [cavaliercoder/libzbxpgsql#44]
This is using the libzbxpgsql module 0.2.1 from RPM.

It looks like the "Longest running query" is getting incorrect data.  I'm getting back negative values 
around -1.4ms on an idle system:
```
2016-04-29 13:35:04    -0.0012
2016-04-29 13:30:04    -0.0016
2016-04-29 13:25:03    -0.0013
```

When I enable full logging I see the following query, which appears correct:
```
SELECT   EXTRACT(EPOCH FROM NOW()) - EXTRACT(EPOCH FROM query_start) AS duration FROM pg_stat_activity WHERE state = 'active' ORDER BY duration DESC LIMIT 1
```

When I run the SQL manually I always get zero on my idle system.

Could the module be returning the wrong data?

Thanks,
Rob

**Comment by cavaliercoder** [comment]
This should be fixed in 14e36f1 which is yet to be released. This error condition occurs when no application queries are in process and PostgreSQL reports `query_start` to be slightly later than `NOW()` for the 'longest query' query being called by the Zabbix agent.
