### ISSUE TITLE
fe_sendauth: no password supplied module libzbxpgsql 0.2.1

### ISSUE THREAD

**Issue by mijaresey** [cavaliercoder/libzbxpgsql#47]
Hi good afternoon , I need help regarding an error that is generated when loading the module libzbxpgsql

my pg_hba
Local all zabbix peer map = zabbix #prueba

my pg_ident

zabbix root zabbix

macro template
host = 127.0.0.1 port = 5432 password = user = zabbix zabbix

after making this configuration still gives the following error

zabbix_agentd [22302]: Starting agent module libzbxpgsql 0.2.1
pg.modver                                     [s|libzbxpgsql 0.2.1]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.connect                                    [u|0]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.version                                    [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.starttime                                  [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.uptime                                     [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.setting[,,data_directory]                  [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.setting.discovery                          [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.query.string[,,SELECT 'Lorem ipsum dolor';] [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.query.integer[,,SELECT pg_backend_pid();]  [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.query.double[,,SELECT CAST(1234 AS double precision);] [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.query.discovery[,,SELECT \* FROM pg_database;] [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.backends.count                             [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.queries.longest                            [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.checkpoints_timed                          [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.checkpoints_req                            [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.checkpoint_write_time                      [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.checkpoint_sync_time                       [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.buffers_checkpoint                         [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.buffers_clean                              [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.maxwritten_clean                           [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.buffers_backend                            [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.buffers_backend_fsync                      [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.buffers_alloc                              [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.stats_reset                                [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.db.discovery                               [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.namespace.discovery                        [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.schema.discovery                           [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.tablespace.discovery                       [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.discovery                            [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.children.discovery[,,pg_proc]        [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.index.discovery                            [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.db.size                                    [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.size                                 [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.rows                                 [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.children[,,pg_database]              [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.children.size[,,pg_database]         [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.children.rows[,,pg_database]         [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.index.size                                 [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.index.rows                                 [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.tablespace.size[,,pg_default]              [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.namespace.size[,,pg_catalog]               [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.schema.size[,,pg_catalog]                  [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.db.numbackends                             [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.db.xact_commit                             [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.db.xact_rollback                           [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.db.blks_read                               [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.db.blks_hit                                [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.db.tup_returned                            [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.db.tup_fetched                             [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.db.tup_inserted                            [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.db.tup_updated                             [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.db.tup_deleted                             [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.db.conflicts                               [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.db.temp_files                              [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.db.temp_bytes                              [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.db.deadlocks                               [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.db.blk_read_time                           [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.db.blk_write_time                          [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.db.stats_reset[,,postgres,,,]              [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.seq_scan                             [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.seq_tup_read                         [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.idx_scan                             [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.idx_tup_fetch                        [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.n_tup_ins                            [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.n_tup_upd                            [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.n_tup_del                            [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.n_tup_hot_upd                        [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.n_live_tup                           [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.n_dead_tup                           [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.last_vacuum[,,pg_database]           [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.last_autovacuum[,,pg_database]       [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.last_analyze[,,pg_database]          [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.last_autoanalyze[,,pg_database]      [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.vacuum_count                         [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.autovacuum_count                     [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.analyze_count                        [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.autoanalyze_count                    [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.heap_blks_read                       [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.heap_blks_hit                        [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.idx_blks_read                        [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.idx_blks_hit                         [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.toast_blks_read                      [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.toast_blks_hit                       [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.tidx_blks_read                       [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.table.tidx_blks_hit                        [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.index.idx_scan                             [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.index.idx_tup_read                         [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.index.idx_tup_fetch                        [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.index.idx_blks_read                        [m|ZBX_NOTSUPPORTED]
zabbix_agentd [22302]: Error: Failed to connect to PostgreSQL in pg_connect():
fe_sendauth: no password supplied

pg.index.idx_blks_hit                         [m|ZBX_NOTSUPPORTED]
sh: 1: /find_dbname.sh: not found
sh: 1: /find_dbname_table.sh: not found
sh: 1: /find_sr.sh: not found
sh: 1: /find_sr_client_ip.sh: not found
sh: 1: /find_dbname.sh: not found
sh: 1: /pgsql_simple.sh: not found
sh: 1: /pgsql_primary.sh: not found
sh: 1: /pgsql_standby.sh: not found
sh: 1: /pgsql_server_funcs.sh: not found
sh: 1: /pgsql_server_funcs.sh: not found
sh: 1: /pgsql_server_funcs.sh: not found
sh: 1: /pgsql_db_funcs.sh: not found
sh: 1: /pgsql_userdb_funcs.sh: not found
sh: 1: /pgsql_tbl_funcs.sh: not found
sh: 1: /pgsql_sr_server_funcs.sh: not found
sh: 1: /pgsql_sr_server_funcs.sh: not found
sh: 1: /find_pgpool_backend.sh: not found
sh: 1: /find_pgpool_backend_ip.sh: not found
sh: 1: /pgpool_simple.sh: not found
sh: 1: /pgpool_delegate_ip.sh: not found
sh: 1: /pgpool_backend_status.sh: not found
sh: 1: /pgpool_connections.sh: not found
sh: 1: /pgpool_cache.sh: not found

**Comment by cavaliercoder** [comment]
Thanks for posting this issue with detailed information.

Can you please confirm that your `~/.pgpass` file is correctly configured for root (assuming the Zabbix agent is running as root)?

Please see:
* http://cavaliercoder.com/libzbxpgsql/agent-keys/#remote-monitoring-agent
* https://www.postgresql.org/docs/current/static/libpq-pgpass.html

**Comment by cavaliercoder** [comment]
Oops... I notice you are using `peer` authentication. This will only work for local connections, not TCP. You need to change your `host` connection parameter to the directory of your listening socket (typically `/tmp` on EL family OS) or switch from `peer` auth to `md5` and configure the `.pgpass` file.

**Comment by mijaresey** [comment]
hi, thanks for answering ! change the settings as you indicated me
pg_hba : host all zabbix 10.100.2.27/32 md5

 my .pgpass place it in /etc/zabbix/.pgpass file , the file content is:
*: *: *: Zabbix : zabbix

restart the agent and the postgresl and still gives me the same error, I can not really be doing wrong .

**Comment by cavaliercoder** [comment]
If you are still seeing the `fe_sendauth: no password supplied` error, this is caused by misconfiguration of the PostgreSQL client library with relies on a correctly configured `~/.pgpass` file.

Please follow the PostgreSQL documentation and confirm the password is correctly read by testing with the `psql` client binary. https://www.postgresql.org/docs/current/static/libpq-pgpass.html
