### ISSUE TITLE
Error: Check access restrictions in Zabbix agent configuration

### ISSUE THREAD

**Issue by mmitucha** [cavaliercoder/libzbxpgsql#48]
Hello, 

I would like to ask for advice because of strange behaviour of zabbix-agent with 'libzbxpgsql' module.
Everything works fine, but no data coming from zabbix agent 'libzbxpgsql' module.

Zabbix Agent works fine, can see data from 'Template OS Linux' in Zabbix Web, but no data from 'Template PostgreSQL Server'.

So I started investigating. 

Scenario
 - zabbix-server (sk1zbx001p)
 - zabbix-agent (sk1psql001t) with PostgreSQL Server v9.2.15

Zabbix (agent, server) v3.0.3
libzbxpgsql v0.2.1

Both systems: CentOS Linux release 7.2.1511 (Core)  (on VMware)
 - kernel 3.10.0-327.18.2.el7.x86_64

SELinux is disabled.

When I try to get some "genereral" key (e.g. `system.cpu.load[all,avg1]`), it is OK, but when I try to get some key from 'libzbxpgsql' library (e.g. `pg.modver`), I get: 

    zabbix_get [11939]: Check access restrictions in Zabbix agent configuration

All processes are running as 'zabbix' user. 
I am connecting to database as 'monitoring' user with peer auth mapped from user 'zabbix', it works OK. 

More debug info in attachment (using 'zabbix_get').
[debug.txt](https://github.com/cavaliercoder/libzbxpgsql/files/310266/debug.txt)

I really have no other ideas what to try, so will be very thankfull for any advice.

**Comment by cavaliercoder** [comment]
There have been a few bug fixes to modules in the Zabbix agent version 3. Can you please upgrade your agent and the module to latest version and then advise if the issue persists?

If the problem stays, please submit the output from `zabbix_agentd -t pg.modver`

**Comment by zinhteo0603** [comment]
Hello cavaliercode!
my output information with command: "zabbix-agentd -t pg.modver"
pg.modver                   [m|ZBX_NOTSUPPORTED]   [Unsupported item key.]
I'm use zabbix version 3.0.4 on CentOS release 6.8 (Final)

Please help me
P/s: error:  Check access restrictions in Zabbix agent configuration

**Comment by cavaliercoder** [comment]
Can you see the module initializing in the agent log file? Can you please post a sample of the logs from agent start until this error is produced?

**Comment by zinhteo0603** [comment]
Hi Cavaliercoder.
I fixed above problem with wrong configuration my network.
Thanks you for reply me soon.

**Comment by cavaliercoder** [comment]
In case anyone else has a similar issue, can you please post how you fixed it?

**Comment by mmitucha** [comment]
Sorry for long response.
I tested it today, I confirm it works (like a charm). 

Thank you very much.

**Comment by r0039** [comment]
> Hi Cavaliercoder.
> I fixed above problem with wrong configuration my network.
> Thanks you for reply me soon.

Hi @zinhteo1110  could you please let me know what did you do to solve this?
Thank you so much!

**Comment by harrisonratcliffe** [comment]
Anyone know the solution?

**Comment by parul010282** [comment]
> zabbix_agentd -t pg.modver

[root@stackstormdev ~]# zabbix_agentd -t pg.modver
pg.modver                                     [m|ZBX_NOTSUPPORTED] [Unsupported item key.]



I Face the same problem, not sure how to proceed on this. Please suggest the resolution..

**Comment by i-ky** [comment]
> [root@stackstormdev ~]# zabbix_agentd -t pg.modver
pg.modver [m|ZBX_NOTSUPPORTED] [Unsupported item key.]

"Unsupported item key." means that module is not even loaded by Zabbix agent. Make sure you point Zabbix agent to a correct configuration file, make sure there is `LoadModule=` in it, etc.
