### ISSUE TITLE
Signal SIGSEGV after zabbix agent start

### ISSUE THREAD

**Issue by MaXoo459** [cavaliercoder/libzbxpgsql#5]
Hi,
I've just tried to use your new module for Zabbix.
I follow the installation and configuration guide.
But when I start the zabbix-agent service, it crashed few seconds after.
Here my logs :
---------------------
 18196:20150515:140934.555 Failed to execute PostgreSQL query in pg_get_int(pg.backends.count) with: ERROR:  column "pid" does not exist
LINE 1: SELECT COUNT(pid) FROM pg_stat_activity
                     ^

 18196:20150515:140934.555 active check "pg.backends.count[localhost,5432,zabbix_server,postgres,network]" is not supported
 18196:20150515:140934.555 Got signal [signal:11(SIGSEGV),reason:1,refaddr:(nil)]. Crashing ...
 18196:20150515:140934.555 ====== Fatal information: ======
 18196:20150515:140934.555 Program counter: 0x40db70
 18196:20150515:140934.555 === Registers: ===
 18196:20150515:140934.555 r8      =     7f5b029d3720 =      140028862609184 =      140028862609184
 18196:20150515:140934.555 r9      =                1 =                    1 =                    1
 18196:20150515:140934.555 r10     = 5d6b726f7774656e =  6731599891106391406 =  6731599891106391406
 18196:20150515:140934.555 r11     =              206 =                  518 =                  518
 18196:20150515:140934.555 r12     =             2743 =                10051 =                10051
 18196:20150515:140934.555 r13     =           7f5d10 =              8346896 =              8346896
 18196:20150515:140934.555 r14     =                0 =                    0 =                    0
 18196:20150515:140934.555 r15     =              1c0 =                  448 =                  448
 18196:20150515:140934.555 rdi     =           43b150 =              4436304 =              4436304
 18196:20150515:140934.555 rsi     =              172 =                  370 =                  370
 18196:20150515:140934.555 rbp     =         5555e1fd =           1431691773 =           1431691773
 18196:20150515:140934.555 rbx     =              180 =                  384 =                  384
 18196:20150515:140934.555 rdx     =           648d64 =              6589796 =              6589796
 18196:20150515:140934.555 rax     =           7ff160 =              8384864 =              8384864
 18196:20150515:140934.555 rcx     =           7f6410 =              8348688 =              8348688
 18196:20150515:140934.555 rsp     =     7fff7f5a0510 =      140735329994000 =      140735329994000
 18196:20150515:140934.555 rip     =           40db70 =              4250480 =              4250480
 18196:20150515:140934.555 efl     =            10202 =                66050 =                66050
 18196:20150515:140934.555 csgsfs  =               33 =                   51 =                   51
 18196:20150515:140934.555 err     =                4 =                    4 =                    4
 18196:20150515:140934.555 trapno  =                e =                   14 =                   14
 18196:20150515:140934.555 oldmask =                0 =                    0 =                    0
 18196:20150515:140934.555 cr2     =                0 =                    0 =                    0
 18196:20150515:140934.555 === Backtrace: ===
 18196:20150515:140934.556 10: /usr/sbin/zabbix_agentd: active checks #1 [processing active checks](print_fatal_info+0x9e) [0x425c9e]
 18196:20150515:140934.556 9: /usr/sbin/zabbix_agentd: active checks #1 [processing active checks]() [0x4260a7]
 18196:20150515:140934.556 8: /lib/x86_64-linux-gnu/libc.so.6(+0x321e0) [0x7f5b015061e0]
 18196:20150515:140934.556 7: /usr/sbin/zabbix_agentd: active checks #1 [processing active checks]() [0x40db70]
 18196:20150515:140934.556 6: /usr/sbin/zabbix_agentd: active checks #1 [processing active checks](active_checks_thread+0x1d7) [0x40e247]
 18196:20150515:140934.556 5: /usr/sbin/zabbix_agentd: active checks #1 [processing active checks](zbx_thread_start+0x62) [0x424912]
 18196:20150515:140934.556 4: /usr/sbin/zabbix_agentd: active checks #1 [processing active checks](MAIN_ZABBIX_ENTRY+0x222) [0x4130e2]
 18196:20150515:140934.556 3: /usr/sbin/zabbix_agentd: active checks #1 [processing active checks](daemon_start+0x18c) [0x4255ac]
 18196:20150515:140934.556 2: /usr/sbin/zabbix_agentd: active checks #1 [processing active checks](main+0x171) [0x40bfe1]
 18196:20150515:140934.556 1: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xfd) [0x7f5b014f2ead]
 18196:20150515:140934.556 0: /usr/sbin/zabbix_agentd: active checks #1 [processing active checks]() [0x40c0d1]
 18196:20150515:140934.556 === Memory map: ===
 18196:20150515:140934.556 00400000-00447000 r-xp 00000000 fe:00 22385                              /usr/sbin/zabbix_agentd
 18196:20150515:140934.556 00647000-00649000 rw-p 00047000 fe:00 22385                              /usr/sbin/zabbix_agentd
 18196:20150515:140934.556 00649000-0064e000 rw-p 00000000 00:00 0
 18196:20150515:140934.556 007ef000-00810000 rw-p 00000000 00:00 0                                  [heap]
 18196:20150515:140934.556 00810000-00929000 rw-p 00000000 00:00 0                                  [heap]
 18196:20150515:140934.556 7f5afda82000-7f5afda97000 r-xp 00000000 fe:00 128526                     /lib/x86_64-linux-gnu/libgcc_s.so.1
 18196:20150515:140934.556 7f5afda97000-7f5afdc97000 ---p 00015000 fe:00 128526                     /lib/x86_64-linux-gnu/libgcc_s.so.1
 18196:20150515:140934.556 7f5afdc97000-7f5afdc98000 rw-p 00015000 fe:00 128526                     /lib/x86_64-linux-gnu/libgcc_s.so.1
 18196:20150515:140934.556 7f5afdc98000-7f5afde62000 r-xp 00000000 fe:00 4817                       /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
 18196:20150515:140934.556 7f5afde62000-7f5afe062000 ---p 001ca000 fe:00 4817                       /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
 18196:20150515:140934.556 7f5afe062000-7f5afe07d000 r--p 001ca000 fe:00 4817                       /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
 18196:20150515:140934.556 7f5afe07d000-7f5afe08c000 rw-p 001e5000 fe:00 4817                       /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
 18196:20150515:140934.556 7f5afe08c000-7f5afe090000 rw-p 00000000 00:00 0
 18196:20150515:140934.556 7f5afe090000-7f5afe0e6000 r-xp 00000000 fe:00 4832                       /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
 18196:20150515:140934.556 7f5afe0e6000-7f5afe2e6000 ---p 00056000 fe:00 4832                       /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
 18196:20150515:140934.556 7f5afe2e6000-7f5afe2e9000 r--p 00056000 fe:00 4832                       /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
 18196:20150515:140934.556 7f5afe2e9000-7f5afe2f0000 rw-p 00059000 fe:00 4832                       /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
 18196:20150515:140934.556 7f5afe2f0000-7f5afe31a000 r-xp 00000000 fe:00 18655                      /usr/lib/libpq.so.5.4
 18196:20150515:140934.556 7f5afe31a000-7f5afe519000 ---p 0002a000 fe:00 18655                      /usr/lib/libpq.so.5.4
 18196:20150515:140934.556 7f5afe519000-7f5afe51b000 r--p 00029000 fe:00 18655                      /usr/lib/libpq.so.5.4
 18196:20150515:140934.557 7f5afe51b000-7f5afe51d000 rw-p 0002b000 fe:00 18655                      /usr/lib/libpq.so.5.4
 18196:20150515:140934.557 7f5afe51d000-7f5afe526000 r-xp 00000000 fe:00 27633                      /usr/lib/modules/libzbxpgsql.so
 18196:20150515:140934.557 7f5afe526000-7f5afe725000 ---p 00009000 fe:00 27633                      /usr/lib/modules/libzbxpgsql.so
 18196:20150515:140934.557 7f5afe725000-7f5afe726000 r--p 00008000 fe:00 27633                      /usr/lib/modules/libzbxpgsql.so
 18196:20150515:140934.557 7f5afe726000-7f5afe727000 rw-p 00009000 fe:00 27633                      /usr/lib/modules/libzbxpgsql.so
 18196:20150515:140934.557 7f5afe727000-7f5afe732000 r-xp 00000000 fe:00 128612                     /lib/x86_64-linux-gnu/libnss_files-2.13.so
 18196:20150515:140934.557 7f5afe732000-7f5afe931000 ---p 0000b000 fe:00 128612                     /lib/x86_64-linux-gnu/libnss_files-2.13.so
 18196:20150515:140934.557 7f5afe931000-7f5afe932000 r--p 0000a000 fe:00 128612                     /lib/x86_64-linux-gnu/libnss_files-2.13.so
 18196:20150515:140934.557 7f5afe932000-7f5afe933000 rw-p 0000b000 fe:00 128612                     /lib/x86_64-linux-gnu/libnss_files-2.13.so
 18196:20150515:140934.557 7f5afe933000-7f5afe93d000 r-xp 00000000 fe:00 128614                     /lib/x86_64-linux-gnu/libnss_nis-2.13.so
 18196:20150515:140934.557 7f5afe93d000-7f5afeb3c000 ---p 0000a000 fe:00 128614                     /lib/x86_64-linux-gnu/libnss_nis-2.13.so
 18196:20150515:140934.558 7f5afeb3c000-7f5afeb3d000 r--p 00009000 fe:00 128614                     /lib/x86_64-linux-gnu/libnss_nis-2.13.so
 18196:20150515:140934.558 7f5afeb3d000-7f5afeb3e000 rw-p 0000a000 fe:00 128614                     /lib/x86_64-linux-gnu/libnss_nis-2.13.so
 18196:20150515:140934.558 7f5afeb3e000-7f5afeb53000 r-xp 00000000 fe:00 128609                     /lib/x86_64-linux-gnu/libnsl-2.13.so
 18196:20150515:140934.558 7f5afeb53000-7f5afed52000 ---p 00015000 fe:00 128609                     /lib/x86_64-linux-gnu/libnsl-2.13.so
 18196:20150515:140934.558 7f5afed52000-7f5afed53000 r--p 00014000 fe:00 128609                     /lib/x86_64-linux-gnu/libnsl-2.13.so
 18196:20150515:140934.558 7f5afed53000-7f5afed54000 rw-p 00015000 fe:00 128609                     /lib/x86_64-linux-gnu/libnsl-2.13.so
 18196:20150515:140934.558 7f5afed54000-7f5afed56000 rw-p 00000000 00:00 0
 18196:20150515:140934.558 7f5afed56000-7f5afed5d000 r-xp 00000000 fe:00 128610                     /lib/x86_64-linux-gnu/libnss_compat-2.13.so
 18196:20150515:140934.558 7f5afed5d000-7f5afef5c000 ---p 00007000 fe:00 128610                     /lib/x86_64-linux-gnu/libnss_compat-2.13.so
 18196:20150515:140934.558 7f5afef5c000-7f5afef5d000 r--p 00006000 fe:00 128610                     /lib/x86_64-linux-gnu/libnss_compat-2.13.so
 18196:20150515:140934.558 7f5afef5d000-7f5afef5e000 rw-p 00007000 fe:00 128610                     /lib/x86_64-linux-gnu/libnss_compat-2.13.so
 18196:20150515:140934.558 7f5afef5e000-7f5afef61000 r-xp 00000000 fe:00 135251                     /lib/x86_64-linux-gnu/libkeyutils.so.1.4
 18196:20150515:140934.559 7f5afef61000-7f5aff160000 ---p 00003000 fe:00 135251                     /lib/x86_64-linux-gnu/libkeyutils.so.1.4
 18196:20150515:140934.559 7f5aff160000-7f5aff161000 r--p 00002000 fe:00 135251                     /lib/x86_64-linux-gnu/libkeyutils.so.1.4
 18196:20150515:140934.559 7f5aff161000-7f5aff162000 rw-p 00003000 fe:00 135251                     /lib/x86_64-linux-gnu/libkeyutils.so.1.4
 18196:20150515:140934.559 7f5aff162000-7f5aff16a000 r-xp 00000000 fe:00 9728                       /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
 18196:20150515:140934.559 7f5aff16a000-7f5aff369000 ---p 00008000 fe:00 9728                       /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
 18196:20150515:140934.559 7f5aff369000-7f5aff36a000 r--p 00007000 fe:00 9728                       /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
 18196:20150515:140934.559 7f5aff36a000-7f5aff36b000 rw-p 00008000 fe:00 9728                       /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
 18196:20150515:140934.559 7f5aff36b000-7f5aff36e000 r-xp 00000000 fe:00 128768                     /lib/x86_64-linux-gnu/libcom_err.so.2.1
 18196:20150515:140934.559 7f5aff36e000-7f5aff56d000 ---p 00003000 fe:00 128768                     /lib/x86_64-linux-gnu/libcom_err.so.2.1
 18196:20150515:140934.559 7f5aff56d000-7f5aff56e000 r--p 00002000 fe:00 128768                     /lib/x86_64-linux-gnu/libcom_err.so.2.1
 18196:20150515:140934.559 7f5aff56e000-7f5aff56f000 rw-p 00003000 fe:00 128768                     /lib/x86_64-linux-gnu/libcom_err.so.2.1
 18196:20150515:140934.559 7f5aff56f000-7f5aff595000 r-xp 00000000 fe:00 9734                       /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
 18196:20150515:140934.559 7f5aff595000-7f5aff795000 ---p 00026000 fe:00 9734                       /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
 18196:20150515:140934.560 7f5aff795000-7f5aff796000 r--p 00026000 fe:00 9734                       /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
 18196:20150515:140934.560 7f5aff796000-7f5aff797000 rw-p 00027000 fe:00 9734                       /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
 18196:20150515:140934.560 7f5aff797000-7f5aff798000 rw-p 00000000 00:00 0
 18196:20150515:140934.560 7f5aff798000-7f5aff861000 r-xp 00000000 fe:00 9746                       /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
 18196:20150515:140934.561 7f5aff861000-7f5affa60000 ---p 000c9000 fe:00 9746                       /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
 18196:20150515:140934.561 7f5affa60000-7f5affa6a000 r--p 000c8000 fe:00 9746                       /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
 18196:20150515:140934.561 7f5affa6a000-7f5affa6c000 rw-p 000d2000 fe:00 9746                       /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
 18196:20150515:140934.561 7f5affa6c000-7f5affa6f000 r-xp 00000000 fe:00 128446                     /lib/x86_64-linux-gnu/libgpg-error.so.0.8.0
 18196:20150515:140934.561 7f5affa6f000-7f5affc6e000 ---p 00003000 fe:00 128446                     /lib/x86_64-linux-gnu/libgpg-error.so.0.8.0
 18196:20150515:140934.561 7f5affc6e000-7f5affc6f000 rw-p 00002000 fe:00 128446                     /lib/x86_64-linux-gnu/libgpg-error.so.0.8.0
 18196:20150515:140934.561 7f5affc6f000-7f5affc80000 r-xp 00000000 fe:00 4769                       /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.0.0
 18196:20150515:140934.561 7f5affc80000-7f5affe7f000 ---p 00011000 fe:00 4769                       /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.0.0
 18196:20150515:140934.561 7f5affe7f000-7f5affe80000 r--p 00010000 fe:00 4769                       /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.0.0
 18196:20150515:140934.561 7f5affe80000-7f5affe81000 rw-p 00011000 fe:00 4769                       /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.0.0
 18196:20150515:140934.561 7f5affe81000-7f5affe91000 r-xp 00000000 fe:00 4779                       /usr/lib/x86_64-linux-gnu/libtasn1.so.3.1.16
 18196:20150515:140934.561 7f5affe91000-7f5b00090000 ---p 00010000 fe:00 4779                       /usr/lib/x86_64-linux-gnu/libtasn1.so.3.1.16
 18196:20150515:140934.561 7f5b00090000-7f5b00091000 r--p 0000f000 fe:00 4779                       /usr/lib/x86_64-linux-gnu/libtasn1.so.3.1.16
 18196:20150515:140934.562 7f5b00091000-7f5b00092000 rw-p 00010000 fe:00 4779                       /usr/lib/x86_64-linux-gnu/libtasn1.so.3.1.16
 18196:20150515:140934.562 7f5b00092000-7f5b000ab000 r-xp 00000000 fe:00 20501                      /usr/lib/x86_64-linux-gnu/librtmp.so.0
 18196:20150515:140934.562 7f5b000ab000-7f5b002ab000 ---p 00019000 fe:00 20501                      /usr/lib/x86_64-linux-gnu/librtmp.so.0
 18196:20150515:140934.562 7f5b002ab000-7f5b002ac000 rw-p 00019000 fe:00 20501                      /usr/lib/x86_64-linux-gnu/librtmp.so.0
 18196:20150515:140934.562 7f5b002ac000-7f5b002c2000 r-xp 00000000 fe:00 128959                     /lib/x86_64-linux-gnu/libz.so.1.2.7
 18196:20150515:140934.562 7f5b002c2000-7f5b004c1000 ---p 00016000 fe:00 128959                     /lib/x86_64-linux-gnu/libz.so.1.2.7
 18196:20150515:140934.562 7f5b004c1000-7f5b004c2000 r--p 00015000 fe:00 128959                     /lib/x86_64-linux-gnu/libz.so.1.2.7
 18196:20150515:140934.562 7f5b004c2000-7f5b004c3000 rw-p 00016000 fe:00 128959                     /lib/x86_64-linux-gnu/libz.so.1.2.7
 18196:20150515:140934.566 7f5b004c3000-7f5b004ff000 r-xp 00000000 fe:00 9752                       /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
 18196:20150515:140934.566 7f5b004ff000-7f5b006ff000 ---p 0003c000 fe:00 9752                       /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
 18196:20150515:140934.566 7f5b006ff000-7f5b00700000 r--p 0003c000 fe:00 9752                       /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
 18196:20150515:140934.566 7f5b00700000-7f5b00702000 rw-p 0003d000 fe:00 9752                       /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
 18196:20150515:140934.566 7f5b00702000-7f5b00729000 r-xp 00000000 fe:00 20516                      /usr/lib/x86_64-linux-gnu/libssh2.so.1.0.1
 18196:20150515:140934.566 7f5b00729000-7f5b00929000 ---p 00027000 fe:00 20516                      /usr/lib/x86_64-linux-gnu/libssh2.so.1.0.1
 18196:20150515:140934.566 7f5b00929000-7f5b0092a000 r--p 00027000 fe:00 20516                      /usr/lib/x86_64-linux-gnu/libssh2.so.1.0.1
 18196:20150515:140934.566 7f5b0092a000-7f5b0092b000 rw-p 00028000 fe:00 20516                      /usr/lib/x86_64-linux-gnu/libssh2.so.1.0.1
 18196:20150515:140934.566 7f5b0092b000-7f5b0095d000 r-xp 00000000 fe:00 4806                       /usr/lib/x86_64-linux-gnu/libidn.so.11.6.8
 18196:20150515:140934.566 7f5b0095d000-7f5b00b5d000 ---p 00032000 fe:00 4806                       /usr/lib/x86_64-linux-gnu/libidn.so.11.6.8
 18196:20150515:140934.566 7f5b00b5d000-7f5b00b5e000 r--p 00032000 fe:00 4806                       /usr/lib/x86_64-linux-gnu/libidn.so.11.6.8
 18196:20150515:140934.567 7f5b00b5e000-7f5b00b5f000 rw-p 00033000 fe:00 4806                       /usr/lib/x86_64-linux-gnu/libidn.so.11.6.8
 18196:20150515:140934.567 7f5b00b5f000-7f5b00b76000 r-xp 00000000 fe:00 128163                     /lib/x86_64-linux-gnu/libpthread-2.13.so
 18196:20150515:140934.567 7f5b00b76000-7f5b00d75000 ---p 00017000 fe:00 128163                     /lib/x86_64-linux-gnu/libpthread-2.13.so
 18196:20150515:140934.567 7f5b00d75000-7f5b00d76000 r--p 00016000 fe:00 128163                     /lib/x86_64-linux-gnu/libpthread-2.13.so
 18196:20150515:140934.567 7f5b00d76000-7f5b00d77000 rw-p 00017000 fe:00 128163                     /lib/x86_64-linux-gnu/libpthread-2.13.so
 18196:20150515:140934.567 7f5b00d77000-7f5b00d7b000 rw-p 00000000 00:00 0
 18196:20150515:140934.567 7f5b00d7b000-7f5b00df5000 r-xp 00000000 fe:00 128545                     /lib/x86_64-linux-gnu/libgcrypt.so.11.7.0
 18196:20150515:140934.567 7f5b00df5000-7f5b00ff5000 ---p 0007a000 fe:00 128545                     /lib/x86_64-linux-gnu/libgcrypt.so.11.7.0
 18196:20150515:140934.567 7f5b00ff5000-7f5b00ff6000 r--p 0007a000 fe:00 128545                     /lib/x86_64-linux-gnu/libgcrypt.so.11.7.0
 18196:20150515:140934.567 7f5b00ff6000-7f5b00ff9000 rw-p 0007b000 fe:00 128545                     /lib/x86_64-linux-gnu/libgcrypt.so.11.7.0
 18196:20150515:140934.567 7f5b00ff9000-7f5b010b2000 r-xp 00000000 fe:00 4803                       /usr/lib/x86_64-linux-gnu/libgnutls.so.26.22.4
 18196:20150515:140934.567 7f5b010b2000-7f5b012b1000 ---p 000b9000 fe:00 4803                       /usr/lib/x86_64-linux-gnu/libgnutls.so.26.22.4
 18196:20150515:140934.567 7f5b012b1000-7f5b012b7000 r--p 000b8000 fe:00 4803                       /usr/lib/x86_64-linux-gnu/libgnutls.so.26.22.4
 18196:20150515:140934.568 7f5b012b7000-7f5b012b9000 rw-p 000be000 fe:00 4803                       /usr/lib/x86_64-linux-gnu/libgnutls.so.26.22.4
 18196:20150515:140934.568 7f5b012b9000-7f5b012d3000 r-xp 00000000 fe:00 9768                       /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
 18196:20150515:140934.568 7f5b012d3000-7f5b014d2000 ---p 0001a000 fe:00 9768                       /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
 18196:20150515:140934.568 7f5b014d2000-7f5b014d3000 r--p 00019000 fe:00 9768                       /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
 18196:20150515:140934.568 7f5b014d3000-7f5b014d4000 rw-p 0001a000 fe:00 9768                       /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
 18196:20150515:140934.568 7f5b014d4000-7f5b01656000 r-xp 00000000 fe:00 128598                     /lib/x86_64-linux-gnu/libc-2.13.so
 18196:20150515:140934.570 7f5b01656000-7f5b01856000 ---p 00182000 fe:00 128598                     /lib/x86_64-linux-gnu/libc-2.13.so
 18196:20150515:140934.570 7f5b01856000-7f5b0185a000 r--p 00182000 fe:00 128598                     /lib/x86_64-linux-gnu/libc-2.13.so
 18196:20150515:140934.570 7f5b0185a000-7f5b0185b000 rw-p 00186000 fe:00 128598                     /lib/x86_64-linux-gnu/libc-2.13.so
 18196:20150515:140934.570 7f5b0185b000-7f5b01860000 rw-p 00000000 00:00 0
 18196:20150515:140934.570 7f5b01860000-7f5b01873000 r-xp 00000000 fe:00 128617                     /lib/x86_64-linux-gnu/libresolv-2.13.so
 18196:20150515:140934.570 7f5b01873000-7f5b01a72000 ---p 00013000 fe:00 128617                     /lib/x86_64-linux-gnu/libresolv-2.13.so
 18196:20150515:140934.570 7f5b01a72000-7f5b01a73000 r--p 00012000 fe:00 128617                     /lib/x86_64-linux-gnu/libresolv-2.13.so
 18196:20150515:140934.570 7f5b01a73000-7f5b01a74000 rw-p 00013000 fe:00 128617                     /lib/x86_64-linux-gnu/libresolv-2.13.so
 18196:20150515:140934.570 7f5b01a74000-7f5b01a76000 rw-p 00000000 00:00 0
 18196:20150515:140934.570 7f5b01a76000-7f5b01a7d000 r-xp 00000000 fe:00 128618                     /lib/x86_64-linux-gnu/librt-2.13.so
 18196:20150515:140934.571 7f5b01a7d000-7f5b01c7c000 ---p 00007000 fe:00 128618                     /lib/x86_64-linux-gnu/librt-2.13.so
 18196:20150515:140934.571 7f5b01c7c000-7f5b01c7d000 r--p 00006000 fe:00 128618                     /lib/x86_64-linux-gnu/librt-2.13.so
 18196:20150515:140934.571 7f5b01c7d000-7f5b01c7e000 rw-p 00007000 fe:00 128618                     /lib/x86_64-linux-gnu/librt-2.13.so
 18196:20150515:140934.571 7f5b01c7e000-7f5b01c80000 r-xp 00000000 fe:00 128604                     /lib/x86_64-linux-gnu/libdl-2.13.so
 18196:20150515:140934.571 7f5b01c80000-7f5b01e80000 ---p 00002000 fe:00 128604                     /lib/x86_64-linux-gnu/libdl-2.13.so
 18196:20150515:140934.571 7f5b01e80000-7f5b01e81000 r--p 00002000 fe:00 128604                     /lib/x86_64-linux-gnu/libdl-2.13.so
 18196:20150515:140934.571 7f5b01e81000-7f5b01e82000 rw-p 00003000 fe:00 128604                     /lib/x86_64-linux-gnu/libdl-2.13.so
 18196:20150515:140934.571 7f5b01e82000-7f5b01f03000 r-xp 00000000 fe:00 128606                     /lib/x86_64-linux-gnu/libm-2.13.so
 18196:20150515:140934.571 7f5b01f03000-7f5b02102000 ---p 00081000 fe:00 128606                     /lib/x86_64-linux-gnu/libm-2.13.so
 18196:20150515:140934.571 7f5b02102000-7f5b02103000 r--p 00080000 fe:00 128606                     /lib/x86_64-linux-gnu/libm-2.13.so
 18196:20150515:140934.571 7f5b02103000-7f5b02104000 rw-p 00081000 fe:00 128606                     /lib/x86_64-linux-gnu/libm-2.13.so
 18196:20150515:140934.571 7f5b02104000-7f5b02165000 r-xp 00000000 fe:00 20537                      /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.2.0
 18196:20150515:140934.571 7f5b02165000-7f5b02364000 ---p 00061000 fe:00 20537                      /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.2.0
 18196:20150515:140934.572 7f5b02364000-7f5b02367000 r--p 00060000 fe:00 20537                      /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.2.0
 18196:20150515:140934.572 7f5b02367000-7f5b02368000 rw-p 00063000 fe:00 20537                      /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.2.0
 18196:20150515:140934.572 7f5b02368000-7f5b02376000 r-xp 00000000 fe:00 9783                       /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2.8.3
 18196:20150515:140934.572 7f5b02376000-7f5b02575000 ---p 0000e000 fe:00 9783                       /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2.8.3
 18196:20150515:140934.572 7f5b02575000-7f5b02576000 r--p 0000d000 fe:00 9783                       /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2.8.3
 18196:20150515:140934.572 7f5b02576000-7f5b02577000 rw-p 0000e000 fe:00 9783                       /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2.8.3
 18196:20150515:140934.572 7f5b02577000-7f5b025c3000 r-xp 00000000 fe:00 9784                       /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2.8.3
 18196:20150515:140934.572 7f5b025c3000-7f5b027c3000 ---p 0004c000 fe:00 9784                       /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2.8.3
 18196:20150515:140934.572 7f5b027c3000-7f5b027c5000 r--p 0004c000 fe:00 9784                       /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2.8.3
 18196:20150515:140934.572 7f5b027c5000-7f5b027c6000 rw-p 0004e000 fe:00 9784                       /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2.8.3
 18196:20150515:140934.572 7f5b027c6000-7f5b027c8000 rw-p 00000000 00:00 0
 18196:20150515:140934.572 7f5b027c8000-7f5b027e8000 r-xp 00000000 fe:00 128592                     /lib/x86_64-linux-gnu/ld-2.13.so
 18196:20150515:140934.572 7f5b029b6000-7f5b029d3000 rw-s 00000000 00:04 2293761                    /SYSV6c006bff (deleted)
 18196:20150515:140934.573 7f5b029d3000-7f5b029df000 rw-p 00000000 00:00 0
 18196:20150515:140934.573 7f5b029e3000-7f5b029e4000 rw-p 00000000 00:00 0
 18196:20150515:140934.573 7f5b029e4000-7f5b029e5000 rw-p 00000000 00:00 0
 18196:20150515:140934.573 7f5b029e5000-7f5b029e7000 rw-p 00000000 00:00 0
 18196:20150515:140934.574 7f5b029e7000-7f5b029e8000 r--p 0001f000 fe:00 128592                     /lib/x86_64-linux-gnu/ld-2.13.so
 18196:20150515:140934.574 7f5b029e8000-7f5b029e9000 rw-p 00020000 fe:00 128592                     /lib/x86_64-linux-gnu/ld-2.13.so
 18196:20150515:140934.574 7f5b029e9000-7f5b029ea000 rw-p 00000000 00:00 0
 18196:20150515:140934.574 7fff7f583000-7fff7f5a4000 rw-p 00000000 00:00 0                          [stack]
 18196:20150515:140934.574 7fff7f5ff000-7fff7f600000 r-xp 00000000 00:00 0                          [vdso]
 18196:20150515:140934.574 ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
 18196:20150515:140934.574 ================================
 18196:20150515:140934.574 Please consider attaching a disassembly listing to your bug report.
 18196:20150515:140934.574 This listing can be produced with, e.g., objdump -DSswx zabbix_agentd.
 18196:20150515:140934.574 ================================
 18188:20150515:140934.575 One child process died (PID:18196,exitcode/signal:1). Exiting ...
zabbix_agentd [18188]: Error on thread waiting.
 18188:20150515:140934.578 Zabbix Agent stopped. Zabbix 2.4.2 (revision 50419).
----------------------------

I've Postgresql 9.1.14. The authentification of the postgres user is good when I tested it with the command-line.
I've grant access on all tables of postgres user.

Thanks,
Maxime

**Comment by cavaliercoder** [comment]
Thanks for logging this issue. This is actually a bug in the 2.4 agent when handling unsupported items loaded from custom modules. The good news is it is already fixed in v2.4.4 :)

Please see: https://support.zabbix.com/browse/ZBX-9218

**Comment by cavaliercoder** [comment]
Added details of the issue to libzbxpgsql documentation under compatibility: http://cavaliercoder.github.io/libzbxpgsql/#compatibility
