### ISSUE TITLE
Problems with the trigger Backend connections are exhausted of the PostgreSQL template

### ISSUE THREAD

**Issue by Fizard** [cavaliercoder/libzbxpgsql#51]
Hi Cavaliercoder,

I have another question, I'm having some problems with the Backend connections are exhausted on {HOST.NAME} trigger. The expression of the trigger is `{Template-PostgreSQL-Linux:pg.prepared_xacts_ratio[{$PG_CONN},{$PG_DB}].last()}<{$PG_BACKENDS_CRIT}` and the default `$PG_BACKENDS_CRIT` is 5. In the item `PostgreSQL Prepared transaction used %` we can see the function `pg.prepared_xacts_ratio[{$PG_CONN},{$PG_DB}]` returns the total of transactions that could be commited as it is described on the description of the item:

> "Returns the **number of transactions that are currently prepared for two phase commit as a percentage of the maximum available** prepared transactions."

 So if the value is 0, there are no transactions prepared for commit. So why the trigger activate if the value is less then 5%? Shouldn't it activate if the value is more then 95% (for an example)? Is this trigger correct, because it's always activating since there is no transaction waiting on the server.

Regards,

Cristiano

**Comment by esawyja** [comment]
I have the same problem on every Postgres DB in my cluster

**Comment by esawyja** [comment]
Any news on this problem, it is driving me nuts

**Comment by cavaliercoder** [comment]
Yeah the trigger is totally incorrect. I'll take a look after work and correct this for everyone. Thanks for submitting this issue.

**Comment by esawyja** [comment]
Thanks so much!

**Comment by Fizard** [comment]
Thank you very much! ;)

**Comment by esawyja** [comment]
Thank you!
