### ISSUE TITLE
Not supported - unknown error

### ISSUE THREAD

**Issue by conexaoinfraestrutura** [cavaliercoder/libzbxpgsql#52]
I have the same problem. I am using two different Postgres servers and a copy of the template for each of them. Each template has its own name and connection data to the database.
On the first server everything is working properly.
However on the second server the template is experiencing the problem that appears in prints.
The only difference is that the second server, access to customer data is being done through a vpn, and the data that the client sends to the server (active check) are directly by the Internet, outside the vpn.
also follow the settings of my zabbix client.
I'm not having problems with passwords, users, or network.

postgres@:~$ /usr/sbin/zabbix_agentd -p | grep '^pg.'
zabbix_agentd [13503]: Starting agent module libzbxpgsql 0.2.1
pg.modver  
pg.connect  
pg.version  
pg.starttime  
pg.uptime  
pg.setting[,,data_directory]  
pg.setting.discovery  
pg.query.string[,,SELECT 'Lorem ipsum dolor';]
pg.query.integer[,,SELECT pg_backend_pid();] 
pg.query.double[,,SELECT CAST(1234 AS double precision);]
pg.query.discovery[,,SELECT \* FROM pg_database;]
pg.backends.count  
pg.queries.longest  
pg.checkpoints_timed  
pg.checkpoints_req  
pg.buffers_clean  
pg.maxwritten_clean  
pg.buffers_backend  
pg.buffers_backend_fsync  
pg.buffers_alloc  
pg.stats_reset  
pg.db.discovery  
pg.namespace.discovery  
pg.schema.discovery  
pg.tablespace.discovery  
pg.table.discovery  
pg.table.children.discovery[,,pg_proc]  
pg.index.discovery  
pg.db.size  
pg.table.size  
pg.table.rows  
pg.table.children[,,pg_database]  
pg.table.children.size[,,pg_database]  
pg.table.children.rows[,,pg_database]  
pg.index.size  
pg.index.rows  
pg.tablespace.size[,,pg_default]  
pg.namespace.size[,,pg_catalog]  
pg.schema.size[,,pg_catalog]  
pg.db.numbackends  
pg.db.xact_commit  
pg.db.xact_rollback  
pg.db.blks_read  
pg.db.blks_hit  
pg.db.tup_returned  
pg.db.tup_fetched  
pg.db.tup_inserted  
pg.db.tup_updated  
pg.db.tup_deleted  
pg.db.conflicts  
pg.db.temp_files  
pg.db.temp_bytes  
pg.db.deadlocks  
pg.db.blk_read_time  
pg.db.blk_write_time  
pg.db.stats_reset[,,postgres,,,]  
pg.table.seq_scan  
pg.table.seq_tup_read  
pg.table.idx_scan  
pg.table.idx_tup_fetch  
pg.table.n_tup_ins  
pg.table.n_tup_upd  
pg.table.n_tup_del  
pg.table.n_tup_hot_upd  
pg.table.n_live_tup  
pg.table.n_dead_tup  
pg.table.last_vacuum[,,pg_database]  
pg.table.last_autovacuum[,,pg_database]  
pg.table.last_analyze[,,pg_database]  
pg.table.last_autoanalyze[,,pg_database]  
pg.table.vacuum_count  
pg.table.autovacuum_count  
pg.table.analyze_count  
pg.table.autoanalyze_count  
pg.table.heap_blks_read  
pg.table.heap_blks_hit  
pg.table.idx_blks_read  
pg.table.idx_blks_hit  
pg.table.toast_blks_read  
pg.table.toast_blks_hit  
pg.table.tidx_blks_read  
pg.table.tidx_blks_hit  
pg.index.idx_scan  
pg.index.idx_tup_read  
pg.index.idx_tup_fetch  
pg.index.idx_blks_read  
pg.index.idx_blks_hit

vim /etc/zabbix/zabbix_agentd.conf
Server=192.168.0.110,192.168.0.254
ServerActive=192.168.0.110,zabbix.xxxxxxxxx.com

root@:~# /etc/init.d/zabbix-agent restart 
- Stopping Zabbix agent zabbix_agentd
  ...done.
- Starting Zabbix agent zabbix_agentd
  ...done.
  
  27678:20160721:084628.597 Zabbix Agent stopped. Zabbix 3.0.0 (revision 58460).
  14334:20160721:084628.642 Starting Zabbix Agent [srvi0019]. Zabbix 3.0.0 (revision 58460).
  14334:20160721:084628.642 ***\* Enabled features ****
  14334:20160721:084628.642 IPv6 support:          YES
  14334:20160721:084628.642 TLS support:           YES
  14334:20160721:084628.642 **************************
  14334:20160721:084628.642 using configuration file: /etc/zabbix/zabbix_agentd.conf
  14334:20160721:084628.642 Starting agent module libzbxpgsql 0.2.1
  14334:20160721:084628.643 agent #0 started [main process]
  14335:20160721:084628.643 agent #1 started [collector]
  14336:20160721:084628.644 agent #2 started [listener #1]
  14340:20160721:084628.644 agent #6 started [active checks #2]
  14339:20160721:084628.644 agent #5 started [active checks #1]
  14338:20160721:084628.646 agent #4 started [listener #3]
  14337:20160721:084628.646 agent #3 started [listener #2]

root@:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty

![screenshot from 2016-07-21 08-50-39](https://cloud.githubusercontent.com/assets/19329445/17022379/0d70ccf0-4f24-11e6-8cc9-d05f23a146ea.png)
![screenshot from 2016-07-21 08-52-16](https://cloud.githubusercontent.com/assets/19329445/17022384/0d7ffafe-4f24-11e6-97d4-b3100df4006b.png)
![screenshot from 2016-07-21 08-52-25](https://cloud.githubusercontent.com/assets/19329445/17022381/0d7ae69a-4f24-11e6-91eb-271192e3aa40.png)
![screenshot from 2016-07-21 08-52-39](https://cloud.githubusercontent.com/assets/19329445/17022382/0d7eee7a-4f24-11e6-9998-df28e848b084.png)
![screenshot from 2016-07-21 08-52-46](https://cloud.githubusercontent.com/assets/19329445/17022383/0d7f8920-4f24-11e6-9283-b48fa396f872.png)

**Comment by cavaliercoder** [comment]
Thank you for posting this issue. To clarify, I understand you are seeing unsupported items appear on your second instance of the template applied to a single host. The error message is 'Unknown error`.

I notice there are no PostgreSQL errors in the agent log file. This might imply that the error is coming from Zabbix. Can you please check the Zabbix configuration first.

Also, you are using an older version of the module and template. Please consider upgrading to version 1.0.0.

**Comment by cavaliercoder** [comment]
Closing with no response from OP.
