### ISSUE TITLE
No such database: template1

### ISSUE THREAD

**Issue by cazorla19** [cavaliercoder/libzbxpgsql#53]
I faced with some module errors trying to connect to database.

My macros configuration of Zabbix-agent:

> {$PG_CONN} => host=pgmanager.com port=6789 user=ubuntu password=mypass
> {$PG_DB} => qa

The first error I get at the Zabbix-agent log:

>    897:20160727:075843.275 PostgreSQL: ERROR:  No such database: template1
>    897:20160727:075843.275 active check "pg.index.discovery[host=pgmanager.com port=6789 user=ubuntu password=mypass]" is not supported
>    897:20160727:075843.281 PostgreSQL: ERROR:  No such database: template1
>    897:20160727:075843.281 active check "pg.table.discovery[host=pgmanager.com port=6789 user=ubuntu password=mypass]" is not supported

The second one I have trying to check I get items with `zabbix_agentd -p | grep '^pg\.'`:

> zabbix_agentd [1221]: Starting agent module libzbxpgsql 1.0.0
> pg.modver  
> zabbix_agentd [1221]: Error: PostgreSQL: FATAL:  role "ubuntu" does not exist
> pg.connect  
> zabbix_agentd [1221]: Error: PostgreSQL: FATAL:  role "ubuntu" does not exist
> pg.version                                    [m|ZBX_NOTSUPPORTED]
> zabbix_agentd [1221]: Error: PostgreSQL: FATAL:  role "ubuntu" does not exist
> pg.starttime                                  [m|ZBX_NOTSUPPORTED]
> zabbix_agentd [1221]: Error: PostgreSQL: FATAL:  role "ubuntu" does not exist

I set especially in my DBMS `ubuntu` role to ignore such stuff. I carelessly can connect to desired database directly by `psql` . But it doesn't work in my configuration. Also I still can't get anything in Zabbix server. What could I do wrong? Is there a clear way to fix it?

**Comment by cavaliercoder** [comment]
Interesting problem. Have you found a way to fix it?

What happens if you run: `zabbix_agentd -t "pg.conn[host=pgmanager.com port=6789 user=ubuntu password=mypass,qa]"`?

**Comment by cavaliercoder** [comment]
You have a malformed key. You missed the `pg.conn` part of the command I asked you to run.
