### ISSUE TITLE
zabbix template does not receive data available from zabbix_get

### ISSUE THREAD

**Issue by teicher** [cavaliercoder/libzbxpgsql#57]
Hello,

I managed to compile and install it all, and quering for data manually on the zabbix server from the remote zabbix agent database server works like:
`zabbix_get -s prod03.xxxxx.net -k "pg.maxwritten_clean[host=prod03 port=5558 user=postgres,postgres]"`

But data never arrives at the zabbix server! Since I copied the key from the "latest data", I think that everything is set up correctly when compared to manual zabbix-get.

![bildschirmfoto 2016-09-01 um 16 16 28](https://cloud.githubusercontent.com/assets/4208890/18170703/8961ff6c-705f-11e6-8940-ed456064abfd.png)

There are no errors whatsoever, how could I debug this ?

Since even `pg.modver` is not available, it's probably not related to `PG_CONN` settings...

See #58, maybe the template at https://raw.githubusercontent.com/cavaliercoder/libzbxpgsql/v1_template/template_postgresql_server.xml is somehow not compatible with version 1.0.0 for zabbix2 ?

**Comment by teicher** [comment]
Ok, answering my own question here.
Problem is that the templates creates the items as "Zabbix agent (active)".
If you do not have active agentd but only standard zabbix agent,
all template Items must be changed from "Zabbix agent (active)" to "Zabbix agent".

**Comment by cavaliercoder** [comment]
Thank you for posting your solution @teicher. I'm glad you were able to make use of this template.
