### ISSUE TITLE
doc problems

### ISSUE THREAD

**Issue by teicher** [cavaliercoder/libzbxpgsql#58]
* template for import into zabbix 2 is no longer available (must find it in tag in github - used https://raw.githubusercontent.com/cavaliercoder/libzbxpgsql/v1_template/template_postgresql_server.xml )
* Documentation link in footer does not link to documentation (http://cavaliercoder.com/libzbxpgsql/ - and image broken)
* 3rd link on http://cavaliercoder.com/libzbxpgsql/documentation/installation/ broken

**Comment by cavaliercoder** [comment]
Thank you for raising these issues. Unfortunately I broke template compatibility when the module compatibility broken in Zabbix v3. I'll raise a separate issue for this and get to work on it.
