### ISSUE TITLE
Monitoring postgress on a server but keeps asking for a zabbix BD - 

### ISSUE THREAD

**Issue by christopherwelsh** [cavaliercoder/libzbxpgsql#59]
Centos 6.7
Postgress 9.3
system.hostname                               [s|pmc-testlims.petermac.org.au]
pg.modver                                     [s|libzbxpgsql 1.0.0, compiled for Zabbix 3.0.2]
pg.connect                                    [u|0]

Hi I have an application server that has postgres and zabix finds all the normal OS, CPU , etc metrics but not the postgres stuff. I'm missing something real simple here. 

I can login to postgres on this server as the user zabbix and the agent loads the module. 

ie. 
[root@pmc-testlims zabbix]# sudo -u zabbix psql clarityDB
psql (9.3.12)
Type "help" for help.
clarityDB=> 

ie. 
[root@pmc-testlims zabbix]# cat /var/log/zabbix/zabbix_agentd.log
 21435:20160905:140100.044 Got signal [signal:15(SIGTERM),sender_pid:6088,sender_uid:0,reason:0]. Exiting ...
 21435:20160905:140100.137 Zabbix Agent stopped. Zabbix 3.0.4 (revision 61185).
  6108:20160905:040101.209 Starting Zabbix Agent [Zabbix server]. Zabbix 3.0.4 (revision 61185).
  6108:20160905:040101.210 **** Enabled features ****
  6108:20160905:040101.210 IPv6 support:          YES
  6108:20160905:040101.210 TLS support:           YES
  6108:20160905:040101.210 **************************
  6108:20160905:040101.210 using configuration file: /etc/zabbix/zabbix_agentd.conf
  6108:20160905:040101.213 Starting agent module libzbxpgsql 1.0.0
  6108:20160905:040101.213 loaded modules: libzbxpgsql.so
  6108:20160905:040101.213 agent #0 started [main process]
  6114:20160905:040101.214 agent #5 started [active checks #1]
  6112:20160905:040101.216 agent #3 started [listener #2]
  6113:20160905:040101.216 agent #4 started [listener #3]
  6111:20160905:040101.218 agent #2 started [listener #1]
  6110:20160905:040101.221 agent #1 started [collector]

But get postgres  errors saying i have no zabbix database. I do have the zabix DB on the zabbix server and did not expect to need one installed on each server that  runs postgres that i want to monitor. 

 when I run: zabbix_agent -p

(stuff deleted)

pg.modver                                     [s|libzbxpgsql 1.0.0, compiled for Zabbix 3.0.2]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.connect                                    [u|0]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.version                                    [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.starttime                                  [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.uptime                                     [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.prepared_xacts_count                       [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.prepared_xacts_ratio                       [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.prepared_xacts_age                         [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.setting[,,data_directory]                  [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.setting.discovery                          [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.query.string[,,SELECT 'Lorem ipsum dolor';] [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.query.integer[,,SELECT pg_backend_pid();]  [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.query.double[,,SELECT CAST(1234 AS double precision);] [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.query.discovery[,,SELECT * FROM pg_database;] [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.backends.count                             [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.backends.free                              [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.backends.ratio                             [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.queries.longest                            [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.checkpoints_timed                          [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.checkpoints_req                            [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.checkpoint_write_time                      [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.checkpoint_sync_time                       [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.checkpoint_avg_interval                    [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.checkpoint_time_ratio                      [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.buffers_checkpoint                         [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.buffers_clean                              [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.maxwritten_clean                           [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.buffers_backend                            [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.buffers_backend_fsync                      [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.buffers_alloc                              [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.stats_reset                                [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.stats_reset_interval                       [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.db.discovery                               [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.namespace.discovery                        [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.schema.discovery                           [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.tablespace.discovery                       [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.discovery                            [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.children.discovery[,,pg_proc]        [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.index.discovery                            [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.db.size                                    [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.size                                 [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.rows                                 [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.children[,,pg_database]              [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.children.size[,,pg_database]         [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.children.rows[,,pg_database]         [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.index.size                                 [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.index.rows                                 [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.tablespace.size[,,pg_default]              [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.namespace.size[,,pg_catalog]               [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.schema.size[,,pg_catalog]                  [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.db.numbackends                             [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.db.xact_commit                             [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.db.xact_rollback                           [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.db.blks_read                               [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.db.blks_hit                                [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.db.blks_ratio                              [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.db.tup_returned                            [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.db.tup_fetched                             [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.db.tup_inserted                            [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.db.tup_updated                             [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.db.tup_deleted                             [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.db.conflicts                               [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.db.temp_files                              [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.db.temp_bytes                              [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.db.deadlocks                               [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.db.blk_read_time                           [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.db.blk_write_time                          [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.db.stats_reset[,,postgres,,,]              [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.db.xid_age                                 [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.seq_scan                             [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.seq_tup_read                         [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.idx_scan                             [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.idx_scan_ratio                       [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.idx_tup_fetch                        [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.n_tup_ins                            [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.n_tup_upd                            [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.n_tup_del                            [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.n_tup_hot_upd                        [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.n_live_tup                           [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.n_dead_tup                           [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.n_mod_since_analyze                  [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.last_vacuum[,,pg_database]           [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.last_autovacuum[,,pg_database]       [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.last_analyze[,,pg_database]          [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.last_autoanalyze[,,pg_database]      [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.vacuum_count                         [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.autovacuum_count                     [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.analyze_count                        [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.autoanalyze_count                    [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.heap_blks_read                       [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.heap_blks_hit                        [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.heap_blks_ratio                      [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.idx_blks_read                        [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.idx_blks_hit                         [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.idx_blks_ratio                       [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.toast_blks_read                      [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.toast_blks_hit                       [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.toast_blks_ratio                     [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.tidx_blks_read                       [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.tidx_blks_hit                        [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.table.tidx_blks_ratio                      [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.index.idx_scan                             [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.index.idx_tup_read                         [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.index.idx_tup_fetch                        [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.index.idx_blks_read                        [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.index.idx_blks_hit                         [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
zabbix_agentd [13628]: Error: PostgreSQL: FATAL:  database "zabbix" does not exist

pg.index.idx_blks_ratio                       [m|ZBX_NOTSUPPORTED] [FATAL:  database "zabbix" does not exist
]
systemd.unit.is-active                        [t|sh: systemctl: command not found

**Comment by cavaliercoder** [comment]
By default, the PostgreSQL client attempts to connect to a database with same name as your user name. It seems your database name `claritydb` and connection user name `zabbix` do not match. You need to specify `claritydb` as the connection database, in the second parameter of all of your PostgreSQL keys. For convenience, you can simply override the `{#PGDATABASE}` macro provided in the template.

Please see: http://cavaliercoder.com/libzbxpgsql/documentation/connecting-to-postgresql/
