### ISSUE TITLE
Wrong "Requires" in RPM specfile

### ISSUE THREAD

**Issue by uosiu** [cavaliercoder/libzbxpgsql#6]
RPM with zabbix-agent in RHEL-like systems is named zabbix22-agent.

**Comment by cavaliercoder** [comment]
All the zabbix repos I checks named the agent 'zabbix-agent'. Can you please give more detail on the issue?

**Comment by cavaliercoder** [comment]
I'm closing this issue as I haven't heard from you and the latest release is confirmed to work with Zabbix 2.2 and 2.4 on CentOS 5, 6 and 7.
