### ISSUE TITLE
Template version compatibility

### ISSUE THREAD

**Issue by cavaliercoder** [cavaliercoder/libzbxpgsql#61]
The template is maintained in the Zabbix version 3 but is not compatible with older versions of Zabbix. Need to generate multiple templates for each Zabbix version.

Also need a way to publish URLs for the latest stable version of the templates.

**Comment by ssoriche** [comment]
Is there a version of the template that works with Zabbix version 2.2? Attempting a first time install, and it is failing with `Unknown import version.`

**Comment by cavaliercoder** [comment]
Please try these: https://github.com/cavaliercoder/libzbxpgsql/tree/master/templates

It would be very helpful if you could please reply if these work for you.

**Comment by ssoriche** [comment]
Thank you! I used the 2.0 template and it imported without error.

**Comment by aabudari** [comment]
I tried all versions of templates, they show errors on import as the following: 
![image](https://cloud.githubusercontent.com/assets/8500454/19604541/8ad2fd6a-976a-11e6-9f9d-524fd22f4912.png)

I'm running Zabbix server v2.4.3 (revision 51175) (15 December 2014)

**Comment by aabudari** [comment]
It is working now, I copied and pasted the content of XML instead of Save As. My bad
