### ISSUE TITLE
libzbxpgsql on Zabbix official Docker image - cannot get it work

### ISSUE THREAD

**Issue by marisveide** [cavaliercoder/libzbxpgsql#63]
## Docker context:
I am using Docker image: "zabbix/zabbix-server-pgsql:ubuntu-latest", which is based on "ubuntu:trusty". 
This one: https://hub.docker.com/r/zabbix/zabbix-server-pgsql/

## 1. If I install the libzbxpgsql version Ubuntu Trusty (amd64) for Zabbix v3.2+
(as described here http://cavaliercoder.com/libzbxpgsql/download/)
with the following Dockerfile commands:
```bash
RUN cd /tmp && \
   wget http://s3.cavaliercoder.com/libzbxpgsql/apt/zabbix32/ubuntu/trusty/amd64/libzbxpgsql_1.0.0-1%2Btrusty_amd64.deb && \
   sudo dpkg -i libzbxpgsql*.deb && \
   rm libzbxpgsql*.deb
RUN printf "LoadModulePath=/usr/lib/zabbix/modules\n\
LoadModule=libzbxpgsql.so\n" >> /etc/zabbix/zabbix_agentd.conf
RUN service zabbix-agent restart
```

I get following result:
```bash
$ zabbix_agentd -t pg.modver
zabbix_agentd [460]: ERROR: unsupported module "libzbxpgsql.so" version: 2
zabbix_agentd [460]: ERROR: loading modules failed, exiting...
```

----

## 2. If I install the libzbxpgsql version Ubuntu Trusty (amd64) for Zabbix v3.0+
(as described here http://cavaliercoder.com/libzbxpgsql/download/)
with the following Dockerfile commands:
```bash
RUN cd /tmp && \
   wget http://s3.cavaliercoder.com/libzbxpgsql/apt/zabbix3/ubuntu/trusty/amd64/libzbxpgsql_1.0.0-1%2Btrusty_amd64.deb && \
   sudo dpkg -i libzbxpgsql*.deb && \
   rm libzbxpgsql*.deb
RUN printf "LoadModulePath=/usr/lib/zabbix/modules\n\
LoadModule=libzbxpgsql.so\n" >> /etc/zabbix/zabbix_agentd.conf
RUN service zabbix-agent restart
```

I get following result:
```bash
$ zabbix_agentd -t pg.modver
zabbix_agentd [278]: Starting agent module libzbxpgsql 1.0.0
pg.modver
$ zabbix_get -s 127.0.0.1 -k "pg.connect[host=db-url-to-aws.eu-west-1.rds.amazonaws.com port=5432 user=monitoring password=*********** connect_timeout=10,db-name]"
# (silence, nothing - not to stdout not in zabbix agent log).
$ zabbix_get -s 127.0.0.1 -k "pg.connect[host=db-url-to-aws.eu-west-1.rds.amazonaws.com port=5432 user=monitoring_WRONG_ONE password=*********** connect_timeout=10,db-name]"
$ tail -f /var/log/zabbix-agent/zabbix_agentd.log 
219:20160923:113019.253 PostgreSQL: FATAL:  password authentication failed for user "monitoring_WRONG_ONE"
FATAL:  password authentication failed for user "monitoring_WRONG_ONE"
```

Which makes me conclude that it CAN connect the real database, because there is a silence on the correct connection string, and error on incorrect user.

Now, if I run this:
```bash
$ zabbix_agentd -p
# ...
pg.index.idx_blks_hit                         [m|ZBX_NOTSUPPORTED]
zabbix_agentd [304]: Error: PostgreSQL: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

I get this error for each pg.* metric.
Which tells me that it doesn't even try to connect to remote database, it tries to connect to local one, which off course doesn't exist.

In Zabbix Web console I have all the PostgreSQL Template loaded, and Macros configured as shown in documentation.

And in Zabbix Web console I see that it is not getting any data from the DB Host. 
Latest Data is empty for this host.

DB Host is configured like this:
<img width="1005" alt="screen shot 2016-09-23 at 14 35 30" src="https://cloud.githubusercontent.com/assets/17713131/18784601/e5aa1cf8-819b-11e6-8ea7-f133569cc478.png">
<img width="944" alt="screen shot 2016-09-23 at 14 36 01" src="https://cloud.githubusercontent.com/assets/17713131/18784602/e5d5680e-819b-11e6-82f8-900c786e78cf.png">

## One more try:
Template is using Zabbix Agent (active) to run checks for PostgreSQL.
I have changed one check to use "Zabbix Agent" (not active) - and got the error for that check visible in UI: "Not supported by Zabbix Agent"

So, I am out of ideas, what else I could try to make this work...
Can you suggest something?

**Comment by cavaliercoder** [comment]
There's a few different issues raised here. Please raise separate issues for separate problems.

Before raising any other issues, please take note of the following:

* The docker image you described, `zabbix/zabbix-server-pgsql` is based on Alpine linux, not Ubuntu and does not include the Zabbix agent. I would not expect it to work with my module.
* The `ERROR: unsupported module "libzbxpgsql.so" version: 2` means you are not running v3.2.0 agent which expects module API v2. Previous versions expect v1.
* The authentication errors you are seeing are quite simply bad password issues
* You need to check that the module is loaded correctly in the zabbix agent for active or passive items to work. Try get the keys working via `zabbix_get` on the Zabbix server before botheirng to configure templates.

**Comment by marisveide** [comment]
1. Docker image by Zabbix have also Ubuntu, see here: https://hub.docker.com/r/zabbix/zabbix-server-pgsql/builds/
Please, read carefully, notice the Docker image tag which I wrote: "zabbix/zabbix-server-pgsql:ubuntu-latest".

2. About unsupported version: 2 - that same error is regardless, if I have Zabbix server 3.0 or 3.2 - I have tried with both.

3. About password - please, read carefully, you will understand what I meant by that. There is one test with successful password, which seems ok, and the other with wrong password, to demonstrate that it connects to the right DB.

4. Also, if you read my report, you will notice that zabbix_get sort of works - but I don't know if it should return nothing when successful, or it should return something?
Currently it returns nothing, if connection succeeds.
Then maybe this is the real problem?
Should it return something? And what could be the problem, why it doesn't?

**Comment by cavaliercoder** [comment]
Let's start by tackling the version issues. I think (much like we discovered in #62) that you are running the v2 agent. I had a look at the `zabbix/zabbix-server-pgsql:ubuntu-latest` images and it has no agent, so I assume you installed yourself.

If you use the libzbxpgsql package that was compiled for Zabbix v3.2 on a v2 agent, it will fail with `ERROR: unsupported module "libzbxpgsql.so" version: 2` as the API version was incremented in v3.2.0.

If you use the libzbxpgsql package that was compiled for Zabbix v3.0 on a v2 agent, it will load, but all get queries will return null, as you saw with the blank output for `zabbix_get`.

Please see [the Zabbix documentation](https://www.zabbix.com/documentation/3.2/manual/installation/install_from_packages) for tips on installing the latest agent versions from the apt repo.

You are correct that `zabbix_agentd -p` defaults to connecting to a local database that in your case does not exist. This default is in accordance with the PostgreSQL client defaults. In your case, using `zabbix_get` with connection parameters is more appropriate.

Installing the v3.2.0 agent with the libzbxpgsql package for v3.2.0 should hopefully solve your issues.

**Comment by marisveide** [comment]
Superb, @cavaliercoder!
You helped me!
Really, the issue was with zabbix_agent and zabbix_get versions, which were too old.

I have now installed zabbix-agent and zabbix-get .deb packages directly with dpkg (avoiding apt-get) from here: http://repo.zabbix.com/zabbix/3.2/ubuntu/pool/main/z/zabbix/

Now, when I run:
```bash
$ zabbix_get -s 127.0.0.1 -k "pg.connect[host=db-url-to-aws.eu-west-1.rds.amazonaws.com port=5432 user=monitoring password=*********** connect_timeout=10,db-name]"
1
```
It returns "1" - great success!

But Zabbix Web console still shows no data.
I disabled and enabled host - still no data.
What could be here the issue?

Thanks a lot!

**Comment by cavaliercoder** [comment]
Great! Glad I can help.

If the items have become unsupported in Zabbix, they won't be polled again until the unsupported poller refreshes. You can force an immediate update by restarted the zabbix server, waiting for configuration to load and then restart the zabbix agent.

If that fails, please take a look in the logs on both server and agent and advise.

**Comment by marisveide** [comment]
OK, I have the value in Zabbix Web Console, if I change the agent to "Zabbix Agent".
If I have "Zabbix Agent (active)", then there are still no values.
Should it be working also with Active checks?

**Comment by cavaliercoder** [comment]
Definitely should work with active items but there are a few configuration replication delays that might cause the data to take a while to appear. The following need to happen:
* zabbix server needs to refresh configuration from the database (usually 2 mins)
* zabbix agent needs to refresh active configuration from the server (usually 1 hour)

You'll need to watch the logs to make sure active check configuration is propagating correctly.

**Comment by marisveide** [comment]
Thank you for the great help!
I managed to have everything working - except Active checks.

### zabbix_agentd.log shows the following:

>    463:20160923:190644.287 active check configuration update from [127.0.0.1:10051] started to fail (ZBX_TCP_READ() timed out)
>    463:20160923:190744.310 active check configuration update from [127.0.0.1:10051] is working again
>    462:20160923:191202.439 PostgreSQL: could not translate host name "correct-db-host.eu-west-1.rds.amazonaws.com" to address: Name or service not known

Looks like it doesn't resolve the DNS.

When trying to connect to this host from psql - everything works.
