### ISSUE TITLE
don`t make

### ISSUE THREAD

**Issue by sshadkov** [cavaliercoder/libzbxpgsql#64]
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..    -I/home/admin/zabbix-3.2.1/include -I/usr/pgsql-9.4/include -L/usr/pgsql-9.4/lib -lpq -g -O2 -MT libzbxpgsql_la-pg_bgwriter.lo -MD -MP -MF .deps/libzbxpgsql_la-pg_bgwriter.Tpo -c -o libzbxpgsql_la-pg_bgwriter.lo `test -f 'pg_bgwriter.c' || echo './'`pg_bgwriter.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I/home/admin/zabbix-3.2.1/include -I/usr/pgsql-9.4/include -L/usr/pgsql-9.4/lib -lpq -g -O2 -MT libzbxpgsql_la-pg_bgwriter.lo -MD -MP -MF .deps/libzbxpgsql_la-pg_bgwriter.Tpo -c pg_bgwriter.c  -fPIC -DPIC -o .libs/libzbxpgsql_la-pg_bgwriter.o
pg_bgwriter.c: In function ‘PG_STAT_BGWRITER’:
pg_bgwriter.c:49: error: expected ‘)’ before ‘pgsql_bgwriter_stat’
pg_bgwriter.c: In function ‘PG_BG_TIME_RATIO’:
pg_bgwriter.c:167: error: expected ‘)’ before ‘pgsql_bg_time_ratio’
make[2]: *** [libzbxpgsql_la-pg_bgwriter.lo] Error 1
make[2]: Leaving directory `/home/admin/libzbxpgsql-master/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/admin/libzbxpgsql-master'
make: *** [all] Error 2

**Comment by cavaliercoder** [comment]
More info please. Which sources are you using? What version of Zabbix, etc. etc.

**Comment by sshadkov** [comment]
2.6.32-642.3.1.el6.centos.plus.x86_64
Zabbix 3.2.1

**Comment by cavaliercoder** [comment]
Ah I see. Please note, the master branch is not stable is likely not to build between releases. Please checkout the v1.0.0 tag and try again, or download the released tarball from the [downloads page](http://cavaliercoder.com/libzbxpgsql/download/).

**Comment by sshadkov** [comment]
to release 1.0.0 the same error

2016-10-03 17:17 GMT+03:00 Ryan Armstrong <notifications@github.com>:

**Comment by zykat** [comment]
I have the same error compiling from Source package v.1.0.0 on FreeBSD-9.2 with Zabbix 3.2.1

libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I/usr/home/test/zabbix-3.2.1/include/ -I/usr/local/include -L/usr/local/lib -lpq -g -O2 -MT libzbxpgsql_la-pg_bgwriter.lo -MD -MP -MF .deps/libzbxpgsql_la-pg_bgwriter.Tpo -c pg_bgwriter.c  -fPIC -DPIC -o .libs/libzbxpgsql_la-pg_bgwriter.o
In file included from pg_bgwriter.c:20:
libzbxpgsql.h:158:7: warning: no newline at end of file
pg_bgwriter.c: In function 'PG_STAT_BGWRITER':
pg_bgwriter.c:49: error: expected ')' before 'pgsql_bgwriter_stat'
pg_bgwriter.c: In function 'PG_BG_TIME_RATIO':
pg_bgwriter.c:167: error: expected ')' before 'pgsql_bg_time_ratio'
*** [libzbxpgsql_la-pg_bgwriter.lo] Error code 1

Stop in /usr/home/test/libzbxpgsql-1.0.0/src.
*** [all-recursive] Error code 1
