### ISSUE TITLE
CentOS 5.3 - Zabbix Agent 2.0.7 is not loading /usr/local/lib/libzbxpgsql.so

### ISSUE THREAD

**Issue by aabudari** [cavaliercoder/libzbxpgsql#67]
Hi, 
Would anybody be able to help assist in the issue below: 
I have zabbix agent 2.0.7 running on CentOS 5.3. there is no rpm packages for CentOS 5, SO I compiled the source code. The compilation was successful, however, I could not get Zabbix Agent to load the libzbxpgsql.so module. Below is the test result: 
/opt/zabbix/sbin/zabbix_agentd -t pg.modver
pg.modver                                     [m|ZBX_NOTSUPPORTED]

**Comment by cavaliercoder** [comment]
Does the module appear to load in the agent log file? There's a chance you've place the module in the wrong directory or haven't loaded it in the agent configuration.

Please see the [installation docs](http://cavaliercoder.com/libzbxpgsql/documentation/module-installation/#install-from-source) but note that the default directories have changed a lot in recent Zabbix versions.
