### ISSUE TITLE
Item key pg.db.blks_perc is not supported

### ISSUE THREAD

**Issue by cleitondomazak** [cavaliercoder/libzbxpgsql#69]
I have CentOS 7 x64 + zabbix_agent 3.2 + PostgreSQL 9.4 + , and all itens key of prototype `Discover PostgreSQL Databases` works fine, but I realized that the key pg.db.blks_perc doesn't work.

In zabbix_agent.log and on terminal the msg is the same
 `zabbix_agentd [12894]: Starting agent module libzbxpgsql 1.0.0
pg.db.blks_perc[host=192.168.2.112 port=5432 user=postgres password=111111,postgres,postgres] [m|ZBX_NOTSUPPORTED] [Unsupported item key.]`

**Comment by cavaliercoder** [comment]
Thanks for posting this. Some keys were mislabelled `*_perc` but I don't recall ever releasing these bad versions. They should all now be named `*_ratio` (e.g. `pg.db.blks_ratio`). Where did you get the template from?

Please use the template version bundled with your installation or source package. Alternatively, the v1 template is [here](https://raw.githubusercontent.com/cavaliercoder/libzbxpgsql/v1.0.0/template_postgresql_server.xml). Note that v1.1 will shortly be released.

**Comment by conexaoinfraestrutura** [comment]
Same thing:
zabbix_get -s 11.0.0.52 -k pg.db.blks_perc["user=postgres host=127.0.0.1 port=5432","postgres"]
ZBX_NOTSUPPORTED: Unsupported item key.

zabbix_get -s 11.0.0.52 -k pg.db.blks_ratio["user=postgres host=127.0.0.1 port=5432","postgres"]
ZBX_NOTSUPPORTED: Unsupported item key.

I maked my own template and the information about this item i caught from de official project website

http://cavaliercoder.com/libzbxpgsql/documentation/reference/databases/#pg-db-blks-perc

Also i have big problems with of the ubuntu package libzbx. In the ubuntu i had to install debian version to do libzbx goes to work fine

dpkg -l | grep libzbx
ii  libzbxpgsql                               1.1.0-1                                             amd64        PostgreSQL monitoring module for Zabbix

dpkg -l | grep zabbix
ii  zabbix-agent                              1:2.4.8-1+trusty                                    amd64        network monitoring solution - agent
ii  zabbix-release                            2.4-1+trusty                                        all          Zabbix official repository configuration

if you need more information about my enviroment please reply me.
