### ISSUE TITLE
Documentation typos

### ISSUE THREAD

**Issue by tiyab** [cavaliercoder/libzbxpgsql#72]
Great documentation! so that is why I telling you about these typos below:
for [Module installation](http://cavaliercoder.com/libzbxpgsql/documentation/module-installation/)
you are saying:
> If the module is loaded correctly, you will see the following line in your Zabbix agent log file (/var/log/zabbix/zabbix_agentd.conf):

it should be **/var/log/zabbix/zabbix_agentd.log**

for [Local monitoring agent](http://cavaliercoder.com/libzbxpgsql/documentation/local-monitoring-agent/)
you are saying:
> Allow the Zabbix agent identity (typically zabbix or root) to connect as the monitoring role by adding the following to your pg_indent.conf:

I think the file should be **pg_ident.conf**

**Comment by cavaliercoder** [comment]
Many thanks
