### ISSUE TITLE
SQL Query cut short when attempting to filter out results from another column of same table

### ISSUE THREAD

**Issue by Wicaeed** [cavaliercoder/libzbxpgsql#76]
Greetings,

I ran into the following issue when trying to run a query like this:

`zabbix@zabbic~$ zabbix_get -s zabbixserver -p 10050 -k pg.query.string["{$PG_CONN},{$PG_DB},"select count(*) from table where column = "some value" and anothercolumn NOT IN ('val1', 'val2')"`

```
ZBX_NOTSUPPORTED: PostgreSQL error for query "select count(*) from table WHERE column = 'some value' and anothercolumn NOT IN ('val1'" : ERROR:  syntax error at end of input
LINE 1: ... table WHERE column = 'some value' and anothercolumn NOT IN ('val1'^
````

I can run the query fine from within the psql client:

```
database=> select count(*) from table where column = "some value" and anothercolumn NOT IN ('val1', 'val2');
count
----
40
(1 row)

```

Is there some sort of special escaping that needs to take place?

The table in question is also type text, if you're wondering why the pg.query.string key...

**Comment by robbrucks** [comment]
It could be one of several issues, since you aren't showing us the actual command or your variable settings.

1. The maximum length of a Zabbix key is 255 bytes.  If you are exceeding this length then the key, and your SQL, will get truncated.
2. I don't see a semi-colon at the end of your example SQL statement in the key. It is required.
3. Your replacement variables aren't getting replaced ( {$PG_CONN},  {$PG_DB} ).  Command line variable replacement doesn't work the same as in the Zabbix UI.  You probably need to supply actual values for the replacement variables.
4. You have lots of double quotes, some of them look like SQL syntax errors. Double quotes behave differently in a shell environment. Embedded double quotes will need to be escaped.

You should first try a simple query test, something like this:
```
zabbix_get -s zabbixserver -p 10050 -k pg.query.string["port=5432 user=myuser",postgres,"select 'hello';"]
```
If you get back a "hello" string, then you can begin building on that.

**Note:**
You can get around the 1st problem by using libzbxpgsql v1.1 and putting your query in the libzbxpgsql.conf file like this:
```
queries = {
myquery = "select count(*) from table where column = 'some value' and anothercolumn NOT IN ('val1', 'val2');";
}
```
Then bounce the zabbix-agent and change the key to this:
```
pg.query.string["port=5432 user=myuser",postgres,myquery]
```

**Comment by Wicaeed** [comment]
Thanks for the tips!

After a bit of troubleshooting I was able to work out that the `,` in the NOT IN statement is causing the query to barf.

When I write the query as such it works fine:
```
zabbix@zabbix~$ zabbix_get -s zabbixserver -p 10050 -k pg.query.string["host=mydb port=5432",mydb,"select count(*) from table where column = some value' and anothercolumn <> 'val1' and anothercolumn <> 'val2';"
19
```

Definitally the comma since if I move it around the error message breaks at the location of the comma:
```
zabbix@zabbix~$ zabbix_get -s zabbixserver -p 10050 -k pg.query.string["host=mydb port=5432",mydb,"select count(*),1 from table where column = some value' and anothercolumn <> 'val1' and anothercolumn <> 'val2';"
ZBX_NOTSUPPORTED: PostgreSQL error for query "select count(*)": ERROR:  bind message supplies 2 parameters, but prepared statement "" requires 0
```

**Comment by robbrucks** [comment]
You have definitely found a bug.  I was able to reproduce it too.

@cavaliercoder there appears to be a bug with SQL containing a comma when the SQL is embedded in the Zabbix key.

**Comment by robbrucks** [comment]
@Wicaeed you can get around this by using the libzbxpgsql.conf file to store the query, then reference the query by name in your key (from my "Note" in my first post). I tested it and it accepts commas without a problem using that method.

**Comment by Wicaeed** [comment]
Thanks!

How can I store multiple queries?

Would it be like so?

```
queries = {
myquery = <sql>
myquery2 = <sql>
}
```

**Comment by robbrucks** [comment]
Yes, exactly like that. Double quotes are required around everything, and if you decide to use multiple lines for the SQL it will just concatenate them together, so be sure to include a blanks as needed.  And both the SQL and config file require semicolons as terminators, so you'll need two. One inside the quotes and one outside.
```
myquery = "select count(*) "
                  "from my_table "
                 "where col2 = true "
                 "order by rolname "
                ";";

myotherquery = "select whatever from sometable where somecol in ('val1','val2');";

thisworkstoo = "select mycol
                  from table
                 where col2 = 'xx';";
```

**Comment by Wicaeed** [comment]
Hmm, I appear to be having issues when using a period in the query name (so something like `pg.customname.queryname`)

Periods aren't mentioned as one of the disallowed characters in the libzbxpgsql.conf Readme, however. 

This seems to be a departure from regular Zabbix key naming conventions, am I doing something wrong or is that expected behavior?

**Comment by cavaliercoder** [comment]
@Wicaeed I think you are using the wrong agent key. The key should be one of the [pg.query.*](http://cavaliercoder.com/libzbxpgsql/documentation/reference/queries/) keys. For example, if your query is named `customname` and returns a single scalar string:
```
pg.query.string[customname]
```

**Comment by cavaliercoder** [comment]
Re: commas. The Zabbix key parser uses commas to delimit key parameters, so when you include them in your query, Zabbix sees this as the end of the query and the start of the query parameters. You can solve this by [placing the query in quotes](http://cavaliercoder.com/libzbxpgsql/documentation/reference/queries/), but when building an agent key on the command line, you have three layers of parsing and char escaping going on:
* the shell interpreter
* the agent key parser
* the query parser

Seems unwieldily! I prefer @robbrucks solution; using a named query in the config file.
