### ISSUE TITLE
Parameter {$PG_CONN} doesn't accept spaces between options

### ISSUE THREAD

**Issue by paulor1c4rd0** [cavaliercoder/libzbxpgsql#80]
Hello! First off all, congratulations for your software!

But i'm trying to connect to the agent on my DB, but when i try to test the item with zabbix-get i had some issues.

on the first parameters of the keys, correspondent to {$PG_CONN} macro, if i set only one option its ok, but if i try to set more than one option the message "invalid parameter". Below is one example:

With one option:
```
# zabbix_get -s 192.168.56.102 -p 10050 -k pg.connect[hostaddr=192.168.56.102,zabbix]
0
```

With two or more options:
```
# zabbix_get -s 192.168.56.102 -p 10050 -k pg.connect[hostaddr=192.168.56.102 user=zabbixuser,zabbix]
zabbix_get [7835]: invalid parameter "user=zabbixuser,zabbix]"
Try 'zabbix_get --help' for more information.
```
Any idea for resolve this?
Thanks for all help!!! (Sorry for any english errors)

**Comment by paulor1c4rd0** [comment]
Hello there! I put the connect string between '' and it worked!
Thanks

**Comment by cavaliercoder** [comment]
Thanks for posting your issues and the solution.
You are correct, that your connection string needed to be in quotes, otherwise your shell interpreter sees two space separated arguments, instead of one.
