### ISSUE TITLE
Template import problems.

### ISSUE THREAD

**Issue by rogerpousada** [cavaliercoder/libzbxpgsql#81]
My Zabbix-Server is 2.2.16 (will update soon!)
**I received an error "XML file contains fatal error 41:Specification mandate value for attribute data-pjax-transient [ Line: 29 | Column: 40 ]"**

This is a 2.2 supported? I used the 2.0 template.

Tnx

**Comment by cavaliercoder** [comment]
Yes, 2.2 is tested and supported using the 2.0 template. Can you offer any additional information to replicate this issue? Maybe the PHP and XML module version? Anything else?

**Comment by cavaliercoder** [comment]
As per https://github.com/blacked/zbx_nginx_template/issues/4, please make sure you download the 'Raw' version of the XML document from GitHub or clone the repo. Don't use 'Save As'. Saving the document from the browser will save it as HTML, not XML.
