### ISSUE TITLE
undefined symbol: zbx_module_history_write_cbs

### ISSUE THREAD

**Issue by cavaliercoder** [cavaliercoder/libzbxpgsql#82]
Following on from https://github.com/cavaliercoder/libzbxpgsql/issues/45#issuecomment-290160928, it appears that Zabbix 3.2.4 may have introduced a regression that results in the following error:

```
cannot find "zbx_module_history_write_cbs()" function in module "libzbxpgsql.so": /usr/lib/zabbix/modules/libzbxpgsql.so: undefined symbol: zbx_module_history_write_cbs
```

According to https://www.zabbix.com/documentation/3.2/manual/config/items/loadablemodules, `zbx_module_history_write_cbs` is an optional function and should not be required to exist.

**Comment by cavaliercoder** [comment]
@abdull Can you please advice which operating system your Zabbix 3.2.4 agent is running on? I was unable to replicate your issue on Debian.

**Comment by akomic** [comment]
Having the same issue.
I have zabbix-proxy between zabbix-server and zabbix-agent in this configuration. Zabbix-agent is connecting to remote host postgresql (not localhost). When i try running zabbix_get from proxy machine I'm getting correct info:

zabbix-proxy$  zabbix_get -s 127.0.0.1 -k 'pg.starttime["host=10.0.0.2 port=5432 user=monitoring connect_timeout=30", postgres]' 
2015-04-18 10:39:00.848356+03

zabbix-proxy$ /usr/sbin/zabbix_agentd -p
zabbix_agentd [22468]: Error: PostgreSQL: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

zabbix-proxy$ grep 'function in module' /var/log/zabbix/zabbix_agentd.log
 22334:20170422:211839.036 cannot find "zbx_module_history_write_cbs()" function in module "libzbxpgsql.so": /usr/lib/zabbix/modules/libzbxpgsql.so: undefined symbol: zbx_module_history_write_cbs

Zabbix-server is not getting anything.

**Comment by cavaliercoder** [comment]
The log message is actually a debug-level message and is not an error condition. See `src/libs/zbxmodules/modules.c` in the Zabbix sources. Zabbix checks for all supported module functions and gracefully handles any optional functions by logging a message such as this.
