### ISSUE TITLE
flapping triggers

### ISSUE THREAD

**Issue by Marx1st** [cavaliercoder/libzbxpgsql#83]
Hi,

I'm using libzbxpgsql 1.1.0 with PostgreSQL 9.4 and Zabbix 3.2.

It works mostly great, but I got an annoying flapping trigger:

"Trigger: PostgreSQL Server on XXXX has just been restarted
Trigger status: PROBLEM
Trigger severity: Information
Trigger URL: 
Event date: 2017.03.30

Item values:

1. PostgreSQL Server uptime (XXXX:pg.uptime[user=monitoring,postgres]): 23h 52m"

It will change from "Problem" to "OK" every minute. I can, of course, disable that trigger, but rather would like to fix the problem.

Regards
Tobias

**Comment by robbrucks** [comment]
That is a very strange problem.

Can you check the results of the following query on your DB as the "monitoring" user:
```
SELECT EXTRACT(EPOCH FROM NOW()) - EXTRACT(EPOCH FROM pg_postmaster_start_time());
```
That is the query that should be checking how long it has been since the DB was started.

Go ahead and run it several times over the course of a minute or two and paste the output here.

Thanks,
Rob

**Comment by Marx1st** [comment]
Hi!

Here's the output of that select:

`moodle=> SELECT EXTRACT(EPOCH FROM NOW()) - EXTRACT(EPOCH FROM pg_postmaster_start_time());
     ?column?
------------------
 2868.30740404129
(1 row)

moodle=> SELECT EXTRACT(EPOCH FROM NOW()) - EXTRACT(EPOCH FROM pg_postmaster_start_time());
     ?column?
------------------
 2870.21849608421
(1 row)

moodle=> SELECT EXTRACT(EPOCH FROM NOW()) - EXTRACT(EPOCH FROM pg_postmaster_start_time());
     ?column?
------------------
 2871.13075208664
(1 row)

moodle=> SELECT EXTRACT(EPOCH FROM NOW()) - EXTRACT(EPOCH FROM pg_postmaster_start_time());
     ?column?
------------------
 2872.04324293137
(1 row)

moodle=> SELECT EXTRACT(EPOCH FROM NOW()) - EXTRACT(EPOCH FROM pg_postmaster_start_time());
     ?column?
------------------
 2879.56337189674
(1 row)

moodle=> SELECT EXTRACT(EPOCH FROM NOW()) - EXTRACT(EPOCH FROM pg_postmaster_start_time());
     ?column?
------------------
 2880.97920203209
(1 row)

moodle=> SELECT EXTRACT(EPOCH FROM NOW()) - EXTRACT(EPOCH FROM pg_postmaster_start_time());
     ?column?
------------------
 3152.71059298515
(1 row)

moodle=> SELECT EXTRACT(EPOCH FROM NOW()) - EXTRACT(EPOCH FROM pg_postmaster_start_time());
     ?column?
------------------
 3153.42311501503
(1 row)

moodle=> SELECT EXTRACT(EPOCH FROM NOW()) - EXTRACT(EPOCH FROM pg_postmaster_start_time());
     ?column?
------------------
 3153.95880889893
(1 row)`

> 

For your information, when the trigger is fired it got e.g. this value:
`Item values:

1. PostgreSQL Server uptime (moodle2:pg.uptime[user=monitoring,postgres]): 45m 58s`

when it gets resolved it has e.g. this value:
`Item values:

1. PostgreSQL Server uptime (moodle2:pg.uptime[user=monitoring,postgres]): 1m 9d 20h`

**Comment by Marx1st** [comment]
Btw. there is (sometimes) a second trigger which is flapping and I really don't know where it is coming from:

```
Trigger: PostgreSQL Agent module version was changed on moodle2
Trigger status: PROBLEM
Trigger severity: Information
Trigger URL: 
Event date: 2017.04.11

Item values:

1. PostgreSQL Module version (moodle2:pg.modver): libzbxpgsql 0.2.1

Original event I
```

```
Trigger: PostgreSQL Agent module version was changed on moodle2
Trigger status: OK
Trigger severity: Information
Trigger URL: 
Event recovery date: 2017.04.11
Item values:

1. PostgreSQL Module version (moodle2:pg.modver): libzbxpgsql 1.1.0, compiled for Zabbix 3.2.3


Original event I
```

**Comment by robbrucks** [comment]
That is really bizarre.

It almost appears that you have two different Zabbix agents on two different servers configured to use the same Hostname in their zabbix_agentd.conf files.

Then they both report in as one server but with different values.

That's the only thing I can think of.

**Comment by Marx1st** [comment]
Thank you, thank you, thank you!

This is exactly what happened here! We do have a (slightly out of date) copy of the server for testing and "someone" forgot to change the zabbix client hostname in the settings and it had an old version oft the library...

Thanks again!
