### ISSUE TITLE
Can't not connect to Postgres. Help needed

### ISSUE THREAD

**Issue by rongs89** [cavaliercoder/libzbxpgsql#85]
I've installed the libzbxpgsql module, but I got stuck at configuring it properly. Here is what I have done so far.

1. installed zabbix agent module. [Success] - installed 3.2 version for CentOS 7. 
2. imported Zabbix template. [Success]
3. applied the template to the host that has Postgres 9.5 installed. [Success]
4. applied a general OS template to the same host. [Success] The ZBX icon turns green and server receives data.
5. created a monitoring role named "monitoring", and grant the access to my database named "test". [Success] The role can login via psql
6. Because the agent runs on the Postgres server, I chose to do the local monitoring agent config.

my pg_hba.conf looks like
local all monitory peer map=monitoring

my pg_ident.conf looks like
monitoring root monitoring

I also tried to map the 'monitoring' to 'zabbix'. But none of them got connected.

my connection macros look like
{$PG_CONN} => host=localhost port=5432 user=monitoring connect_timeout=10
${PG_DB} => test

The errors I found in the Postgres look like

2017-04-05 21:18:03 EDT:ruroot:3378:FATAL:  no pg_hba.conf entry for host "[local]", user "root", database "root", SSL off

in the zabbix_agentd.conf, I have "AllowRoot=0".

The zabbix_agent version is 3.2.4. The module was pre-compiled for 3.2.3. I don't know if it matters much.

Could you please tell me what I have done wrong. Thanks!

**Comment by rongs89** [comment]
Made some progress today.

I installed zabbix-get on the agent. if I run the following, I got the data back

sudo -u zabbix zabbix_get -s 127.0.0.1 -k "pg.starttime[user=monitoring, test]"

But I still cannot get the data from zabbix-server.

My {$PG_CONN} is set to "user=monitoring" and {$PG_DB} to "test". The discovery filter for database {#DATABASE} is set to "^test$".

**Comment by robbrucks** [comment]
Which version of the libzbxpgsql module did you install on your DB server?

This will tell you:
```
rpm -qa | grep libzbxpgsql
```

Thanks,
Rob

**Comment by rongs89** [comment]
Hi Rob,

Thank you for helping me!

The version is libzbxpgsql-1.1.0-1.x86_64

Rong

**Comment by robbrucks** [comment]
Hi Rong,

Good, I just wanted to make sure you installed the libzbxpgsql module on your DB server, since you didn't mention it.  Others have skipped that step.

Normally the zabbix agent switches itself to run as the OS user "zabbix" (unless you modified the "User" setting in zabbix_agentd.conf), so your pg_ident.conf map needs to reference "zabbix" instead of "root" for the "SYSTEM-USERNAME" entry.

To make things easier to understand in the configs I would use a mapname that is different from the username.

In your pg_hba.conf file you said it was set to `local all monitory peer map=monitoring`, but "monitory" should probably be "monitoring" shouldn't it?  Not sure if that was just a typo or not.

**Here's how I set up mine:**
I created a "zabbix_agent" user in the database, with the necessary permissions.

_pg_ident.conf:_
```
zabbixmap  zabbix  zabbix_agent
```

_pg_hba.conf:_
```
local  all  zabbix_agent  peer map=zabbixmap
host  all  zabbix_agent  0.0.0.0/0  reject  # prevent remote agent logins
```

_{$PG_CONN}:_
```
user=zabbix_agent
```

Also be sure there are no lines earlier in the pg_hba.conf file that may cause problems.

--Rob

**Comment by rongs89** [comment]
Hi Rob,

The line `local all monitory peer map=monitoring` has a typo.

I followed your example, setting up the db user 'zabbix_agent' and its related configuration in pg_hba.conf and pg_ident.conf. Here is the command I tested afterwards.

sudo -u zabbix zabbix_agentd -t "pg.version[host=/tmp user=zabbix_agent, postgres]"

Yes, as you said, the zabbix_agentd is running by the zabbix system user.

The above command generated the following result:

zabbix_agentd [6115]: starting agent module libzbxpgsql 1.1.0
zabbix_agentd [6115]: using module configuration file: /etc/zabbix/libzbxpgsql.conf
pg.version[host=/tmp user=zabbix_agent, test] [s|PostgreSQL 9.5.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4), 64-bit]

It appears the connection from my zabbix agent and the Postgres server works fine. Do you agree?

On the zabbix server, I can receive data for CPU or memory utilization (applied using the Linux OS template), but I cannot receive data for the key pg.version. The path of connections from the server to the agent is like the following:

zabbix server <--> zabbix proxy <--> zabbix agent (Postgres)

The agent is configured to use the proxy. Is there any other configuration I should do?

Thanks,

Rong

**Comment by robbrucks** [comment]
Yes, it looks like the agent is working now.

Are you only having a problem with one "pg" metric or all of them?

Make sure the `{$PG_CONN}` macro setting in the UI for your DB host matches what you used on the command line.  If it is different than what you tested with then it could fail.

The proxy does introduce delay in sending configuration changes to the agent. Changes made through the UI could take a considerable amount of time to propagate to the agent (default is 60 minutes; proxy setting `ConfigFrequency`).  By default the proxy reads config data from the Zabbix server every 60 minutes.

Make sure you allow time for the proxy to forward configuration changes to the agent before assuming there is a problem.

**Comment by robbrucks** [comment]
If possible you may want to point the agent at the main Zabbix server until you get it working, then switch it back to the proxy.  Then you don't have to wait on the proxy to update the config.

**Comment by rongs89** [comment]
I had the ConfigFrequency set to 1 minute, so I don't think that's the problem.

I will try your suggestion - connect the agent to the server directly. Will report back.

**Comment by rongs89** [comment]
Forgot to mention, I have a problem with all "pg" metrics.

**Comment by rongs89** [comment]
Hi Rob,

I found the cause of the problem. I misconfigured the Hostname in my zabbix_agentd.conf. It was pointed to a wrong host. Once I corrected it, I got the data from the server.

Thank you very much for your help!

Rong

**Comment by robbrucks** [comment]
You're welcome. Glad you found the problem.

**Comment by cavaliercoder** [comment]
Closing. Thanks Rob!
