### ISSUE TITLE
Incorrect documentation for pg.db.blks_perc

### ISSUE THREAD

**Issue by conexaoinfraestrutura** [cavaliercoder/libzbxpgsql#86]
Same thing:
zabbix_get -s 11.0.0.52 -k pg.db.blks_perc["user=postgres host=127.0.0.1 port=5432","postgres"]
ZBX_NOTSUPPORTED: Unsupported item key.

zabbix_get -s 11.0.0.52 -k pg.db.blks_ratio["user=postgres host=127.0.0.1 port=5432","postgres"]
ZBX_NOTSUPPORTED: Unsupported item key.

I maked my own template and the information about this item i caught from de official project website

http://cavaliercoder.com/libzbxpgsql/documentation/reference/databases/#pg-db-blks-perc

 pg.db.blks_perc

Returns the percentage of in-memory cache hits to disk reads as a fraction of 1. A high value (close to 1) indicates most reads are served from cache, while a low value (close to 0) indicates most reads are served from slower disk media.

Type: Numeric (float)

Parameters:

    connection string - libpq compatible keyword/value connection string
    connection database - connection database (default: username from connection string)
    database - return statistics for this database (may differ from the connected database)  (default: average for all database)

Also i have big problems with of the ubuntu package libzbx. In the ubuntu i had to install debian version to do libzbx goes to work fine

dpkg -l | grep libzbx
ii libzbxpgsql 1.1.0-1 amd64 PostgreSQL monitoring module for Zabbix

dpkg -l | grep zabbix
ii zabbix-agent 1:2.4.8-1+trusty amd64 network monitoring solution - agent
ii zabbix-release 2.4-1+trusty all Zabbix official repository configuration

if you need more information about my enviroment please reply me.

**Comment by conexaoinfraestrutura** [comment]
![screenshot from 2017-04-06 10-26-45](https://cloud.githubusercontent.com/assets/19329445/24756653/eb683682-1ab3-11e7-8030-2d8a73b91565.png)
![screenshot from 2017-04-06 10-27-40](https://cloud.githubusercontent.com/assets/19329445/24756654/eb6b0d44-1ab3-11e7-9292-e4e2f7a9ebc3.png)

**Comment by conexaoinfraestrutura** [comment]
so.
after i a reduced the debug of zabbix_agentd to "3" and adjusted the item key to _ratio instead _perc, the item simply came back to get information.
I don't know how :(
I tested this in the other version of lib in centos 6 and libzbx 0.2.1 and the problem persists.
I go to make a upgrade in the lib and reply the tiket.

**Comment by conexaoinfraestrutura** [comment]
zabbix_get -s 11.0.0.52 -k pg.db.blks_ratio["user=postgres host=127.0.0.1 port=5432","postgres"]
0.944776
After upgrade in the centos 6 everything worked fine. : P only the documentation still wrong.
![screenshot from 2017-04-06 11-04-24](https://cloud.githubusercontent.com/assets/19329445/24758513/02241fd0-1ab9-11e7-8d87-a30bbbd9b3b3.png)
![screenshot from 2017-04-06 11-04-36](https://cloud.githubusercontent.com/assets/19329445/24758524/08a3894a-1ab9-11e7-9f34-008401a648a0.png)

**Comment by cavaliercoder** [comment]
Can you please raise a separate issue concerning the Ubuntu package? Please include more information and the error message.

I'll get the documentation updated soon.
