### ISSUE TITLE
No data and empty graphs

### ISSUE THREAD

**Issue by misasimic** [cavaliercoder/libzbxpgsql#87]
Hi,

I have a problem to get data from libzbxpgsql on Zabbix Server.
Zabbix Server 3.2.5 (on Zabbix Server box)
Zabbix Agent 3.2.5 (on Pg Server 9.6 box)

Pg server added as host on Zabbix Server and basic monitoring From Linux Template on Zabbix Server work fine.

Followed instructions for libzbxpgsql installation on Pg server box. And now:

$ sudo zabbix_agentd -t pg.modver
zabbix_agentd [24235]: starting agent module libzbxpgsql 1.1.0
zabbix_agentd [24235]: using module configuration file: /etc/zabbix/libzbxpgsql.conf
pg.modver                                     [s|libzbxpgsql 1.1.0, compiled for Zabbix 3.2.3]

 (PS. I beleive - last night it has not shown starting agent module... - just pg.modver line)

When I try on Pg Server machine:
$ sudo zabbix_agentd -t "pg.backends.count[user=monitoring,test]"
zabbix_agentd [24575]: starting agent module libzbxpgsql 1.1.0
zabbix_agentd [24575]: using module configuration file: /etc/zabbix/libzbxpgsql.conf
pg.backends.count[user=monitoring,test]              [u|2]

I would say - it works.

$sudo zabbix_agentd -p

for pg keys - does not work. says: FATAL: Peer Authentication failed for user "root"

When I try on Zabbix Server:

$sudo zabbix_get -s PgServer -k "pg.backends.count[user=monitoring,test]"
2

I would say - it works,

On Zabbix Server Web. I have added PgServer host, and applied Template App PostgerSQL.
Edited Macros on Host Macros:
key: {$PG_CONN}  value: user=monitoring
key: {$PG_DB} value: test

When I take a look on Postgresql standrad graphs from template - they are empty...
When I go to Latest Data - there are no Postgresql Items at all...

How I could check why it does not collect data from PgServer in Zabbix Server?

Many Thanks.

Misa

**Comment by cavaliercoder** [comment]
I would expect `zabbix_agentd -p` to fail as you described, if the `root` account does not have permission to connect (which is typical). I wouldn't worry about that.

As for the template issue, your best bet is to look for errors in the Zabbix server and agent log files. Also, take a look at the Items on the PostgreSQL Host configuration. They may have a red cross in the Info column that includes an error message.

**Comment by tiyab** [comment]
It happens to me at the beginning.
zabbix_get was working fine but had nothing in the web interface.
My solution was to check that the port 10051 was open on the postgresql server

**Comment by cavaliercoder** [comment]
Is this resolved for you?

**Comment by misasimic** [comment]
Hi,

It seems, it just needed more time to discovery service start working and identify new client.

After few days - data start to come in.

But I have performed tests inside VMs on Virtual Box. So machines where up & down often.... One day have been UP for a long period... And Discovery Service discovered Pg Items.

Everything works now...

Thanks for your help. We can close the case :)

Misa

**Comment by cavaliercoder** [comment]
Thanks for getting back to us. All the best!
