### ISSUE TITLE
Message on template import in zabbix server 3.2

### ISSUE THREAD

**Issue by JeromeDeniau** [cavaliercoder/libzbxpgsql#88]
Hi

I am trying to import the 3.0 xml as a template (from github) into zabbix server 3.2 but I do have this message:

Impossible de lire du XML : (41) Specification mandate value for attribute data-pjax-transient [Ligne: 35 | Colonne: 40].

line is (without the character

meta name="request-id" content="2D21:2FF3:422133A:673D1D1:5924744E" data-pjax-transient

Any idea? Thanks.

**Comment by robbrucks** [comment]
I just performed a test import of the 3.0 template here into my Zabbix 3.2 system without error.

Could you paste the line that is getting an error here?

The error appears to be referencing an attribute called "data-pjax-transient" which is not referenced in any of the libzbxpgsql templates.

Thanks.

**Comment by JeromeDeniau** [comment]
Yes sure:

ligne 35 is
<meta name="request-id" content="2D21:2FF3:422133A:673D1D1:5924744E" data-pjax-transient>

**Comment by JeromeDeniau** [comment]
herr sorry copy.paste did not work

<meta name="request-id" content="2D21:2FF3:422133A:673D1D1:5924744E" data-pjax-transient>

**Comment by JeromeDeniau** [comment]
Aaargh I closed

 

The correct lign 35 is:

<meta name="request-id" content="2D21:2FF3:422133A:673D1D1:5924744E" data-pjax-transient>

 

I've added the file with my mail .....

 

More info: the zabbix-server does not have zabbix-agent and config was done following the zabbix doc..... on centos 7 with postgresql

 

----- Message d'origine -----
De : Rob Brucks <notifications@github.com>
A : cavaliercoder/libzbxpgsql <libzbxpgsql@noreply.github.com>
Cc : JeromeDeniau <jerome.deniau@move4ideas.com>, Author <author@noreply.github.com>
Objet : Re: [cavaliercoder/libzbxpgsql] Message on template import in zabbix server 3.2 (#88)
Date : mar. 23 mai 2017 20:45
 
I just performed a test import of the 3.0 template here into my Zabbix 3.2 system without error.

Could you paste the line that is getting an error here?

The error appears to be referencing an attribute called "data-pjax-transient" which is not referenced in any of the libzbxpgsql templates.

Thanks.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.






 



 
  
   
    
   
  
  
   Jérôme Deniau
  
 
 
  
   Directeur Technique
  
 
 
  
   Phone: +33 (0)7-82-63-42-60 
  
 
 
   
  
 
 
  
6, rue de la Blanche Hermine
  
 
 
  35770 Vern-sur-Seiche
 
 
  
   
   
   Follow us      
    
Messaging Intelligence

**Comment by robbrucks** [comment]
It looks like you may have tried to download the template file directly, or maybe you executed a "wget" of the template file from Github.  The snippet from the file you downloaded looks like an XML representation of the link in Github.

Unfortunately you can't do a direct download with Github.  For the libzbxpgsql repository you will either have to "fork" it (create your own personal copy) and then clone it to your local machine, or click on the template file to view it, then click the "Raw" button, then do a "save as" from your browser.

To make it easier for you I've attached it as a "txt" file. Just download it to your machine and remove the ".txt" from the filename.

Good luck.
[Template_PostgreSQL_Server_3.0.xml.txt](https://github.com/cavaliercoder/libzbxpgsql/files/1023621/Template_PostgreSQL_Server_3.0.xml.txt)

**Comment by JeromeDeniau** [comment]
Thank you thank you, bis repetita!
And thanks for the wget!
