### ISSUE TITLE
High CPU utilization

### ISSUE THREAD

**Issue by Ufaowl** [cavaliercoder/libzbxpgsql#9]
Hi! Thank you for your plugin. It's great and useful. But somehow the CPU usage goes straight up after adding template to host. I tried to exclude almost everything in discovery section without any improvement.
Can you give some tips to tune your plugin  to reduce such CPU consumption?

**Comment by cavaliercoder** [comment]
You're very welcome. Thanks for giving it a try.
One of the trade offs in demonstrating everything the module can do in the included template is that it creates so many items on the first discovery run (around 6000). On lower spec machines, this will peak the CPU (as it does on my 1xCPU 512mb VM). You should see that it's actually PostgreSQL doing most of the heavy lifting; not the agent.

On most modern servers, the CPU impact (with 6000+ items) is measurable but without negative impact. But realistically, 6000 items is a little superfluous and bad practice for delivering a high value monitoring system.

It's really important to disable the items that are not relevant to you and set large enough intervals according to your environment before adding the template to a host. This is noted in the template usage documentation: http://cavaliercoder.github.io/libzbxpgsql/template/. Maybe I should change this so all items are disabled by default???

Please note that if you disable discovery items, any items that have already been discovered will not be removed until the discovery cleanup period expires (30 days from memory). You would be better suited to unlink and clear the PostgreSQL template and add it again after you have disabled unrequired features. Until then, your CPU utilization will most likely not improve.

**Comment by Ufaowl** [comment]
Thank you for your help! 
I managed to get lower CPU load by setting a few filters and disabling unwanted items. 
It seems so obvious now)) 
Thanks again!
