### ISSUE TITLE
Remote Postgres 

### ISSUE THREAD

**Issue by msmarziali** [cavaliercoder/libzbxpgsql#90]
Hi,
The goal is to monitor a 9.4 remote postgres server.
My situation is:
main-db-server  <--> (192.168.0.20/24) PostgresSQL Server 9.4 
zabbix-server <----> (192.168.0.23/24) Zabbix Server 3.2  (zabbix-release-3.2-1.el7.noarch.rpm)

Step1)  
libzbxpgsql agent module is installed from rpm into main-db-server  and the installation is valid.
"[root@main-db-server data]# zabbix_agentd -t pg.modver
  zabbix_agentd [16887]: starting agent module libzbxpgsql 1.1.0
  zabbix_agentd [16887]: using module configuration file: /etc/zabbix/libzbxpgsql.conf
  pg.modver                                     [s|libzbxpgsql 1.1.0, compiled for Zabbix 3.2.3]"
![validation](https://cloud.githubusercontent.com/assets/2008688/26430054/174003c2-40eb-11e7-9557-202cab68bc82.jpg)

Step2) In zabbix-server  i  import template "Template_PostgreSQL_Server_3.0.xml" and applied to main-db-server. 
![template](https://cloud.githubusercontent.com/assets/2008688/26429744/0881c692-40e9-11e7-8e77-3f6f3df3ce07.jpg)
![applied_template](https://cloud.githubusercontent.com/assets/2008688/26429767/2c70290e-40e9-11e7-8c8f-4bacd65f4431.jpg)

Step3) I setup the Macro in zabbix-server
{$PG_CONN} => host=main-db-server port=5432 user=postgres password=xxxx connect_timeout=10
{$PG_DB} => TestApp
![macro](https://cloud.githubusercontent.com/assets/2008688/26429774/34b2b924-40e9-11e7-91f8-2b454cb5141d.jpg)

In my main-db-server the pg_hba.conf is
host    all             all             127.0.0.1/32            trust
host    all             all             192.168.0.20/32         trust
host    all             all             192.168.0.21/32         trust
host    all             all             192.168.0.0/24          md5
![pg_hba_conf](https://cloud.githubusercontent.com/assets/2008688/26430125/92a20254-40eb-11e7-9520-eb51ec74de82.jpg)

The ping from main-db-server --> zabbix-server and zabbix-server -->main-db-server work perfectly.

Zabbix server  does not show any data: for all the charts "PostgresSQL Backend Connections", "PostgresSQL Buffers", "...Checkpoint...", "...Threshould..." 
What am I doing wrong ?!?

Thank you in advance for all the help you can.

Max

**Comment by robbrucks** [comment]
Before I can offer any advice, I'll need some more info:

1. What OS and version are you running on the DB server (```cat /etc/redhat-release```)?
2. Have you checked the Postgres logs to see if there are any errors related to the agent (by default the logs are in ```/var/lib/pgsql/9.4/data/pg_log/```)?
3. Have you checked the Zabbix agent logs on the DB server for any errors (by default in ```/var/log/zabbix```)?
4. Did you set the macro settings on the "main-db-server" host or on the PostgreSQL template in the Zabbix UI?  They should be set on the main-db-host...
5. Is SeLinux enabled in Enforcing mode (run ```getenforce``` command)?

Also, test connectivity on main-db-server to your DB by running the following as the postgres user:
```psql -l -h main-db-server -p 5432 -U postgres -W -d TestApp```

It will prompt you for the password.

That will make the DB connection using the same settings and network path as the agent.

Paste the output of that here.

**Comment by msmarziali** [comment]
Hi,

1) [root@main-db-server ~]# cat /etc/redhat-release
CentOS Linux release 7.1.1503 (Core)

2) On main-db-server (/var/lib/pgsql/9.4/data/pg_log/)  not have error for login.

3) On main-db-server  log for zabbix-agent not have error.
 2688:20170526:003002.721 Starting Zabbix Agent [main-db-server.sigmaspa.lan]. Zabbix 3.2.6 (revision 67849).
  2688:20170526:003002.721 **** Enabled features ****
  2688:20170526:003002.721 IPv6 support:          YES
  2688:20170526:003002.721 TLS support:           YES
  2688:20170526:003002.721 **************************
  2688:20170526:003002.721 using configuration file: /etc/zabbix/zabbix_agentd.conf
  2688:20170526:003002.722 starting agent module libzbxpgsql 1.1.0
  2688:20170526:003002.722 using module configuration file: /etc/zabbix/libzbxpgsql.conf
  2688:20170526:003002.723 loaded modules: libzbxpgsql.so
  2688:20170526:003002.723 agent #0 started [main process]
  2690:20170526:003002.767 agent #2 started [listener #1]
  2692:20170526:003002.767 agent #4 started [listener #3]
  2689:20170526:003002.769 agent #1 started [collector]
  2691:20170526:003002.769 agent #3 started [listener #2]

4) I have setting macro at host main-db-server. 
At template level:
![macro_template](https://cloud.githubusercontent.com/assets/2008688/26473315/05a3d4fc-41ab-11e7-8b80-44a52b40e805.jpg)

For host main-db-server:
![macro_host](https://cloud.githubusercontent.com/assets/2008688/26473376/49f2e378-41ab-11e7-8715-4b00438731e8.jpg)

5) SeLinux:
[root@main-db-server /]# getenforce
Disabled
[root@main-db-server /]#




Test connectivity on main-db-server 

[root@main-db-server /]#
[root@main-db-server /]# su postgres
bash-4.2$ psql -l -h main-db-server -p 5432 -U postgres -W -d TestApp
Password for user postgres:
                                    List of databases
     Name     |  Owner   | Encoding |   Collate   |    Ctype    |    Access privileges
--------------+----------+----------+-------------+-------------+-------------------------
 TestApp  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =Tc/postgres           +
              |          |          |             |             | postgres=CTc/postgres  +
              |          |          |             |             | grp_quality=Tc/postgres+
              |          |          |             |             | aminnucci=c/postgres
 IntranetBulk | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =Tc/postgres           +
              |          |          |             |             | postgres=CTc/postgres  +
              |          |          |             |             | aminnucci=c/postgres
 QTM          | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | postgres=CTc/postgres
 Quality      | quality  | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =Tc/quality            +
              |          |          |             |             | quality=CTc/quality
 postgres     | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 survay       | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | postgres=CTc/postgres
 template0    | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres            +
              |          |          |             |             | postgres=CTc/postgres
 template1    | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres            +
              |          |          |             |             | postgres=CTc/postgres
(8 rows)

bash-4.2$


From Dashboard Graph of Zabbix server:
![nodata](https://cloud.githubusercontent.com/assets/2008688/26473534/496d10e4-41ac-11e7-9bb2-2cf87feac7be.jpg)

In main-db-server the file libzbxpgsql.conf
![libzbxpgsql](https://cloud.githubusercontent.com/assets/2008688/26473689/37ea8710-41ad-11e7-867d-82c85f417021.jpg)


What am I doing wrong ?!?

Thank you in advance for all the help you can.
Thanks again.
Max

**Comment by robbrucks** [comment]
Next let's test if the agent can successfully connect to the DB using your configuration.

Install the "zabbix-get" package (if it's not already installed) on your DB server.

You will also need to make sure that the "Server" setting in `/etc/zabbix/zabbix_agent.conf` includes IP address `127.0.0.1` in the list. Be sure to restart the agent if you change this setting.

Then run the following command on your DB server as root (put in your password):
```
zabbix_get -s 127.0.0.1 -k "pg.connect[host=main-db-server port=5432 user=postgres password=xxxx connect_timeout=10,TestApp]"
```

This command will either return a 0 or a 1.

If there is a connection problem then it should either show up in the Zabbix agent log or the PostgreSQL log.

Let me know what happens.

**Comment by robbrucks** [comment]
Also try the zabbix_get command with the "pg.uptime" key.

**Comment by robbrucks** [comment]
Did you get it working?

**Comment by msmarziali** [comment]
Now it works !!, the problem was on DB accesses.
I did not find compatibility issues. It's a great template.

Thanks to the precious support!.ù
Max.

**Comment by robbrucks** [comment]
Glad you got it working.
