### ISSUE TITLE
configure fails with Postgres-XL

### ISSUE THREAD

**Issue by sgplay** [cavaliercoder/libzbxpgsql#91]
./configure fails with Postgres-XL
pg_config --version returns: PostgreSQL 9.5.5 (Postgres-XL 9.5r1.4)
So (POSTGRESQL_VERSION=`$PG_CONFIG --version | sed -e 's#PostgreSQL ##'`)
POSTGRESQL_VERSION=9.5.5 (Postgres-XL 9.5r1.4)
As result  the verification of POSTGRESQL_VERSION fails.
I have fixed it inside "configure" script, by adding "| awk '{print $1}'" to the POSTGRESQL_VERSION.
So final line looks like:
POSTGRESQL_VERSION=`$PG_CONFIG --version | sed -e 's#PostgreSQL ##' | awk '{print $1}'`

**Comment by cavaliercoder** [comment]
I've updated the configure script now to `$PG_CONFIG --version | awk '{print $2}'`. Hopefully this will cater to a larger number of inputs, including XL.
