### ISSUE TITLE
Problem about connection

### ISSUE THREAD

**Issue by por16378** [cavaliercoder/libzbxpgsql#93]
Hi I'm student from KMUTNB in Thailand I'm newbie for  monitering I've leaning about zabbix monitering with template postgresql just 2 week I'm juse only done to make zabbix console show me pgsql connected to agent (learn solution from #45 and other) I've tried to check or do something that make me sure they are connected succesful and usable but I've checked with zabbix_get -s <myagentip> -k pg.modver  , zabbix_get -s <myagentip> -k pg.connect[user=pdns] but it return 0 and in graph monitering is no data
Could you please teach me how to check or work?
p.s. sorry if I make you annoying.
regard.

**Comment by cavaliercoder** [comment]
It is my pleasure to help you with this.
You will probably find the answer in the Zabbix Agent log files. Please restart the agent and take a look at the messages from the time the agent start. Please post here what you find.

**Comment by por16378** [comment]
![capture](https://user-images.githubusercontent.com/21307877/27371397-d0049d00-568a-11e7-92d4-ea1c899ab82b.PNG)
I found somethingwrong I think it didnt work cause zabbix agent type active ?? 
and I change dicover postgresql in template all of them from "type:zabbix agent(active)" to "type : zabbix agent"  if I didnt change ,ZBX will turn to gray

**Comment by cavaliercoder** [comment]
You might have a firewall/routing problem here. Nothing to do with the PostgreSQL module - just that the agent cannot reach the server on port 10051.

If the server can reach the agent correctly however, switching from Active to Passive checks should get things working for you (everything else looks okay in your logs). I would recommend fixing Active checks instead though, as they improve the performance of your server and reduce network overhead.

**Comment by cavaliercoder** [comment]
Is the IP address configured under ServerActive in the agent config file correct?

**Comment by por16378** [comment]
Server & ServerActive : 192.168.56.220
my zabbix server is running on 192.168.56.220
// I just change to test by change ip to another (192.168.56.223 agent) (127.0.0.1 default) but nothing happen
is that correct ?

**Comment by cavaliercoder** [comment]
That sounds correct. You might be most successful chatting to the Zabbix community in the forum or on IRC. Someone will likely be available to talk you through the issue you are having with active checks.

Please see: http://www.zabbix.com/community
