### ISSUE TITLE
getsockopt(TCP_KEEPALIVE) failed: Option not supported by protocol (Solaris 11.3)

### ISSUE THREAD

**Issue by lizenko** [cavaliercoder/libzbxpgsql#95]
Hello, 
the following message appeared in PostgreSQL logs, after enabling libzbxpgsql.so

`2017-06-27 18:00:31 CEST 127.0.0.1 zbx@postgres % LOG:  getsockopt(TCP_KEEPALIVE) failed: Option not supported by protocol`

Zabbix agent & server version 3.2, llibzbxpgsql version 1.0.0, agent and PostgreSQL 9.6.3 are running on Solaris 11.3 (latest stable).

Unfortunately, I've not found a place in sources, where tcp connection properties placed, but it seems like it should be SO_KEEPALIVE.

Probably it is not a libzbxpgsql problem, but I can not reproduce this error with libpq examples:
https://www.postgresql.org/docs/current/static/libpq-example.html

**Comment by lizenko** [comment]
Looks like server side issue - reproduced with pgAdmin 3 and 4.

**Comment by lizenko** [comment]
It is a PosgtreSQL confirmed bug #14720. Closed.

**Comment by cavaliercoder** [comment]
Excellent submission! Thanks for the great details and followup.
