### ISSUE TITLE
Nodata from postgresql in graph and trigger

### ISSUE THREAD

**Issue by por16378** [cavaliercoder/libzbxpgsql#96]
I had read many solution from the other and tried to solved it  after I had success to  allow connection port  in server (active check) but nothing change in zabbixconsole  
e.g.
change user in pg_hba.conf , pg_ident.conf , .pgpass
pg_hba.conf

# TYPE  DATABASE        USER            ADDRESS                 METHOD
local   pdns            pdns                                    trust
local   pdns            pdns                                    ident map=pdnst
# "local" is for Unix domain socket connections only
local   all             all                                     md5
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
host    all             all             192.168.56.223/32       md5
# IPv6 local connections:
host    all             all             ::1/128                 ident
# Allow replication connections from localhost, by a user with the
# replication privilege.
#local   replication     postgres                                peer
#host    replication     postgres        127.0.0.1/32            ident
#host    replication     postgres        ::1/128                 ident

pg_ident.conf
# MAPNAME       SYSTEM-USERNAME         PG-USERNAME
pdns            root                    pdns

.pgpass
hoststname:port:database:username:password
*:*:pdns:pdns:powerdns

sudo -u pdns zabbix_agentd -p | grep -n .pg
result is ...
zabbix_agentd [17856]: starting agent module libzbxpgsql 1.1.0
zabbix_agentd [17856]: using module configuration file: /etc/zabbix/libzbxpgsql.conf
1:agent.hostname                                [s|DNS]
2:agent.ping                                    [u|1]
3:agent.version                                 [s|3.2.6]
4:system.localtime[utc]                         [u|1499316622]
5:system.run[echo test]                         [m|ZBX_NOTSUPPORTED] [Remote commands are not enabled.]
6:web.page.get[localhost,,80]                   [t|]
7:web.page.perf[localhost,,80]                  [d|0.000000]
8:web.page.regexp[localhost,,80,OK]             [s|]
9:vfs.file.size[/etc/passwd]                    [u|1097]
10:vfs.file.time[/etc/passwd,modify]             [u|1497375360]
11:vfs.file.exists[/etc/passwd]                  [u|1]
12:vfs.file.contents[/etc/passwd]                [t|root:x:0:0:root:/root:/bin/bash
13:bin:x:1:1:bin:/bin:/sbin/nologin
14:daemon:x:2:2:daemon:/sbin:/sbin/nologin
15:adm:x:3:4:adm:/var/adm:/sbin/nologin
16:lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
17:sync:x:5:0:sync:/sbin:/bin/sync
18:shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
19:halt:x:7:0:halt:/sbin:/sbin/halt
20:mail:x:8:12:mail:/var/spool/mail:/sbin/nologin
21:uucp:x:10:14:uucp:/var/spool/uucp:/sbin/nologin
22:operator:x:11:0:operator:/root:/sbin/nologin
23:games:x:12:100:games:/usr/games:/sbin/nologin
24:gopher:x:13:30:gopher:/var/gopher:/sbin/nologin
25:ftp:x:14:50:FTP User:/var/ftp:/sbin/nologin
26:nobody:x:99:99:Nobody:/:/sbin/nologin
27:vcsa:x:69:69:virtual console memory owner:/dev:/sbin/nologin
28:saslauth:x:499:76:Saslauthd user:/var/empty/saslauth:/sbin/nologin
29:postfix:x:89:89::/var/spool/postfix:/sbin/nologin
30:sshd:x:74:74:Privilege-separated SSH:/var/empty/sshd:/sbin/nologin
31:sawitmee:x:500:500::/home/sawitmee:/bin/bash
32:postgres:x:26:26:PostgreSQL Server:/var/lib/pgsql:/bin/bash
33:pdns:x:498:498:PowerDNS authoritative server user:/:/sbin/nologin
34:zabbix:x:497:497:Zabbix Monitoring System:/var/lib/zabbix:/sbin/nologin]
35:vfs.file.regexp[/etc/passwd,root]             [s|root:x:0:0:root:/root:/bin/bash]
36:vfs.file.regmatch[/etc/passwd,root]           [u|1]
37:vfs.file.md5sum[/etc/passwd]                  [s|5199eb3fe7281bb30824c44987fae0e2]
38:vfs.file.cksum[/etc/passwd]                   [u|3641103166]
39:net.dns[,zabbix.com]                          [u|1]
40:net.dns.record[,zabbix.com]                   [t|zabbix.com           SOA      ns1.yourhostingaccount.com admin.yourhostingaccount.com 2012081367 10800 3600 604800 3600]
41:net.tcp.dns[,zabbix.com]                      [u|1]
42:net.tcp.dns.query[,zabbix.com]                [t|zabbix.com           SOA      ns1.yourhostingaccount.com admin.yourhostingaccount.com 2012081367 10800 3600 604800 3600]
43:net.tcp.port[,80]                             [u|0]
44:system.users.num                              [u|5]
45:log[logfile]                                  [m|ZBX_NOTSUPPORTED] [Accessible only as active check.]
46:log.count[logfile]                            [m|ZBX_NOTSUPPORTED] [Accessible only as active check.]
47:logrt[logfile]                                [m|ZBX_NOTSUPPORTED] [Accessible only as active check.]
48:logrt.count[logfile]                          [m|ZBX_NOTSUPPORTED] [Accessible only as active check.]
49:eventlog[system]                              [m|ZBX_NOTSUPPORTED] [Accessible only as active check.]
50:kernel.maxfiles                               [u|21471]
51:kernel.maxproc                                [u|32768]
52:vfs.fs.size[/,free]                           [u|5091389440]
53:vfs.fs.inode[/,free]                          [u|418910]
55:vfs.dev.read[sda,operations]                  [u|9685]
56:vfs.dev.write[sda,operations]                 [u|10613]
57:net.tcp.listen[80]                            [u|0]
58:net.udp.listen[68]                            [u|1]
59:net.if.in[lo,bytes]                           [u|503039034]
60:net.if.out[lo,bytes]                          [u|503039034]
61:net.if.total[lo,bytes]                        [u|1006078068]
62:net.if.collisions[lo]                         [u|0]
64:vm.memory.size[total]                         [u|249761792]
65:proc.cpu.util[inetd]                          [m|ZBX_NOTSUPPORTED] [Collector is not started.]
66:proc.num[inetd]                               [u|0]
67:proc.mem[inetd]                               [u|0]
68:system.cpu.switches                           [u|2272749]
69:system.cpu.intr                               [u|1067758]
70:system.cpu.util[all,user,avg1]                [m|ZBX_NOTSUPPORTED] [Collector is not started.]
71:system.cpu.load[all,avg1]                     [d|0.300000]
72:system.cpu.num[online]                        [u|1]
74:system.uname                                  [s|Linux DNS 2.6.32-642.el6.x86_64 #1 SMP Tue May 10 17:27:01 UTC 2016 x86_64]
75:system.hw.chassis                             [m|ZBX_NOTSUPPORTED] [Cannot obtain hardware information.]
76:system.hw.cpu                                 [t|processor 0: GenuineIntel Intel(R) Core(TM) i5-3470S CPU @ 2.90GHz working at 2893MHz]
77:system.hw.devices                             [t|sh: lspci: command not found]
78:system.hw.macaddr                             [s|[eth0] 08:00:27:bf:de:7f, [eth1] 08:00:27:e4:81:92]
79:system.sw.arch                                [s|x86_64]
80:system.sw.os                                  [s|Linux version 2.6.32-642.el6.x86_64 (mockbuild@worker1.bsys.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC) ) #1 SMP Tue May 10 17:27:01 UTC 2016]
81:system.sw.packages                            [t|[rpm] MAKEDEV-3.24-6.el6.x86_64, acl-2.2.49-6.el6.x86_64, attr-2.4.44-7.el6.x86_64, audit-2.4.5-3.el6.x86_64, audit-libs-2.4.5-3.el6.x86_64, authconfig-6.1.12-23.el6.x86_64, b43-openfwwf-5.2-10.el6.noarch, basesystem-10.0-4.el6.noarch, bash-4.1.2-40.el6.x86_64, bind-libs-9.8.2-0.62.rc1.el6_9.2.x86_64, bind-utils-9.8.2-0.62.rc1.el6_9.2.x86_64, binutils-2.20.51.0.2-5.44.el6.x86_64, boost-program-options-1.41.0-28.el6.x86_64, bridge-utils-1.2-10.el6.x86_64, bzip2-1.0.5-7.el6_0.x86_64, bzip2-libs-1.0.5-7.el6_0.x86_64, ca-certificates-2015.2.6-65.0.1.el6_7.noarch, centos-release-6-8.el6.centos.12.3.x86_64, checkpolicy-2.0.22-1.el6.x86_64, chkconfig-1.3.49.5-1.el6.x86_64, coreutils-8.4-43.el6.x86_64, coreutils-libs-8.4-43.el6.x86_64, cpio-2.10-12.el6_5.x86_64, cracklib-2.8.16-4.el6.x86_64, cracklib-dicts-2.8.16-4.el6.x86_64, cronie-1.4.4-15.el6_7.1.x86_64, cronie-anacron-1.4.4-15.el6_7.1.x86_64, crontabs-1.10-33.el6.noarch, cryptsetup-luks-1.2.0-11.el6.x86_64, cryptsetup-luks-libs-1.2.0-11.el6.x86_64, curl-7.19.7-52.el6.x86_64, cyrus-sasl-2.1.23-15.el6_6.2.x86_64, cyrus-sasl-lib-2.1.23-15.el6_6.2.x86_64, dash-0.5.5.1-4.el6.x86_64, db4-4.7.25-20.el6_7.x86_64, db4-utils-4.7.25-20.el6_7.x86_64, dbus-glib-0.86-6.el6.x86_64, dbus-libs-1.2.24-8.el6_6.x86_64, device-mapper-1.02.117-7.el6.x86_64, device-mapper-event-1.02.117-7.el6.x86_64, device-mapper-event-libs-1.02.117-7.el6.x86_64, device-mapper-libs-1.02.117-7.el6.x86_64, device-mapper-multipath-0.4.9-93.el6.x86_64, device-mapper-multipath-libs-0.4.9-93.el6.x86_64, device-mapper-persistent-data-0.6.2-0.1.rc7.el6.x86_64, dhclient-4.1.1-51.P1.el6.centos.x86_64, dhcp-common-4.1.1-51.P1.el6.centos.x86_64, diffutils-2.8.1-28.el6.x86_64, dnsperf-2.1.0.0-1.el6.x86_64, dracut-004-409.el6.noarch, dracut-kernel-004-409.el6.noarch, e2fsprogs-1.41.12-22.el6.x86_64, e2fsprogs-libs-1.41.12-22.el6.x86_64, efibootmgr-0.5.4-13.el6.x86_64, elfutils-libelf-0.164-2.el6.x86_64, ethtool-3.5-6.el6.x86_64, expat-2.0.1-11.el6_2.x86_64, file-5.04-30.el6.x86_64, file-libs-5.04-30.el6.x86_64, filesystem-2.4.30-3.el6.x86_64, findutils-4.4.2-9.el6.x86_64, fipscheck-1.2.0-7.el6.x86_64, fipscheck-lib-1.2.0-7.el6.x86_64, fuse-2.8.3-5.el6.x86_64, gamin-0.1.10-9.el6.x86_64, gawk-3.1.7-10.el6_7.3.x86_64, gdbm-1.8.0-39.el6.x86_64, glib2-2.28.8-5.el6.x86_64, glibc-2.12-1.192.el6.x86_64, glibc-common-2.12-1.192.el6.x86_64, gmp-4.3.1-10.el6.x86_64, gnupg2-2.0.14-8.el6.x86_64, gpg-pubkey-442df0f8-4783f24a, gpg-pubkey-60ae0e48-546ad4d1, gpg-pubkey-c105b9de-4e0fd3a3, gpgme-1.1.8-3.el6.x86_64, grep-2.20-3.el6_7.1.x86_64, groff-1.18.1.4-21.el6.x86_64, grub-0.97-94.el6_7.1.x86_64, grubby-7.0.15-7.el6.x86_64, gzip-1.3.12-22.el6.x86_64, hwdata-0.233-16.1.el6.noarch, info-4.13a-8.el6.x86_64, initscripts-9.03.53-1.el6.centos.x86_64, iproute-2.6.32-54.el6.x86_64, iptables-1.4.7-16.el6.x86_64, iptables-ipv6-1.4.7-16.el6.x86_64, iputils-20071127-21.el6.x86_64, iscsi-initiator-utils-6.2.0.873-21.el6.x86_64, kbd-1.15-11.el6.x86_64, kbd-misc-1.15-11.el6.noarch, kernel-2.6.32-642.el6.x86_64, kernel-firmware-2.6.32-642.el6.noarch, keyutils-libs-1.4-5.el6.x86_64, kpartx-0.4.9-93.el6.x86_64, krb5-libs-1.10.3-57.el6.x86_64, less-436-13.el6.x86_64, libacl-2.2.49-6.el6.x86_64, libaio-0.3.107-10.el6.x86_64, libattr-2.4.44-7.el6.x86_64, libblkid-2.17.2-12.24.el6.x86_64, libcap-2.16-5.5.el6.x86_64, libcap-ng-0.6.4-3.el6_0.1.x86_64, libcom_err-1.41.12-22.el6.x86_64, libconfig-1.3.2-1.1.el6.x86_64, libcurl-7.19.7-52.el6.x86_64, libdrm-2.4.65-2.el6.x86_64, libedit-2.11-4.20080712cvs.1.el6.x86_64, libffi-3.0.5-3.2.el6.x86_64, libgcc-4.4.7-17.el6.x86_64, libgcrypt-1.4.5-11.el6_4.x86_64, libgpg-error-1.7-4.el6.x86_64, libidn-1.18-2.el6.x86_64, libnih-1.0.1-7.el6.x86_64, libpciaccess-0.13.4-1.el6.x86_64, libselinux-2.0.94-7.el6.x86_64, libselinux-utils-2.0.94-7.el6.x86_64, libsemanage-2.0.43-5.1.el6.x86_64, libsepol-2.0.41-4.el6.x86_64, libss-1.41.12-22.el6.x86_64, libssh2-1.4.2-2.el6_7.1.x86_64, libstdc++-4.4.7-18.el6.x86_64, libtasn1-2.3-6.el6_5.x86_64, libudev-147-2.73.el6.x86_64, libusb-0.1.12-23.el6.x86_64, libuser-0.56.13-8.el6_7.x86_64, libutempter-1.1.5-4.1.el6.x86_64, libuuid-2.17.2-12.24.el6.x86_64, libxml2-2.7.6-21.el6.x86_64, libxslt-1.1.26-2.el6_3.1.x86_64, libzbxpgsql-1.1.0-1.x86_64, logrotate-3.7.8-26.el6_7.x86_64, lua-5.1.4-4.1.el6.x86_64, lvm2-2.02.143-7.el6.x86_64, lvm2-libs-2.02.143-7.el6.x86_64, m4-1.4.13-5.el6.x86_64, make-3.81-23.el6.x86_64, mdadm-3.3.4-1.el6.x86_64, mingetty-1.08-5.el6.x86_64, module-init-tools-3.9-25.el6.x86_64, mysql-libs-5.1.73-7.el6.x86_64, nc-1.84-24.el6.x86_64, ncurses-5.7-4.20090207.el6.x86_64, ncurses-base-5.7-4.20090207.el6.x86_64, ncurses-libs-5.7-4.20090207.el6.x86_64, net-tools-1.60-114.el6.x86_64, newt-0.52.11-3.el6.x86_64, newt-python-0.52.11-3.el6.x86_64, nspr-4.11.0-1.el6.x86_64, nss-3.21.0-8.el6.x86_64, nss-softokn-3.14.3-23.el6_7.x86_64, nss-softokn-freebl-3.14.3-23.3.el6_8.x86_64, nss-sysinit-3.21.0-8.el6.x86_64, nss-tools-3.21.0-8.el6.x86_64, nss-util-3.21.0-2.el6.x86_64, openldap-2.4.40-12.el6.x86_64, openssh-5.3p1-117.el6.x86_64, openssh-clients-5.3p1-117.el6.x86_64, openssh-server-5.3p1-117.el6.x86_64, openssl-1.0.1e-48.el6.x86_64, p11-kit-0.18.5-2.el6_5.2.x86_64, p11-kit-trust-0.18.5-2.el6_5.2.x86_64, pam-1.1.1-22.el6.x86_64, passwd-0.77-7.el6.x86_64, pciutils-libs-3.1.10-4.el6.x86_64, pcre-7.8-7.el6.x86_64, pdns-4.0.3-2.el6.MIND.x86_64, pdns-backend-postgresql-4.0.3-2.el6.MIND.x86_64, pdns-tools-4.0.3-2.el6.MIND.x86_64, pgdg-centos96-9.6-3.noarch, pgdg-redhat96-9.6-3.noarch, pgpool-II-release-3.6-1.noarch, pinentry-0.7.6-8.el6.x86_64, pkgconfig-0.23-9.1.el6.x86_64, plymouth-0.8.3-27.el6.centos.1.x86_64, plymouth-core-libs-0.8.3-27.el6.centos.1.x86_64, plymouth-scripts-0.8.3-27.el6.centos.1.x86_64, policycoreutils-2.0.83-29.el6.x86_64, popt-1.13-7.el6.x86_64, postfix-2.6.6-6.el6_7.1.x86_64, postgresql96-9.6.3-1PGDG.rhel6.x86_64, postgresql96-contrib-9.6.3-1PGDG.rhel6.x86_64, postgresql96-libs-9.6.3-1PGDG.rhel6.x86_64, postgresql96-server-9.6.3-1PGDG.rhel6.x86_64, procps-3.2.8-36.el6.x86_64, psmisc-22.6-19.el6_5.x86_64, pth-2.0.7-9.3.el6.x86_64, pygpgme-0.1-18.20090824bzr68.el6.x86_64, python-2.6.6-64.el6.x86_64, python-iniparse-0.3.1-2.1.el6.noarch, python-libs-2.6.6-64.el6.x86_64, python-pycurl-7.19.0-9.el6.x86_64, python-urlgrabber-3.9.1-11.el6.noarch, readline-6.0-4.el6.x86_64, redhat-logos-60.0.14-12.el6.centos.noarch, rootfiles-8.1-6.1.el6.noarch, rpm-4.8.0-55.el6.x86_64, rpm-libs-4.8.0-55.el6.x86_64, rpm-python-4.8.0-55.el6.x86_64, rsyslog-5.8.10-10.el6_6.x86_64, sed-4.2.1-10.el6.x86_64, selinux-policy-3.7.19-292.el6.noarch, selinux-policy-targeted-3.7.19-292.el6.noarch, setup-2.8.14-20.el6_4.1.noarch, shadow-utils-4.1.5.1-5.el6.x86_64, shared-mime-info-0.70-6.el6.x86_64, slang-2.2.1-1.el6.x86_64, sqlite-3.6.20-1.el6_7.2.x86_64, sudo-1.8.6p3-24.el6.x86_64, system-config-firewall-base-1.2.27-7.2.el6_6.noarch, sysvinit-tools-2.87-6.dsf.el6.x86_64, tar-1.23-14.el6.x86_64, tcp_wrappers-libs-7.6-58.el6.x86_64, telnet-0.17-48.el6.x86_64, tzdata-2016c-1.el6.noarch, udev-147-2.73.el6.x86_64, upstart-0.6.5-16.el6.x86_64, ustr-1.0.4-9.1.el6.x86_64, util-linux-ng-2.17.2-12.24.el6.x86_64, vim-minimal-7.4.629-5.el6.x86_64, wget-1.12-10.el6.x86_64, which-2.19-6.el6.x86_64, xfsprogs-3.1.1-19.el6.x86_64, xz-libs-4.999.9-0.5.beta.20091007git.el6.x86_64, yum-3.2.29-73.el6.centos.noarch, yum-metadata-parser-1.1.2-16.el6.x86_64, yum-plugin-fastestmirror-1.1.30-37.el6.noarch, zabbix-agent-3.2.6-1.el6.x86_64, zabbix-get-3.2.6-1.el6.x86_64, zabbix-sender-3.2.6-1.el6.x86_64, zlib-1.2.3-29.el6.x86_64]
82:system.swap.size[all,free]                    [u|828456960]
83:system.swap.in[all]                           [u|173]
84:system.swap.out[all]                          [u|6651]
85:system.uptime                                 [u|5223]
86:system.boottime                               [u|1499311408]
87:sensor[w83781d-i2c-0-2d,temp1]                [m|ZBX_NOTSUPPORTED] [Cannot obtain sensor information.]
88:net.tcp.service[ssh,127.0.0.1,22]             [u|1]
89:net.tcp.service.perf[ssh,127.0.0.1,22]        [d|0.010699]
90:net.udp.service[ntp,127.0.0.1,123]            [u|0]
91:net.udp.service.perf[ntp,127.0.0.1,123]       [d|0.000000]
92:system.hostname                               [s|DNS]
93:pg.modver                                     [s|libzbxpgsql 1.1.0, compiled for Zabbix 3.2.3]
94:pg.connect                                    [u|1]
95:pg.version                                    [s|PostgreSQL 9.6.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18), 64-bit]
96:pg.starttime                                  [s|2017-07-06 11:50:11.987575+07]
97:pg.uptime                                     [u|19]
98:pg.prepared_xacts_count                       [u|0]
99:pg.prepared_xacts_ratio                       [d|0.000000]
100:pg.prepared_xacts_age                         [u|0]
101:pg.setting[,,data_directory]                  [m|ZBX_NOTSUPPORTED] [Unknown error.]
zabbix_agentd [17856]: No query found for SELECT 'Lorem ipsum dolor';
zabbix_agentd [17856]: No query found for SELECT pg_backend_pid();
103:pg.query.string[,,SELECT 'Lorem ipsum dolor';] [s|Lorem ipsum dolor]
zabbix_agentd [17856]: No query found for SELECT CAST(1234 AS double precision);
104:pg.query.integer[,,SELECT pg_backend_pid();]  [u|17885]
zabbix_agentd [17856]: No query found for SELECT * FROM pg_database;
105:pg.query.double[,,SELECT CAST(1234 AS double precision);] [d|1234.000000]
107:pg.backends.count                             [u|1]
108:pg.backends.free                              [d|298.000000]
109:pg.backends.ratio                             [d|0.003333]
110:pg.queries.longest                            [d|0.000000]
111:pg.checkpoints_timed                          [u|13]
112:pg.checkpoints_req                            [u|0]
113:pg.checkpoint_write_time                      [d|0.000000]
114:pg.checkpoint_sync_time                       [d|0.000000]
115:pg.checkpoint_avg_interval                    [d|392.735990]
116:pg.checkpoint_time_ratio                      [d|0.000000]
117:pg.buffers_checkpoint                         [u|0]
118:pg.buffers_clean                              [u|0]
119:pg.maxwritten_clean                           [u|0]
120:pg.buffers_backend                            [u|0]
121:pg.buffers_backend_fsync                      [u|0]
122:pg.buffers_alloc                              [u|6010]
123:pg.stats_reset                                [s|2017-07-06 10:25:26.598042+07]
124:pg.stats_reset_interval                       [u|5105]
zabbix_agentd [17856]: Error: PostgreSQL: fe_sendauth: no password supplied
127:]
zabbix_agentd [17856]: Error: PostgreSQL: fe_sendauth: no password supplied
129:]
zabbix_agentd [17856]: Error: PostgreSQL: fe_sendauth: no password supplied
132:]
zabbix_agentd [17856]: Error: PostgreSQL: fe_sendauth: no password supplied
135:]
136:pg.db.size                                    [u|30220324]
137:pg.table.size                                 [u|8192]
138:pg.table.rows                                 [u|69]
139:pg.table.children[,,pg_database]              [u|0]
140:pg.table.children.size[,,pg_database]         [u|0]
141:pg.table.children.rows[,,pg_database]         [u|0]
142:pg.index.size                                 [u|3375104]
143:pg.index.rows                                 [u|40592]
144:pg.tablespace.size[,,pg_default]              [u|30244900]
145:pg.namespace.size[,,pg_catalog]               [u|2883584]
146:pg.schema.size[,,pg_catalog]                  [u|2883584]
147:pg.db.numbackends                             [u|2]
148:pg.db.xact_commit                             [u|84545]
149:pg.db.xact_rollback                           [u|0]
150:pg.db.blks_read                               [u|5868]
151:pg.db.blks_hit                                [u|17086974]
152:pg.db.blks_ratio                              [d|0.999657]
153:pg.db.tup_returned                            [u|19796815]
154:pg.db.tup_fetched                             [u|8590741]
155:pg.db.tup_inserted                            [u|0]
156:pg.db.tup_updated                             [u|0]
157:pg.db.tup_deleted                             [u|0]
158:pg.db.conflicts                               [u|0]
159:pg.db.temp_files                              [u|0]
160:pg.db.temp_bytes                              [u|0]
161:pg.db.deadlocks                               [u|0]
162:pg.db.blk_read_time                           [d|0.000000]
163:pg.db.blk_write_time                          [d|0.000000]
164:pg.db.stats_reset[,,postgres,,,]              [s|2017-07-06 10:25:30.03871+07]
165:pg.db.xid_age                                 [u|143]
166:pg.table.seq_scan                             [u|664]
167:pg.table.seq_tup_read                         [u|47144]
168:pg.table.idx_scan                             [u|21]
169:pg.table.idx_scan_ratio                       [d|0.973300]
170:pg.table.idx_tup_fetch                        [u|9]
171:pg.table.n_tup_ins                            [u|0]
172:pg.table.n_tup_upd                            [u|0]
173:pg.table.n_tup_del                            [u|0]
174:pg.table.n_tup_hot_upd                        [u|0]
175:pg.table.n_live_tup                           [u|0]
176:pg.table.n_dead_tup                           [u|0]
177:pg.table.n_mod_since_analyze                  [u|0]
178:pg.table.last_vacuum[,,pg_database]           [s|]
179:pg.table.last_autovacuum[,,pg_database]       [s|]
180:pg.table.last_analyze[,,pg_database]          [s|]
181:pg.table.last_autoanalyze[,,pg_database]      [s|]
182:pg.table.vacuum_count                         [u|0]
183:pg.table.autovacuum_count                     [u|0]
184:pg.table.analyze_count                        [u|0]
185:pg.table.autoanalyze_count                    [u|0]
186:pg.table.heap_blks_read                       [u|3]
187:pg.table.heap_blks_hit                        [u|1334]
188:pg.table.heap_blks_ratio                      [d|0.999645]
189:pg.table.idx_blks_read                        [u|10]
190:pg.table.idx_blks_hit                         [u|103]
191:pg.table.idx_blks_ratio                       [d|0.999812]
192:pg.table.toast_blks_read                      [u|0]
193:pg.table.toast_blks_hit                       [u|0]
194:pg.table.toast_blks_ratio                     [d|0.992075]
195:pg.table.tidx_blks_read                       [u|0]
196:pg.table.tidx_blks_hit                        [u|0]
197:pg.table.tidx_blks_ratio                      [d|0.997129]
198:pg.index.idx_scan                             [u|4011180]
199:pg.index.idx_tup_read                         [u|5199975]
200:pg.index.idx_tup_fetch                        [u|5195511]
201:pg.index.idx_blks_read                        [u|10]
202:pg.index.idx_blks_hit                         [u|103]
203:pg.index.idx_blks_ratio                       [d|0.999807]

in  log file show me
zabbix_agent.log

 30098:20170706:133636.328 Got signal [signal:15(SIGTERM),sender_pid:28329,sender_uid:0,reason:0]. Exiting ...
 30098:20170706:133636.395 Zabbix Agent stopped. Zabbix 3.2.6 (revision 67849).
 28352:20170706:133636.626 Starting Zabbix Agent [DNS]. Zabbix 3.2.6 (revision 67849).
 28352:20170706:133636.626 **** Enabled features ****
 28352:20170706:133636.626 IPv6 support:          YES
 28352:20170706:133636.626 TLS support:           YES
 28352:20170706:133636.626 **************************
 28352:20170706:133636.626 using configuration file: /etc/zabbix/zabbix_agentd.conf
 28352:20170706:133636.627 starting agent module libzbxpgsql 1.1.0
 28352:20170706:133636.627 using module configuration file: /etc/zabbix/libzbxpgsql.conf
 28352:20170706:133636.653 loaded modules: libzbxpgsql.so
 28352:20170706:133636.655 agent #0 started [main process]
 28356:20170706:133636.656 agent #4 started [listener #3]
 28355:20170706:133636.656 agent #3 started [listener #2]
 28357:20170706:133636.656 agent #5 started [active checks #1]
 28354:20170706:133636.656 agent #2 started [listener #1]
 28353:20170706:133636.656 agent #1 started [collector]

and zabbix_get ..... pg.connect now it return 1

in my project  
I had setting network by
server(name: Zabbix) : 192.168.56.220 : 10050   , listen 10051
client (name: DNS) :192.168.56.223: 10050 -> with agent 
postgres on client : 192.168.56.223  :5432
user postgres : pdns , database : pdns 

and in zabbix console
![default](https://user-images.githubusercontent.com/21307877/27898838-e21eb7b4-6251-11e7-8558-d2866c31ee97.png)

I confused I may had forgot something ?  
sorry if i distub you

**Comment by por16378** [comment]
I found my problem .
It must to set Hostname on file configuration   as name as  hostname of setting host in zabbix console  
That's work perfect .I like it ,thank you

**Comment by cavaliercoder** [comment]
Thanks for sharing your solution. I hope you enjoy the plugin.
