### ISSUE TITLE
Documentation is not new-user-friendly

### ISSUE THREAD

**Issue by antiphase** [cavaliercoder/libzbxpgsql#97]
I'm trying to get this to monitor a Postgres 9.4 server from Zabbix 3.2, and the documentation is inadequate for a new user to even get basic checks up and running. It seems one has to be an expert Zabbix user to fill in a lot of gaps in terminology and understand expected behaviour, and I am not. Zabbix itself does not require a high level of expertise to use out of the box, nor does Postgres, so this is an anomaly.
I'd offer to help improve what you have, but I can't even make a basic example work using what documentation there is because of problems with authentication and almost no troubleshooting instructions other than "turn on debugging", so I don't actually know where to go with this now. Reverse-engineering the source code is not practical for every single thing I need to use.

**Comment by cavaliercoder** [comment]
The feedback I usually get for this module requests more and more flexibility, coverage and support for diverse PostgreSQL and Zabbix configurations. This means that the module itself becomes more powerful, but more complicated. It's not really possible to write step-by-step instruction that would be valid for even a portion of configurations in the wild. Are you using MD5 auth or Ident? Pgpass files, environment variables or connection strings? Active checks or passive? Connection pooling or direct?

This module and its documentation is definitely intended for a power-user audience. I currently have no intention of duplicating any information already available in the Zabbix or PostgreSQL documentation. You will benefit much more from switching between the documentation for Zabbix, PostgreSQL and this module.

Monitoring a database is complicated. The metrics this module returns and triggers on are complicated. I trust you will learn heaps and be a better SysAdmin for taking the time to truly understand your configuration and the best way to monitor it.
